import { ExamData } from "./exam-store";

export const ADDITIONAL_EXAMS: ExamData[] = [
  // ===== KHỐI 10: Đề kiểm tra 15p & Giữa kỳ =====
  {
    id: "exam-g10-u1-15m",
    title: "Đề kiểm tra 15 phút: Unit 1 - Family Life (Lớp 10)",
    description: "Đề kiểm tra nhanh ngữ âm /br/, /kr/, /tr/, thì Hiện tại đơn và Hiện tại tiếp diễn chuẩn SGK Tiếng Anh 10 Global Success.",
    grade: "10",
    subject: "Tiếng Anh",
    unitSlug: "unit-1-family-life",
    durationMinutes: 15,
    pinCode: "101501",
    shuffleQuestions: true,
    shuffleOptions: true,
    antiCheatEnabled: true,
    showAnswersAfterSubmit: true,
    createdAt: new Date().toISOString(),
    authorName: "Ban Chuyên Môn THPT Lớp 10",
    questions: [
      {
        id: "g10-q1",
        questionNumber: 1,
        questionText: "Which word has the underlined part pronounced differently from the others?",
        options: [
          { key: "A", text: "breadwinner" },
          { key: "B", text: "breakfast" },
          { key: "C", text: "heavy" },
          { key: "D", text: "clean" },
        ],
        correctAnswer: "D",
        explanation: "Các đáp án A, B, C có 'ea' phát âm là /e/. Đáp án D 'clean' có 'ea' phát âm là /iː/.",
        difficulty: "easy",
      },
      {
        id: "g10-q2",
        questionNumber: 2,
        questionText: "In many Asian cultures, the father is traditionally considered the primary ________ of the family.",
        options: [
          { key: "A", text: "breadwinner" },
          { key: "B", text: "homemaker" },
          { key: "C", text: "servant" },
          { key: "D", text: "bystander" },
        ],
        correctAnswer: "A",
        explanation: "'breadwinner' là người trụ cột kinh tế đi làm nuôi gia đình.",
        difficulty: "easy",
      },
      {
        id: "g10-q3",
        questionNumber: 3,
        questionText: "Look! Lan ________ the groceries in the kitchen right now.",
        options: [
          { key: "A", text: "unpacks" },
          { key: "B", text: "is unpacking" },
          { key: "C", text: "unpacked" },
          { key: "D", text: "has unpacked" },
        ],
        correctAnswer: "B",
        explanation: "Có dấu hiệu 'Look!' và 'right now' diễn tả hành động đang xảy ra tại thời điểm nói → dùng thì Hiện tại tiếp diễn.",
        difficulty: "medium",
      },
      {
        id: "g10-q4",
        questionNumber: 4,
        questionText: "Doing chores together helps teenagers develop a strong sense of ________.",
        options: [
          { key: "A", text: "responsibility" },
          { key: "B", text: "responsible" },
          { key: "C", text: "responsibly" },
          { key: "D", text: "irresponsible" },
        ],
        correctAnswer: "A",
        explanation: "Sau giới từ 'of' cần một danh từ. 'sense of responsibility' là cụm từ mang nghĩa 'tinh thần trách nhiệm'.",
        difficulty: "medium",
      },
      {
        id: "g10-q5",
        questionNumber: 5,
        questionText: "My brother ________ games every evening, but today he ________ with the laundry.",
        options: [
          { key: "A", text: "plays / is helping" },
          { key: "B", text: "is playing / helps" },
          { key: "C", text: "plays / helps" },
          { key: "D", text: "is playing / is helping" },
        ],
        correctAnswer: "A",
        explanation: "Mệnh đề 1 có 'every evening' (thói quen) → Hiện tại đơn (plays). Mệnh đề 2 có 'today' (sự việc tạm thời khác thường ngày) → Hiện tại tiếp diễn (is helping).",
        difficulty: "hard",
      },
    ],
  },

  {
    id: "exam-g10-midterm1",
    title: "Đề thi Giữa Học kỳ 1 — Tiếng Anh 10 Global Success",
    description: "Đề thi chuẩn cấu trúc 40 câu trắc nghiệm bao quát Unit 1 (Family Life), Unit 2 (Humans and the Environment) và Unit 3 (Music).",
    grade: "10",
    subject: "Tiếng Anh",
    unitSlug: "unit-2-humans-and-the-environment",
    durationMinutes: 45,
    pinCode: "104502",
    shuffleQuestions: true,
    shuffleOptions: true,
    antiCheatEnabled: true,
    showAnswersAfterSubmit: true,
    createdAt: new Date().toISOString(),
    authorName: "Hội Đồng Đề Thi Khối 10",
    questions: [
      {
        id: "g10-mid-1",
        questionNumber: 1,
        questionText: "Mark the word whose stress pattern differs from the other three.",
        options: [
          { key: "A", text: "emission" },
          { key: "B", text: "footprint" },
          { key: "C", text: "appliance" },
          { key: "D", text: "pollutant" },
        ],
        correctAnswer: "B",
        explanation: "Footprint trọng âm 1. Các từ còn lại emission, appliance, pollutant đều có trọng âm rơi vào âm tiết thứ 2.",
        difficulty: "medium",
      },
      {
        id: "g10-mid-2",
        questionNumber: 2,
        questionText: "We can reduce our carbon footprint by cutting down on ________ plastic products.",
        options: [
          { key: "A", text: "single-use" },
          { key: "B", text: "eco-friendly" },
          { key: "C", text: "sustainable" },
          { key: "D", text: "organic" },
        ],
        correctAnswer: "A",
        explanation: "'single-use plastic' là đồ nhựa dùng một lần. Cần cắt giảm đồ nhựa dùng 1 lần để bảo vệ môi trường.",
        difficulty: "easy",
      },
      {
        id: "g10-mid-3",
        questionNumber: 3,
        questionText: "The judges were completely blown away by her breathtaking musical ________.",
        options: [
          { key: "A", text: "performance" },
          { key: "B", text: "performing" },
          { key: "C", text: "performer" },
          { key: "D", text: "performed" },
        ],
        correctAnswer: "A",
        explanation: "Sau tính từ 'musical' cần một danh từ chỉ màn trình diễn: 'performance'.",
        difficulty: "medium",
      },
      {
        id: "g10-mid-4",
        questionNumber: 4,
        questionText: "Nam: 'Would you like to join our volunteer group this weekend?' — Mai: '________'",
        options: [
          { key: "A", text: "I'd love to! Count me in." },
          { key: "B", text: "No, I don't like music." },
          { key: "C", text: "Yes, you are right." },
          { key: "D", text: "Never mind, it doesn't matter." },
        ],
        correctAnswer: "A",
        explanation: "Đáp lại lời mời tham gia hoạt động tình nguyện bằng sự đồng ý nhiệt tình: 'I'd love to! Count me in.' (Tôi rất thích! Hãy tính cả tôi nữa nhé).",
        difficulty: "easy",
      },
      {
        id: "g10-mid-5",
        questionNumber: 5,
        questionText: "Solar panels are installed on roofs in order to ________ electricity bills.",
        options: [
          { key: "A", text: "lower" },
          { key: "B", text: "rise" },
          { key: "C", text: "waste" },
          { key: "D", text: "pollute" },
        ],
        correctAnswer: "A",
        explanation: "'lower electricity bills' nghĩa là giảm hóa đơn tiền điện.",
        difficulty: "easy",
      },
    ],
  },

  // ===== KHỐI 11: Đề Học kỳ & Nâng cao =====
  {
    id: "exam-g11-sem1",
    title: "Đề thi Học kỳ 1: Tiếng Anh 11 — Đô thị tương lai & Di sản (Global Success)",
    description: "Chuyên đề Ngữ pháp Danh động từ (Gerunds), Phân từ hoàn thành (Perfect Participles) và Từ vựng Unit 3, 4, 5.",
    grade: "11",
    subject: "Tiếng Anh",
    unitSlug: "unit-3-cities-of-the-future",
    durationMinutes: 45,
    pinCode: "114501",
    shuffleQuestions: true,
    shuffleOptions: true,
    antiCheatEnabled: true,
    showAnswersAfterSubmit: true,
    createdAt: new Date().toISOString(),
    authorName: "Tổ Ngoại Ngữ Chuyên Sư Phạm",
    questions: [
      {
        id: "g11-sem-1",
        questionNumber: 1,
        questionText: "Smart cities utilize IoT sensors to ________ traffic flow and eliminate congestion.",
        options: [
          { key: "A", text: "monitor" },
          { key: "B", text: "ignore" },
          { key: "C", text: "contaminate" },
          { key: "D", text: "worsen" },
        ],
        correctAnswer: "A",
        explanation: "'monitor traffic flow' là giám sát và theo dõi lưu lượng giao thông.",
        difficulty: "medium",
      },
      {
        id: "g11-sem-2",
        questionNumber: 2,
        questionText: "________ the assignment ahead of time, Tuan felt completely relaxed during the weekend.",
        options: [
          { key: "A", text: "Having completed" },
          { key: "B", text: "Completed" },
          { key: "C", text: "Being completed" },
          { key: "D", text: "Have completed" },
        ],
        correctAnswer: "A",
        explanation: "Dùng phân từ hoàn thành 'Having + V3/ed' để nhấn mạnh hành động nộp bài xong trước đã hoàn tất trước hành động cảm thấy thư thái trong quá khứ.",
        difficulty: "hard",
      },
      {
        id: "g11-sem-3",
        questionNumber: 3,
        questionText: "Preserving historical monuments requires a delicate balance between tourism and ________.",
        options: [
          { key: "A", text: "conservation" },
          { key: "B", text: "destruction" },
          { key: "C", text: "pollution" },
          { key: "D", text: "industrialization" },
        ],
        correctAnswer: "A",
        explanation: "'conservation' là sự bảo tồn. 'balance between tourism and conservation' là sự cân bằng giữa du lịch và bảo tồn di sản.",
        difficulty: "medium",
      },
    ],
  },

  // ===== KHỐI 12: Đề Thi Thử Tốt Nghiệp THPT Quốc Gia (Định dạng Đổi mới BGD) =====
  {
    id: "exam-g12-thptqg-2025",
    title: "Đề Thi Thử Tốt Nghiệp THPT Quốc Gia 2025/2026 môn Tiếng Anh (Chuẩn Cấu Trúc Đổi Mới BGD)",
    description: "Đề chuẩn ma trận thi Tốt nghiệp THPT: Ngữ âm, Trọng âm, Tìm từ đồng nghĩa/trái nghĩa, Chức năng giao tiếp, Điền từ đoạn văn, Đọc hiểu chuyên sâu và Kết hợp câu.",
    grade: "12",
    subject: "Tiếng Anh",
    unitSlug: "unit-6-artificial-intelligence",
    durationMinutes: 50,
    pinCode: "122025",
    shuffleQuestions: true,
    shuffleOptions: true,
    antiCheatEnabled: true,
    showAnswersAfterSubmit: true,
    createdAt: new Date().toISOString(),
    authorName: "Hội Đồng Biên Soạn Đề Thi Quốc Gia (Global Success)",
    questions: [
      {
        id: "thpt-1",
        questionNumber: 1,
        questionText: "Mark the letter A, B, C, or D to indicate the word whose underlined part differs from the other three in pronunciation:\nA. dedicated   B. visited   C. influenced   D. promoted",
        options: [
          { key: "A", text: "dedicated" },
          { key: "B", text: "visited" },
          { key: "C", text: "influenced" },
          { key: "D", text: "promoted" },
        ],
        correctAnswer: "C",
        explanation: "Quy tắc phát âm đuôi -ed: 'influenced' kết thúc bằng âm vô thanh /s/ nên phát âm là /t/. Các từ còn lại kết thúc bằng /t/ hoặc /d/ nên phát âm là /ɪd/.",
        difficulty: "easy",
      },
      {
        id: "thpt-2",
        questionNumber: 2,
        questionText: "Mark the letter A, B, C, or D to indicate the word that differs from the other three in the position of primary stress:\nA. visionary   B. biography   C. resilience   D. trajectory",
        options: [
          { key: "A", text: "visionary" },
          { key: "B", text: "biography" },
          { key: "C", text: "resilience" },
          { key: "D", text: "trajectory" },
        ],
        correctAnswer: "A",
        explanation: "Visionary có trọng âm rơi vào âm tiết 1 (/ˈvɪʒənri/). Các từ biography (/baɪˈɒɡrəfi/), resilience (/rɪˈzɪliəns/), trajectory (/trəˈdʒektəri/) đều có trọng âm rơi vào âm tiết thứ 2.",
        difficulty: "medium",
      },
      {
        id: "thpt-3",
        questionNumber: 3,
        questionText: "The rapid integration of artificial intelligence into workplaces has caused ________ changes in labor requirements.",
        options: [
          { key: "A", text: "profound" },
          { key: "B", text: "shallow" },
          { key: "C", text: "trivial" },
          { key: "D", text: "insignificant" },
        ],
        correctAnswer: "A",
        explanation: "'profound changes' là cụm từ học thuật có nghĩa 'những thay đổi sâu sắc, toàn diện'.",
        difficulty: "hard",
      },
      {
        id: "thpt-4",
        questionNumber: 4,
        questionText: "Mark the letter A, B, C, or D to indicate the word CLOSEST in meaning to the underlined word:\nHer sheer *perseverance* allowed her to conquer extreme academic challenges.",
        options: [
          { key: "A", text: "determination" },
          { key: "B", text: "hesitation" },
          { key: "C", text: "reluctance" },
          { key: "D", text: "carelessness" },
        ],
        correctAnswer: "A",
        explanation: "'Perseverance' (sự kiên trì, bền chí) đồng nghĩa với 'determination' (sự quyết tâm cao độ).",
        difficulty: "medium",
      },
      {
        id: "thpt-5",
        questionNumber: 5,
        questionText: "Mark the letter A, B, C, or D to indicate the word OPPOSITE in meaning to the underlined word:\nDoctors praised his *humble* attitude despite his historic scientific breakthrough.",
        options: [
          { key: "A", text: "arrogant" },
          { key: "B", text: "modest" },
          { key: "C", text: "polite" },
          { key: "D", text: "cautious" },
        ],
        correctAnswer: "A",
        explanation: "'Humble' (khiêm tốn, giản dị) trái nghĩa với 'arrogant' (ngạo mạn, kiêu căng tự đắc).",
        difficulty: "medium",
      },
      {
        id: "thpt-6",
        questionNumber: 6,
        questionText: "Peter and Mary are discussing online media.\nPeter: 'Social media users should always verify news sources before sharing.'\nMary: '________. Misinformation spreads alarmingly fast.'",
        options: [
          { key: "A", text: "I couldn't agree more" },
          { key: "B", text: "That's completely untrue" },
          { key: "C", text: "I don't think so" },
          { key: "D", text: "It's none of my business" },
        ],
        correctAnswer: "A",
        explanation: "'I couldn't agree more' (Tôi hoàn toàn đồng ý với bạn) là thành ngữ thể hiện sự đồng tình 100%.",
        difficulty: "easy",
      },
      {
        id: "thpt-7",
        questionNumber: 7,
        questionText: "Had Viet Nam not implemented prompt digital policies, the nationwide tech transition ________ so swiftly.",
        options: [
          { key: "A", text: "would not have occurred" },
          { key: "B", text: "will not occur" },
          { key: "C", text: "did not occur" },
          { key: "D", text: "would not occur" },
        ],
        correctAnswer: "A",
        explanation: "Đảo ngữ câu điều kiện loại 3: 'Had + S + not + V3/ed, S + would/could + have + V3/ed' diễn tả giả định trái ngược với quá khứ.",
        difficulty: "hard",
      },
      {
        id: "thpt-8",
        questionNumber: 8,
        questionText: "Mark the sentence that best combines the two given sentences:\n'The candidate lacked digital literacy skills. He failed to secure the senior IT position.'",
        options: [
          { key: "A", text: "If the candidate had possessed digital literacy skills, he could have secured the senior IT position." },
          { key: "B", text: "Because he was skilled in digital literacy, he failed to secure the IT position." },
          { key: "C", text: "Although he had digital literacy skills, he failed to get the job." },
          { key: "D", text: "Unless he lacked digital literacy skills, he would fail the interview." },
        ],
        correctAnswer: "A",
        explanation: "Sự thật trong quá khứ: ứng viên thiếu kỹ năng và trượt phỏng vấn → dùng câu điều kiện loại 3 để viết lại kết quả giả định: 'Nếu anh ta có kỹ năng thì anh ta đã có thể giành được công việc đó'.",
        difficulty: "hard",
      },
    ],
  },
];
