# -*- coding: utf-8 -*-
"""
Boost Grade 12 vocabulary so that every single unit reaches 52-60 words!
Curated from textbook syllabus, VietJack, Loigiaihay, and Cambridge Dictionary.
"""
import json
import os

G12_EXTRA = {
    "unit-1-life-stories-we-admire": [
        ("statesman", "n", "nhà chính trị lỗi lạc, chính khách có tầm", "/ˈsteɪtsmən/",
         "President Ho Chi Minh is remembered as an internationally respected statesman.",
         "Chủ tịch Hồ Chí Minh được tưởng nhớ như một nhà chính khách lỗi lạc được quốc tế kính trọng.",
         ["distinguished statesman", "visionary statesman"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("intellectual rigor", "n.phr", "sự nghiêm cẩn và chặt chẽ trong học thuật", "/ˌɪntəˈlektʃuəl ˈrɪɡə(r)/",
         "Her scientific papers are celebrated for profound insights and intellectual rigor.",
         "Các công trình khoa học của bà được ca ngợi bởi sự sâu sắc và tính nghiêm cẩn học thuật.",
         ["display intellectual rigor", "demand intellectual rigor"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("moral fortitude", "n.phr", "sự kiên định và bản lĩnh đạo đức", "/ˈmɒrəl ˈfɔːtɪtjuːd/",
         "He stood firm against corrupt pressures with remarkable moral fortitude.",
         "Ông đã đứng vững trước những sức ép tiêu cực với bản lĩnh đạo đức phi thường.",
         ["show moral fortitude", "admire moral fortitude"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("selfless devotion", "n.phr", "sự cống hiến quên mình vì nhân dân", "/ˈselfləs dɪˈvəʊʃn/",
         "Doctors in remote communes serve with selfless devotion through long stormy nights.",
         "Các y bác sĩ vùng sâu vùng xa cống hiến hết mình quên thân qua những đêm mưa bão.",
         ["admire selfless devotion", "lifelong selfless devotion"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("legendary hero", "n.phr", "vị anh hùng huyền thoại trong sử sách", "/ˈledʒəndri ˈhɪərəʊ/",
         "General Tran Hung Dao is revered as a legendary hero who defeated three Mongol invasions.",
         "Hưng Đạo Đại Vương Trần Quốc Tuấn là vị anh hùng huyền thoại ba lần đánh tan quân Nguyên Mông.",
         ["revere a legendary hero", "feats of a legendary hero"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("unshakable resolve", "n.phr", "quyết tâm sắt đá không gì lay chuyển", "/ʌnˈʃeɪkəbl rɪˈzɒlv/",
         "The youth marched with unshakable resolve to build a prosperous homeland.",
         "Thanh niên tiến bước với quyết tâm sắt đá xây dựng quê hương giàu đẹp.",
         ["demonstrate unshakable resolve", "unshakable resolve to succeed"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("historic turning point", "n.phr", "bước ngoặt lịch sử làm xoay chuyển thời cuộc", "/hɪˈstɒrɪk ˈtɜːnɪŋ pɔɪnt/",
         "The August Revolution of 1945 was a monumental historic turning point for Vietnam.",
         "Cách mạng Tháng Tám năm 1945 là bước ngoặt lịch sử vĩ đại của dân tộc Việt Nam.",
         ["mark a historic turning point", "crucial turning point"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("illustrious career", "n.phr", "sự nghiệp lẫy lừng, vẻ vang", "/ɪˈlʌstriəs kəˈrɪə(r)/",
         "The professor capped an illustrious career with the national scientific prize.",
         "Vị giáo sư đã khép lại sự nghiệp lẫy lừng bằng giải thưởng khoa học cấp quốc gia.",
         ["conclude an illustrious career", "illustrious medical career"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("philanthropic mission", "n.phr", "sứ mệnh từ thiện nhân đạo cao cả", "/ˌfɪlənˈθrɒpɪk ˈmɪʃn/",
         "Her philanthropic mission built thirty primary schools in mountain hamlets.",
         "Sứ mệnh thiện nguyện của bà đã xây dựng ba mươi trường tiểu học tại các bản vùng cao.",
         ["embark on a philanthropic mission", "support philanthropic missions"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("heroic sacrifice", "n.phr", "sự hy sinh anh dũng vì tổ quốc", "/həˈrəʊɪk ˈsækrɪfaɪs/",
         "We bow our heads in gratitude for the heroic sacrifice of front-line medics.",
         "Chúng ta nghiêng mình biết ơn sự hy sinh anh dũng của các chiến sĩ áo trắng tuyến đầu.",
         ["commemorate heroic sacrifice", "honor heroic sacrifice"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-2-a-multicultural-world": [
        ("cultural assimilation", "n.phr", "sự đồng hóa văn hóa vào xã hội", "/ˈkʌltʃərəl əˌsɪməˈleɪʃn/",
         "Sociologists study how second-generation immigrants navigate cultural assimilation.",
         "Các nhà xã hội học nghiên cứu cách thế hệ người nhập cư thứ hai thích nghi văn hóa.",
         ["speed of cultural assimilation", "resist cultural assimilation"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("multicultural harmony", "n.phr", "sự hòa hợp giữa các nền văn hóa", "/ˌmʌltiˈkʌltʃərəl ˈhɑːməni/",
         "Singapore is celebrated globally for maintaining vibrant multicultural harmony.",
         "Singapore được cả thế giới ngợi ca nhờ duy trì sự hòa hợp đa văn hóa rực rỡ.",
         ["promote multicultural harmony", "preserve multicultural harmony"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("ethnic diversity", "n.phr", "sự phong phú đa dạng của các dân tộc", "/ˌeθnɪk daɪˈvɜːsəti/",
         "The central highlands showcase remarkable ethnic diversity in musical traditions.",
         "Vùng đất Tây Nguyên thể hiện sự đa dạng dân tộc đáng nể qua truyền thống âm nhạc.",
         ["celebrate ethnic diversity", "rich ethnic diversity"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("cross-cultural awareness", "n.phr", "nhận thức và sự tinh tế liên văn hóa", "/ˌkrɒs ˈkʌltʃərəl əˈweənəs/",
         "Studying abroad builds cross-cultural awareness that prevents unintentional social blunders.",
         "Du học giúp rèn luyện nhận thức liên văn hóa để tránh những sơ suất vô ý trong giao tiếp.",
         ["develop cross-cultural awareness", "heightened awareness"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("cultural hybridity", "n.phr", "sự giao thoa lai ghép văn hóa độc đáo", "/ˈkʌltʃərəl haɪˈbrɪdəti/",
         "Banh mi is a delicious culinary example of Vietnamese-French cultural hybridity.",
         "Bánh mì là ví dụ ẩm thực thơm ngon cho sự giao thoa lai ghép văn hóa Việt - Pháp.",
         ["expression of cultural hybridity", "modern cultural hybridity"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("heritage preservation", "n.phr", "gìn giữ và bảo tồn di sản cha ông", "/ˈherɪtɪdʒ ˌprezəˈveɪʃn/",
         "Funds are allocated for intangible heritage preservation like Quan Ho singing.",
         "Ngân sách được phân bổ cho việc gìn giữ di sản phi vật thể như dân ca Quan họ.",
         ["advocate heritage preservation", "fund heritage preservation"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("linguistic diversity", "n.phr", "sự đa dạng ngôn ngữ và tiếng nói", "/lɪŋˈɡwɪstɪk daɪˈvɜːsəti/",
         "UNESCO actively records dying dialects to protect global linguistic diversity.",
         "UNESCO tích cực ghi chép các phương ngôn nguy cấp để bảo vệ đa dạng ngôn ngữ.",
         ["protect linguistic diversity", "rich linguistic diversity"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("cultural sensitivity", "n.phr", "sự tế nhị và tôn trọng chuẩn mực văn hóa", "/ˈkʌltʃərəl ˌsensəˈtɪvəti/",
         "Displaying cultural sensitivity when greeting international guests builds mutual trust.",
         "Thể hiện sự tế nhị văn hóa khi chào đón khách quốc tế giúp xây đắp lòng tin cậy.",
         ["demonstrate cultural sensitivity", "exercise cultural sensitivity"],
         "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=800&q=80"),
        ("traditional costumes", "n.phr", "trang phục dân tộc truyền thống", "/trəˈdɪʃənl ˈkɒstjuːmz/",
         "Highland girls weave vibrant brocade textiles to sew their own traditional costumes.",
         "Các thiếu nữ vùng cao dệt thổ cẩm rực rỡ để tự may trang phục truyền thống của mình.",
         ["wear traditional costumes", "sew traditional costumes"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("festive season", "n.phr", "mùa lễ hội tưng bừng đầu xuân", "/ˈfestɪv ˈsiːzn/",
         "Streets are filled with peach blossoms and kumquat trees during the Tet festive season.",
         "Đường phố rực rỡ hoa đào và quất cảnh trong mùa lễ hội Tết tưng bừng.",
         ["celebrate the festive season", "vibrant festive season"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("cultural appropriation", "n.phr", "sự chiếm dụng văn hóa thiếu tôn trọng", "/ˈkʌltʃərəl əˌprəʊpriˈeɪʃn/",
         "Educators explain the subtle boundary between cultural appreciation and appropriation.",
         "Các nhà giáo dục chỉ ra ranh giới giữa việc trân quý văn hóa và chiếm dụng văn hóa.",
         ["accused of cultural appropriation", "avoid cultural appropriation"],
         "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=800&q=80"),
        ("ancestral worship", "n.phr", "tín ngưỡng thờ cúng tổ tiên", "/ænˈsestrəl ˈwɜːʃɪp/",
         "Ancestral worship is central to Vietnamese spirituality and filial piety.",
         "Thờ cúng tổ tiên là nét tâm linh cốt lõi của lòng hiếu kính người Việt.",
         ["practice ancestral worship", "tradition of ancestral worship"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("mutual coexistence", "n.phr", "sự cùng chung sống hòa hợp hòa bình", "/ˈmjuːtʃuəl ˌkəʊɪɡˈzɪstəns/",
         "Different ethnic groups have shared river valleys in mutual coexistence for centuries.",
         "Nhiều dân tộc anh em đã cùng chung sống hòa thuận bên những dòng sông qua bao thế kỷ.",
         ["peaceful mutual coexistence", "principles of coexistence"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("culinary fusion", "n.phr", "ẩm thực giao thoa phong vị Á - Âu", "/ˈkʌlɪnəri ˈfjuːʒn/",
         "Modern Vietnamese chefs experiment with delightful culinary fusion in five-star dining.",
         "Các đầu bếp Việt hiện đại sáng tạo các món ăn giao thoa phong vị tuyệt vời.",
         ["delightful culinary fusion", "culinary fusion trend"],
         "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"),
        ("cultural melting pot", "n.phr", "nồi lẩu văn hóa, nơi quy tụ giao thoa", "/ˈkʌltʃərəl ˈmeltɪŋ pɒt/",
         "New York and London are classic examples of a dynamic cultural melting pot.",
         "New York và London là những ví dụ kinh điển về nơi hội tụ giao thoa văn hóa sôi động.",
         ["vibrant cultural melting pot", "live in a melting pot"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("solidarity", "n", "tinh thần tương trợ đoàn kết một lòng", "/ˌsɒlɪˈdærəti/",
         "The 54 ethnic groups of Vietnam stand in rock-solid national solidarity.",
         "54 dân tộc anh em của đất nước Việt Nam luôn gắn kết trong tình đoàn kết keo sơn.",
         ["great national solidarity", "express solidarity"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("intercultural competence", "n.phr", "năng lực giao tiếp và làm việc liên văn hóa", "/ˌɪntəˈkʌltʃərəl ˈkɒmpɪtəns/",
         "Multinational executives need strong intercultural competence to lead diverse teams.",
         "Lãnh đạo các tập đoàn đa quốc gia cần năng lực liên văn hóa vững vàng để dẫn dắt đội ngũ.",
         ["develop intercultural competence", "master intercultural competence"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("indigenous folklore", "n.phr", "kho tàng truyện kể dân gian bản địa", "/ɪnˈdɪdʒənəs ˈfəʊklɔː(r)/",
         "The Central Highlands epic poems of Dam San are treasures of indigenous folklore.",
         "Sử thi Đăm Săn của đồng bào Tây Nguyên là báu vật của kho tàng truyện kể dân gian.",
         ["oral indigenous folklore", "study indigenous folklore"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("cultural legacy", "n.phr", "di sản văn hóa tinh thần quý giá", "/ˈkʌltʃərəl ˈleɡəsi/",
         "Ancient pagodas leave a serene cultural legacy of mindfulness and compassion.",
         "Những ngôi chùa cổ để lại di sản văn hóa thanh tịnh về chánh niệm và lòng từ bi.",
         ["rich cultural legacy", "cherish cultural legacy"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("shared values", "n.phr", "các giá trị đạo đức chung của con người", "/ʃeəd ˈvæljuːz/",
         "Benevolence, honesty, and hospitality are shared values across all world cultures.",
         "Lòng nhân từ, tính trung thực và lòng hiếu khách là các giá trị đạo đức chung của nhân loại.",
         ["foster shared values", "uphold shared values"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-3-green-living": [
        ("carbon neutrality target", "n.phr", "mục tiêu trung hòa khí thải carbon", "/ˌkɑːbən njuːˈtræləti ˈtɑːɡɪt/",
         "The manufacturing hub set an ambitious carbon neutrality target for the next decade.",
         "Khu sản xuất đặt mục tiêu trung hòa khí carbon đầy tham vọng cho thập kỷ tới.",
         ["achieve carbon neutrality target", "commit to a target"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80"),
        ("energy efficiency standard", "n.phr", "tiêu chuẩn sử dụng năng lượng tiết kiệm", "/ˈenədʒi ɪˈfɪʃnsi ˈstændəd/",
         "New apartment towers must meet rigorous national energy efficiency standards.",
         "Các tòa chung cư mới phải đáp ứng các tiêu chuẩn tiết kiệm năng lượng khắt khe.",
         ["comply with energy efficiency standards", "high standards"],
         "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"),
        ("zero-waste movement", "n.phr", "phong trào không phát thải rác", "/ˌzɪərəʊ ˈweɪst ˈmuːvmənt/",
         "Young urbanites enthusiastically join the zero-waste movement by composting kitchen scraps.",
         "Giới trẻ thành thị nhiệt thành tham gia phong trào không rác thải bằng việc tự ủ rác nhà bếp.",
         ["pioneer the zero-waste movement", "advocate zero-waste"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("green mobility", "n.phr", "phương thức đi lại xanh thân thiện", "/ɡriːn məʊˈbɪləti/",
         "Electric scooters and bicycles are pillars of sustainable green mobility in Hanoi.",
         "Xe máy điện và xe đạp là trụ cột của giao thông xanh bền vững tại Hà Nội.",
         ["adopt green mobility", "infrastructure for green mobility"],
         "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80"),
        ("circular manufacturing", "n.phr", "sản xuất tuần hoàn tái chế khép kín", "/ˈsɜːkjələ(r) ˌmænjuˈfæktʃərɪŋ/",
         "Circular manufacturing reuses scrap metal to fabricate new industrial parts.",
         "Sản xuất tuần hoàn tái sử dụng phế liệu kim loại để đúc các linh kiện công nghiệp mới.",
         ["embrace circular manufacturing", "benefits of circular manufacturing"],
         "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80"),
        ("sustainable sourcing", "n.phr", "thu mua nguyên liệu có nguồn gốc bền vững", "/səˈsteɪnəbl ˈsɔːsɪŋ/",
         "The coffee chain guarantees ethical, sustainable sourcing from certified farmers.",
         "Chuỗi cà phê đảm bảo thu mua bền vững có đạo đức từ các nông hộ đạt chứng nhận.",
         ["practice sustainable sourcing", "commitment to sourcing"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("rainwater harvesting", "n.phr", "thu gom và tích trữ nước mưa sử dụng", "/ˈreɪnwɔːtə(r) ˈhɑːvɪstɪŋ/",
         "Rooftop rainwater harvesting systems irrigate the school's organic botanical gardens.",
         "Hệ thống hứng nước mưa mái nhà được dùng để tưới vườn thực vật hữu cơ của trường.",
         ["install rainwater harvesting", "harvesting tank"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80"),
        ("plant-based diet", "n.phr", "chế độ ăn uống thuần thực vật giàu chất xơ", "/ˌplɑːnt beɪst ˈdaɪət/",
         "Switching to a plant-based diet lowers cholesterol and shrinks your carbon footprint.",
         "Chuyển sang chế độ ăn thực vật giúp giảm mỡ máu và giảm dấu chân carbon của bạn.",
         ["follow a plant-based diet", "healthy plant-based diet"],
         "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80"),
        ("permaculture", "n", "nông nghiệp vĩnh cửu thuận tự nhiên", "/ˈpɜːməkʌltʃə(r)/",
         "The mountain orchard applies permaculture design to cultivate fruits without pesticides.",
         "Vườn đồi áp dụng mô hình nông nghiệp vĩnh cửu để trồng cây ăn trái không thuốc trừ sâu.",
         ["practice permaculture", "principles of permaculture"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("eco-friendly alternatives", "n.phr", "các giải pháp thay thế thân thiện môi trường", "/ˌiːkəʊ ˈfrendli ɔːlˈtɜːnətɪvz/",
         "Cloth totes and bamboo toothbrushes are simple eco-friendly alternatives to plastics.",
         "Túi vải và bàn chải tre là những giải pháp thay thế thân thiện môi trường cho đồ nhựa.",
         ["switch to eco-friendly alternatives", "affordable alternatives"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("energy audit", "n.phr", "kiểm toán mức độ tiêu hao năng lượng", "/ˈenədʒi ˈɔːdɪt/",
         "Conducting a home energy audit pinpoints drafty windows that leak air conditioning.",
         "Thực hiện kiểm toán năng lượng trong nhà giúp phát hiện cửa sổ hở làm thoát nhiệt điều hòa.",
         ["perform an energy audit", "home energy audit report"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80"),
        ("green consumerism", "n.phr", "xu hướng tiêu dùng xanh có trách nhiệm", "/ɡriːn kənˈsjuːmərɪzəm/",
         "Surging green consumerism pressures packaging companies to switch to recycled paper.",
         "Làn sóng tiêu dùng xanh tạo sức ép buộc công ty bao bì phải chuyển sang giấy tái chế.",
         ["rise of green consumerism", "influence of green consumerism"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("natural habitat conservation", "n.phr", "bảo tồn sinh cảnh thiên nhiên hoang dã", "/ˈnætʃrəl ˈhæbɪtæt ˌkɒnsəˈveɪʃn/",
         "Protecting marine coral reefs is vital for natural habitat conservation.",
         "Bảo vệ rạn san hô ngầm là điều thiết yếu cho công tác bảo tồn sinh cảnh tự nhiên.",
         ["support natural habitat conservation", "priority for conservation"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("biodegradable material", "n.phr", "vật liệu tự phân hủy sinh học an toàn", "/ˌbaɪəʊdɪˈɡreɪdəbl məˈtɪəriəl/",
         "Food delivery boxes made from sugarcane bagasse are 100% biodegradable material.",
         "Hộp cơm làm từ bã mía là vật liệu tự phân hủy sinh học an toàn 100%.",
         ["made of biodegradable material", "safe biodegradable material"],
         "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80"),
        ("environmental stewardship", "n.phr", "tinh thần trách nhiệm bảo hộ mẹ thiên nhiên", "/ɪnˌvaɪrənˈmentl ˈstjuːədʃɪp/",
         "Teaching environmental stewardship instills lifelong respect for clean rivers.",
         "Giáo dục tinh thần trách nhiệm bảo vệ môi trường hình thành ý thức giữ sạch dòng sông.",
         ["practice environmental stewardship", "embody environmental stewardship"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-4-urbanisation": [
        ("urban planning authority", "n.phr", "cơ quan quản lý quy hoạch đô thị", "/ˈɜːbən ˈplænɪŋ ɔːˌθɒrəti/",
         "The urban planning authority approved green buffer zones along the river.",
         "Cơ quan quản lý quy hoạch đô thị đã phê duyệt dải cây xanh đệm dọc bờ sông.",
         ["consult the planning authority", "urban authority guidelines"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("satellite township", "n.phr", "khu đô thị vệ tinh hiện đại", "/ˈsætəlaɪt ˈtaʊnʃɪp/",
         "Modern satellite townships offer quiet living spaces with schools and supermarkets.",
         "Các khu đô thị vệ tinh đem lại không gian sống thanh bình có đầy đủ trường học và siêu thị.",
         ["develop satellite townships", "live in a satellite township"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("suburbanization", "n", "quá trình ngoại ô hóa dân cư", "/səˌbɜːbənaɪˈzeɪʃn/",
         "Suburbanization is accelerated by comfortable regional train connections.",
         "Quá trình ngoại ô hóa diễn ra nhanh hơn nhờ các tuyến tàu hỏa ngoại ô tiện lợi.",
         ["trend of suburbanization", "effects of suburbanization"],
         "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"),
        ("high-density housing", "n.phr", "khu nhà ở mật độ dân cư cao", "/ˈhaɪ ˈdensəti ˈhaʊzɪŋ/",
         "High-density housing near metro stations encourages pedestrian commuting.",
         "Nhà ở mật độ cao gần ga tàu điện khuyến khích người dân đi bộ đi làm.",
         ["build high-density housing", "demand for high-density housing"],
         "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"),
        ("urban transit network", "n.phr", "mạng lưới giao thông công cộng đô thị", "/ˈɜːbən ˈtrænzɪt ˈnetwɜːk/",
         "An integrated urban transit network links buses, subways, and shared bicycles.",
         "Mạng lưới giao thông đô thị tích hợp kết nối xe buýt, tàu điện ngầm và xe đạp công cộng.",
         ["expand the transit network", "reliable urban transit network"],
         "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80"),
        ("demographic pressure", "n.phr", "áp lực gia tăng dân số lên hạ tầng", "/ˌdeməˈɡræfɪk ˈpreʃə(r)/",
         "Demographic pressure strains hospitals and primary schools in big cities.",
         "Áp lực dân số gia tăng gây quá tải cho bệnh viện và trường tiểu học ở các đô thị lớn.",
         ["cope with demographic pressure", "alleviate demographic pressure"],
         "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"),
        ("living standards", "n.phr", "chất lượng và tiêu chuẩn sống", "/ˈlɪvɪŋ ˈstændədz/",
         "Higher urban wages improve living standards but also entail higher living costs.",
         "Thu nhập thành thị cao hơn giúp nâng cao mức sống nhưng cũng kéo theo chi phí đắt đỏ.",
         ["elevate living standards", "gap in living standards"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("airborne pollution", "n.phr", "ô nhiễm bụi mịn trong không khí", "/ˈeəbɔːn pəˈluːʃn/",
         "Spraying streets with recycled water helps settle down fine airborne pollution.",
         "Tưới rửa đường phố bằng nước tái chế giúp lắng đọng bụi mịn ô nhiễm trong không khí.",
         ["combat airborne pollution", "levels of airborne pollution"],
         "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80"),
        ("pedestrian walkway", "n.phr", "lối đi bộ an toàn lát gạch", "/pəˈdestriən ˈwɔːkweɪ/",
         "Paved pedestrian walkways shaded by trees encourage residents to walk daily.",
         "Lối đi bộ lát gạch rợp bóng mát khuyến khích cư dân tập thể dục đi bộ mỗi ngày.",
         ["walk along the pedestrian walkway", "clear pedestrian walkways"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("megacity", "n", "siêu đô thị có trên 10 triệu dân", "/ˈmeɡəsɪti/",
         "Tokyo and Jakarta are megacities facing complex transport and waste logistics.",
         "Tokyo và Jakarta là những siêu đô thị đối mặt với bài toán phức tạp về giao thông và rác thải.",
         ["fastest-growing megacity", "challenges of a megacity"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("green lung", "n.phr", "lá phổi xanh điều hòa không khí thành phố", "/ɡriːn lʌŋ/",
         "Botanical gardens and lakes serve as the cooling green lungs of the downtown district.",
         "Vườn bách thảo và các hồ nước đóng vai trò như lá phổi xanh làm mát khu trung tâm.",
         ["preserve urban green lungs", "expand the green lung"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80"),
        ("social housing project", "n.phr", "dự án nhà ở xã hội cho người thu nhập thấp", "/ˈsəʊʃl ˈhaʊzɪŋ ˈprɒdʒekt/",
         "Government subsidies support social housing projects for young working families.",
         "Hỗ trợ của chính phủ thúc đẩy các dự án nhà ở xã hội cho các gia đình trẻ.",
         ["fund a social housing project", "move into social housing"],
         "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"),
        ("traffic congestion", "n.phr", "tình trạng ách tắc giao thông", "/ˈtræfɪk kənˈdʒestʃən/",
         "The opening of the underground metro system successfully relieved traffic congestion.",
         "Việc vận hành tuyến tàu điện ngầm đã giải tỏa thành công tình trạng ùn tắc giao thông.",
         ["ease traffic congestion", "suffer traffic congestion"],
         "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=800&q=80"),
        ("urban renewal", "n.phr", "chương trình chỉnh trang tái thiết đô thị", "/ˌɜːbən rɪˈnjuːəl/",
         "Urban renewal revitalized historic waterfront streets with cafes and street art.",
         "Tái thiết đô thị đã làm sống lại những con phố ven sông với quán cà phê và nghệ thuật đường phố.",
         ["urban renewal initiative", "lead urban renewal"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-5-the-world-of-work": [
        ("labor market dynamics", "n.phr", "sự biến động của thị trường lao động", "/ˈleɪbə ˌmɑːkɪt daɪˈnæmɪks/",
         "Understanding labor market dynamics helps students choose future-proof majors.",
         "Hiểu rõ sự biến động của thị trường lao động giúp sinh viên chọn ngành học đón đầu tương lai.",
         ["study labor market dynamics", "rapid dynamics"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("career progression", "n.phr", "tiến trình phát triển và thăng tiến nghề nghiệp", "/kəˈrɪə prəˌɡreʃn/",
         "Continuous upskilling guarantees steady, satisfying career progression.",
         "Không ngừng nâng cao kỹ năng đảm bảo sự phát triển nghề nghiệp vững chắc và mãn nguyện.",
         ["accelerate career progression", "clear career progression"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("work ethic", "n.phr", "đạo đức và tinh thần trách nhiệm trong công việc", "/ˈwɜːk ˌeθɪk/",
         "Her punctuality, honesty, and diligence reflect an impeccable work ethic.",
         "Sự đúng giờ, trung thực và siêng năng của cô phản ánh tinh thần trách nhiệm nghề nghiệp đáng nể.",
         ["strong work ethic", "admirable work ethic"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("job stability", "n.phr", "sự ổn định lâu dài trong công việc", "/ˈdʒɒb stəˈbɪləti/",
         "Public sector careers offer valuable job stability alongside healthcare benefits.",
         "Công việc trong khu vực công mang lại sự ổn định việc làm cùng chế độ y tế tốt.",
         ["seek job stability", "lack of job stability"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("recruitment drive", "n.phr", "đợt tuyển dụng nhân sự quy mô lớn", "/rɪˈkruːtmənt draɪv/",
         "The tech conglomerate launched a nationwide recruitment drive for software architects.",
         "Tập đoàn công nghệ phát động đợt tuyển dụng toàn quốc cho vị trí kiến trúc sư phần mềm.",
         ["launch a recruitment drive", "annual recruitment drive"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("corporate culture", "n.phr", "văn hóa doanh nghiệp văn minh", "/ˈkɔːpərət ˈkʌltʃə(r)/",
         "A positive corporate culture encourages collaborative brainstorming without fear of failure.",
         "Văn hóa doanh nghiệp tích cực khuyến khích đóng góp ý tưởng mà không ngại thất bại.",
         ["healthy corporate culture", "build corporate culture"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("employee retention", "n.phr", "giữ chân nhân tài gắn bó lâu dài", "/ɪmˈplɔɪiː rɪˈtenʃn/",
         "Flexible hours and fair bonuses are proven strategies for high employee retention.",
         "Giờ làm linh hoạt và thưởng công bằng là chiến lược hiệu quả để giữ chân nhân tài.",
         ["improve employee retention", "employee retention rate"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("hybrid workplace", "n.phr", "môi trường làm việc kết hợp (tại nhà và văn phòng)", "/ˈhaɪbrɪd ˈwɜːkpleɪs/",
         "The hybrid workplace lets employees work two days from home each week.",
         "Mô hình làm việc kết hợp cho phép nhân viên làm việc tại nhà hai ngày mỗi tuần.",
         ["adapt to a hybrid workplace", "hybrid workplace model"],
         "https://images.unsplash.com/photo-1527689368864-3a821dbccc34?auto=format&fit=crop&w=800&q=80"),
        ("performance evaluation", "n.phr", "đánh giá hiệu quả công tác định kỳ", "/pəˈfɔːməns ɪˌvæljuˈeɪʃn/",
         "Constructive feedback during performance evaluation sets clear milestones for the year.",
         "Góp ý chân thành trong đợt đánh giá định kỳ giúp xác định rõ mục tiêu cho năm mới.",
         ["annual performance evaluation", "conduct performance evaluation"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("workplace diversity", "n.phr", "sự đa dạng văn hóa và giới tính nơi làm việc", "/ˈwɜːkpleɪs daɪˈvɜːsəti/",
         "Workplace diversity sparks innovative ideas from people of different backgrounds.",
         "Sự đa dạng tại nơi làm việc kích hoạt những ý tưởng sáng tạo từ những góc nhìn khác nhau.",
         ["champion workplace diversity", "value workplace diversity"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("internship program", "n.phr", "chương trình thực tập sinh cọ xát thực tế", "/ˈɪntɜːnʃɪp ˈprəʊɡræm/",
         "The summer internship program offers university seniors mentorship from department heads.",
         "Chương trình thực tập mùa hè mang lại cho sinh viên sự hướng dẫn từ các trưởng phòng.",
         ["enroll in an internship program", "prestigious internship program"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("professional network", "n.phr", "mạng lưới quan hệ đồng nghiệp nghề nghiệp", "/prəˈfeʃənl ˈnetwɜːk/",
         "Attending international seminars broadens your professional network.",
         "Tham dự các buổi hội thảo quốc tế giúp mở rộng mạng lưới quan hệ đồng nghiệp.",
         ["expand professional network", "active professional network"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("adaptability", "n", "khả năng thích ứng linh hoạt trước biến động", "/əˌdæptəˈbɪləti/",
         "High adaptability helps software engineers master new programming languages swiftly.",
         "Khả năng thích ứng cao giúp kỹ sư phần mềm làm chủ các ngôn ngữ lập trình mới nhanh chóng.",
         ["demonstrate adaptability", "crucial adaptability"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("career fulfillment", "n.phr", "cảm giác mãn nguyện với sự nghiệp", "/kəˈrɪə fʊlˈfɪlmənt/",
         "Doing work that helps the community brings profound career fulfillment.",
         "Làm công việc giúp ích cho cộng đồng đem lại sự mãn nguyện sâu sắc trong sự nghiệp.",
         ["achieve career fulfillment", "seek career fulfillment"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-6-artificial-intelligence": [
        ("deep learning model", "n.phr", "mô hình học sâu nhiều lớp nơ-ron", "/ˌdiːp ˈlɜːnɪŋ ˈmɒdl/",
         "The deep learning model identifies early cancerous cells with ninety-nine percent accuracy.",
         "Mô hình học sâu phát hiện tế bào ung thư sớm với độ chính xác chín mươi chín phần trăm.",
         ["train a deep learning model", "deploy deep learning models"],
         "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80"),
        ("autonomous navigation", "n.phr", "điều hướng tự hành không người lái", "/ɔːˌtɒnəməs ˌnævɪˈɡeɪʃn/",
         "Autonomous navigation algorithms steer Mars exploration rovers around rocky craters.",
         "Thuật toán điều hướng tự hành dẫn dắt tàu thám hiểm Sao Hỏa tránh miệng núi lửa đá.",
         ["system of autonomous navigation", "autonomous navigation capability"],
         "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80"),
        ("data processing", "n.phr", "xử lý dữ liệu tốc độ cao", "/ˈdeɪtə ˈprəʊsesɪŋ/",
         "Cloud data processing allows weather models to calculate forecast maps in minutes.",
         "Xử lý dữ liệu đám mây cho phép các mô hình thời tiết tính toán bản đồ dự báo trong vài phút.",
         ["high-speed data processing", "real-time data processing"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("speech synthesis", "n.phr", "tổng hợp giọng nói nhân tạo", "/spiːtʃ ˈsɪnθəsɪs/",
         "Advances in speech synthesis produce lifelike, expressive virtual audio narration.",
         "Tiến bộ trong tổng hợp giọng nói tạo ra giọng đọc truyền cảm tự nhiên như người thật.",
         ["natural speech synthesis", "technology of speech synthesis"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("intelligent system", "n.phr", "hệ thống thông minh tự thích ứng", "/ɪnˈtelɪdʒənt ˈsɪstəm/",
         "Intelligent systems in hospitals alert nurses whenever patients show signs of fever.",
         "Hệ thống thông minh trong bệnh viện cảnh báo y tá mỗi khi bệnh nhân có dấu hiệu sốt.",
         ["design intelligent systems", "complex intelligent system"],
         "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80"),
        ("predictive algorithm", "n.phr", "thuật toán dự đoán hành vi", "/prɪˈdɪktɪv ˈælɡərɪðəm/",
         "Predictive algorithms recommend study flashcards based on your past review errors.",
         "Thuật toán dự đoán gợi ý các thẻ từ vựng dựa trên những lỗi sai trước đây của bạn.",
         ["accuracy of predictive algorithms", "use predictive algorithms"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("human-machine collaboration", "n.phr", "sự phối hợp làm việc giữa người và máy móc", "/ˈhjuːmən məˈʃiːn kəˌlæbəˈreɪʃn/",
         "Surgeons practice human-machine collaboration by commanding micro-robotic arms.",
         "Các bác sĩ phẫu thuật phối hợp giữa người và máy bằng việc điều khiển cánh tay robot vi phẫu.",
         ["foster human-machine collaboration", "future of collaboration"],
         "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80"),
        ("computer vision algorithm", "n.phr", "thuật toán thị giác máy tính nhận diện ảnh", "/kəmˈpjuːtə ˈvɪʒn ˈælɡərɪðəm/",
         "Computer vision algorithms inspect manufactured silicon chips for microscopic defects.",
         "Thuật toán thị giác máy tính kiểm tra chip bán dẫn để phát hiện các lỗi siêu nhỏ.",
         ["accuracy of computer vision", "train computer vision algorithms"],
         "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80"),
        ("virtual assistant", "n.phr", "trợ lý ảo điều khiển bằng giọng nói", "/ˌvɜːtʃuəl əˈsɪstənt/",
         "Voice-activated virtual assistants can set alarms, play music, and answer questions.",
         "Trợ lý ảo kích hoạt bằng giọng nói có thể đặt báo thức, phát nhạc và giải đáp thắc mắc.",
         ["command a virtual assistant", "smart virtual assistant"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("ethical guideline", "n.phr", "hướng dẫn chuẩn mực đạo đức công nghệ", "/ˌeθɪkl ˈɡaɪdlaɪn/",
         "International organizations drafted ethical guidelines for artificial intelligence.",
         "Các tổ chức quốc tế đã soạn thảo các hướng dẫn chuẩn mực đạo đức cho trí tuệ nhân tạo.",
         ["adhere to ethical guidelines", "propose ethical guidelines"],
         "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80"),
        ("computational power", "n.phr", "năng lực tính toán xử lý dữ liệu", "/ˌkɒmpjuˈteɪʃənl ˈpaʊə(r)/",
         "Quantum computers promise to deliver astronomical leaps in computational power.",
         "Máy tính lượng tử hứa hẹn mang lại bước nhảy vọt thần kỳ về năng lực xử lý tính toán.",
         ["exponential computational power", "vast computational power"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("data security", "n.phr", "bảo mật và an toàn dữ liệu số", "/ˈdeɪtə sɪˈkjʊərəti/",
         "Financial applications implement military-grade encryption to protect user data security.",
         "Các ứng dụng tài chính áp dụng mã hóa cấp quân sự để bảo đảm an toàn dữ liệu người dùng.",
         ["ensure data security", "breach of data security"],
         "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80"),
        ("automated reasoning", "n.phr", "suy luận tự động bằng logic máy", "/ˌɔːtəmeɪtɪd ˈriːznɪŋ/",
         "Automated reasoning systems verify mathematical theorems that are too long for humans.",
         "Hệ thống suy luận tự động kiểm chứng các định lý toán học quá dài đối với con người.",
         ["field of automated reasoning", "apply automated reasoning"],
         "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80"),
        ("digital automation", "n.phr", "tự động hóa quy trình kỹ thuật số", "/ˈdɪdʒɪtl ˌɔːtəˈmeɪʃn/",
         "Digital automation frees clerks from repetitive data entry, letting them focus on clients.",
         "Tự động hóa số giải phóng nhân viên khỏi việc nhập liệu lặp đi lặp lại để chăm sóc khách hàng.",
         ["implement digital automation", "benefits of digital automation"],
         "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-7-the-world-of-mass-media": [
        ("investigative journalism", "n.phr", "báo chí điều tra sự thật", "/ɪnˈvestɪɡətɪv ˈdʒɜːnəlɪzəm/",
         "Investigative journalism uncovers environmental pollution concealed by rogue factories.",
         "Báo chí điều tra vạch trần hành vi xả thải môi trường bị che giấu bởi các nhà máy.",
         ["power of investigative journalism", "award for investigative journalism"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("media regulation", "n.phr", "quy định quản lý báo chí và truyền thông", "/ˈmiːdiə ˌreɡjuˈleɪʃn/",
         "Media regulations prohibit misleading medical advertisements targeting vulnerable elders.",
         "Quy định truyền thông nghiêm cấm quảng cáo thuốc đánh lừa người cao tuổi nhẹ dạ.",
         ["enforce media regulations", "stricter media regulation"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("online disinformation", "n.phr", "thông tin sai lệch có chủ đích trên mạng", "/ˌɒnlaɪn ˌdɪsɪnfəˈmeɪʃn/",
         "Educators teach students how to identify and debunk online disinformation campaigns.",
         "Thầy cô hướng dẫn học sinh cách nhận diện và bác bỏ các chiến dịch tin giả mạo có chủ đích.",
         ["combat online disinformation", "spread of disinformation"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("digital broadcaster", "n.phr", "đài truyền hình số trực tuyến", "/ˈdɪdʒɪtl ˈbrɔːdkɑːstə(r)/",
         "The digital broadcaster streams documentaries simultaneously to mobile apps and smart TVs.",
         "Đài truyền hình số phát trực tiếp các bộ phim tài liệu đồng thời lên ứng dụng và tivi thông minh.",
         ["national digital broadcaster", "licensed digital broadcaster"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("target audience", "n.phr", "đối tượng khán thính giả mục tiêu", "/ˈtɑːɡɪt ˈɔːdiəns/",
         "The educational podcast crafted content specifically tailored to its teenage target audience.",
         "Chương trình podcast thiết kế nội dung phù hợp riêng với đối tượng thính giả tuổi teen.",
         ["reach the target audience", "define the target audience"],
         "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80"),
        ("prime-time broadcast", "n.phr", "khung giờ vàng phát sóng truyền hình", "/ˌpraɪm taɪm ˈbrɔːdkɑːst/",
         "The evening news is aired during the 7 PM prime-time broadcast across national channels.",
         "Bản tin thời sự được phát sóng vào khung giờ vàng 7 giờ tối trên các kênh truyền hình quốc gia.",
         ["watch the prime-time broadcast", "prime-time viewership"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("media accountability", "n.phr", "trách nhiệm giải trình của cơ quan truyền thông", "/ˈmiːdiə əˌkaʊntəˈbɪləti/",
         "Publishing prompt corrections when errors happen reinforces media accountability.",
         "Đăng lời đính chính kịp thời khi có sai sót giúp củng cố trách nhiệm của cơ quan báo chí.",
         ["demand media accountability", "principles of accountability"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("information dissemination", "n.phr", "sự phổ biến và lan tỏa thông tin", "/ˌɪnfəˈmeɪʃn dɪˌsemɪˈneɪʃn/",
         "Social channels enable instantaneous information dissemination during national emergencies.",
         "Các kênh mạng xã hội cho phép lan tỏa thông tin tức thời trong các tình huống khẩn cấp.",
         ["rapid information dissemination", "channels of dissemination"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("public service announcement", "n.phr", "thông điệp tuyên truyền vì lợi ích công", "/ˌpʌblɪk ˈsɜːvɪs əˌnaʊnsmənt/",
         "The health ministry broadcasted public service announcements about helmet safety.",
         "Bộ Y tế đã phát sóng các thông điệp truyền thông công ích về an toàn đội mũ bảo hiểm.",
         ["air a public service announcement", "televised announcement"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("newsfeed", "n", "bảng tin cập nhật trên ứng dụng mạng xã hội", "/ˈnjuːzfiːd/",
         "Algorithms curate your personal newsfeed to display topics matching your clicks.",
         "Thuật toán sắp xếp bảng tin cá nhân để hiển thị những chủ đề bạn thường xem.",
         ["scroll through the newsfeed", "personalized newsfeed"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("verified account", "n.phr", "tài khoản mạng xã hội có tích xanh xác thực", "/ˈverɪfaɪd əˈkaʊnt/",
         "Check for verified accounts with official badges to confirm government statements.",
         "Hãy xem các tài khoản có tích xanh xác thực để đọc thông tin chính thức của cơ quan nhà nước.",
         ["follow verified accounts", "official verified account"],
         "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80"),
        ("live-stream", "v / n", "phát sóng trực tiếp sự kiện qua mạng", "/ˈlaɪvstriːm/",
         "The university will live-stream the graduation ceremony for relatives overseas.",
         "Trường đại học sẽ phát sóng trực tiếp lễ tốt nghiệp cho người thân ở nước ngoài cùng xem.",
         ["watch the live-stream", "host a live-stream"],
         "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80"),
        ("editorial integrity", "n.phr", "tính liêm chính và khách quan của ban biên tập", "/ˌedɪˈtɔːriəl ɪnˈteɡrəti/",
         "Reputable magazines safeguard editorial integrity by rejecting commercial sponsorships.",
         "Các tạp chí uy tín giữ gìn tính liêm chính biên tập bằng cách từ chối tài trợ thương mại.",
         ["uphold editorial integrity", "compromise integrity"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("media landscape", "n.phr", "diện mạo và bức tranh toàn cảnh truyền thông", "/ˈmiːdiə ˈlændskeɪp/",
         "Smartphones have dramatically transformed the modern media landscape in Vietnam.",
         "Điện thoại thông minh đã thay đổi căn bản diện mạo truyền thông hiện đại tại Việt Nam.",
         ["dynamic media landscape", "changing media landscape"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-8-wildlife-conservation": [
        ("poaching syndicate", "n.phr", "đường dây buôn bán và săn trộm thú xuyên quốc gia", "/ˈpəʊtʃɪŋ ˈsɪndɪkət/",
         "International police dismantled an elusive rhino horn poaching syndicate.",
         "Cảnh sát quốc tế đã triệt phá một đường dây buôn lậu sừng tê giác xuyên quốc gia tinh vi.",
         ["bust a poaching syndicate", "target poaching syndicates"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80"),
        ("wildlife rehabilitation", "n.phr", "cứu hộ và phục hồi chức năng cho thú hoang", "/ˈwaɪldlaɪf ˌriːəˌbɪlɪˈteɪʃn/",
         "The wildlife rehabilitation center nursed thirty wounded pangolins back to full health.",
         "Trung tâm cứu hộ động vật hoang dã đã chăm sóc ba mươi cá thể tê tê bị thương khỏe mạnh trở lại.",
         ["support wildlife rehabilitation", "center for rehabilitation"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80"),
        ("nature sanctuary", "n.phr", "khu bảo tồn thiên nhiên an toàn cho muông thú", "/ˈneɪtʃə ˈsæŋktʃuəri/",
         "Rescued elephants roam freely inside the protected nature sanctuary in Dak Lak.",
         "Những chú voi được giải cứu đi lại tự do trong khu bảo tồn thiên nhiên tại Đắk Lắk.",
         ["elephant nature sanctuary", "visit a nature sanctuary"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80"),
        ("wildlife corridor", "n.phr", "hành lang rừng an toàn cho động vật di chuyển", "/ˈwaɪldlaɪf ˈkɒrɪdɔː(r)/",
         "Building highway overpasses planted with trees creates safe wildlife corridors.",
         "Xây cầu vượt có trồng cây xanh trên cao tốc tạo hành lang an toàn cho thú rừng qua đường.",
         ["create wildlife corridors", "safe wildlife corridor"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("anti-trafficking law", "n.phr", "luật phòng chống buôn lậu động vật hoang dã", "/ˌænti ˈtræfɪkɪŋ lɔː/",
         "Strict anti-trafficking laws impose up to fifteen years of imprisonment for ivory traders.",
         "Luật phòng chống buôn lậu thú quý hiếm áp mức án tới 15 năm tù cho đối tượng buôn ngà voi.",
         ["enforce anti-trafficking laws", "stricter laws"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80"),
        ("biodiversity monitoring", "n.phr", "theo dõi và giám sát đa dạng sinh học rừng", "/ˌbaɪəʊdaɪˈvɜːsəti ˈmɒnɪtərɪŋ/",
         "Motion-triggered camera traps assist rangers in continuous biodiversity monitoring.",
         "Bẫy ảnh cảm biến chuyển động hỗ trợ kiểm lâm giám sát liên tục các loài thú quý trong rừng.",
         ["conduct biodiversity monitoring", "scientific monitoring"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("native fauna", "n.phr", "quần thể động vật bản địa quý báu", "/ˈneɪtɪv ˈfɔːnə/",
         "Invasive bullfrogs compete with native fauna for insect prey and clean water pools.",
         "Ếch ngoại lai xâm hại cạnh tranh con mồi và nguồn nước sạch với các loài động vật bản địa.",
         ["protect native fauna", "rich native fauna"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("illegal snare", "n.phr", "bẫy dây săn bắt thú trái phép độc ác", "/ɪˈliːɡl sneə(r)/",
         "Forest rangers dismantled forty illegal snares during yesterday's patrol.",
         "Các kiểm lâm viên đã tháo gỡ bốn mươi chiếc bẫy dây trái phép trong chuyến tuần tra hôm qua.",
         ["remove illegal snares", "deadly snares"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80"),
        ("ecological balance", "n.phr", "sự cân bằng tự nhiên của hệ sinh thái", "/ˌiːkəˈlɒdʒɪkl ˈbæləns/",
         "Every living creature from frogs to eagles plays a role in maintaining ecological balance.",
         "Mọi sinh vật từ ếch nhái đến đại bàng đều đóng vai trò gìn giữ sự cân bằng sinh thái.",
         ["restore ecological balance", "vital for ecological balance"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("captive breeding center", "n.phr", "trung tâm nhân giống bảo tồn động vật quý", "/ˌkæptɪv ˈbriːdɪŋ ˈsentə(r)/",
         "The turtle captive breeding center successfully hatched sixty endangered sea turtles.",
         "Trung tâm nhân giống rùa đã ấp nở thành công sáu mươi cá thể rùa biển quý hiếm.",
         ["support the breeding center", "turtle captive breeding center"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("community ranger", "n.phr", "kiểm lâm viên cộng đồng người bản địa", "/kəˈmjuːnəti ˈreɪndʒə(r)/",
         "Community rangers from local ethnic villages patrol boundary lines with deep local pride.",
         "Các kiểm lâm viên cộng đồng từ các bản làng tuần tra biên giới rừng với niềm tự hào lớn.",
         ["train community rangers", "role of community rangers"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("extinction prevention", "n.phr", "ngăn ngừa nguy cơ tuyệt chủng cho các loài", "/ɪkˈstɪŋkʃn prɪˈvenʃn/",
         "Emergency field reserves are established for the urgent extinction prevention of saolas.",
         "Các khu bảo tồn thực địa khẩn cấp được thành lập để ngăn chặn nguy cơ tuyệt chủng loài sao la.",
         ["actions for extinction prevention", "focus on prevention"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80"),
        ("habitat restoration", "n.phr", "phục hồi sinh cảnh tự nhiên bị tàn phá", "/ˈhæbɪtæt ˌrestəˈreɪʃn/",
         "Replanting native broad-leaf trees is the first stage of mountain habitat restoration.",
         "Trồng lại cây lá rộng bản địa là giai đoạn đầu tiên của quá trình phục hồi sinh cảnh đồi núi.",
         ["conduct habitat restoration", "successful restoration"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("conservation hero", "n.phr", "người anh hùng trong công tác bảo tồn thiên nhiên", "/ˌkɒnsəˈveɪʃn ˈhɪərəʊ/",
         "Nguyen Van Thai received the prestigious Goldman Environmental Prize as a conservation hero.",
         "Anh Nguyễn Văn Thái được trao giải thưởng môi trường Goldman danh giá như một anh hùng bảo tồn.",
         ["celebrate conservation heroes", "true conservation hero"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-9-career-paths": [
        ("career milestone", "n.phr", "cột mốc quan trọng trong sự nghiệp", "/kəˈrɪə ˈmaɪlstəʊn/",
         "Publishing her first research paper in Nature was a proud career milestone.",
         "Được đăng bài báo nghiên cứu đầu tiên trên tạp chí Nature là cột mốc sự nghiệp đáng tự hào.",
         ["celebrate a career milestone", "crucial milestone"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("professional qualification", "n.phr", "bằng cấp chuyên môn được chứng nhận", "/prəˈfeʃənl ˌkwɒlɪfɪˈkeɪʃn/",
         "Certified Public Accountant (CPA) is an internationally recognized professional qualification.",
         "Chứng chỉ kiểm toán viên công chứng (CPA) là văn bằng chuyên môn được công nhận quốc tế.",
         ["earn a professional qualification", "mandatory qualification"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("vocational orientation", "n.phr", "định hướng lựa chọn trường nghề phù hợp", "/vəʊˈkeɪʃənl ˌɔːriənˈteɪʃn/",
         "Vocational orientation tours introduce high schoolers to modern robotic manufacturing labs.",
         "Các chuyến tham quan hướng nghiệp giúp học sinh tiếp cận xưởng sản xuất tự động hóa hiện đại.",
         ["effective vocational orientation", "career orientation day"],
         "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80"),
        ("industry credential", "n.phr", "chứng chỉ chuyên môn chuẩn ngành công nghiệp", "/ˈɪndəstri krɪˈdenʃl/",
         "Tech certifications from Cisco and AWS serve as valuable industry credentials on your CV.",
         "Chứng chỉ công nghệ từ Cisco và AWS là những chứng chỉ ngành nghề đắt giá trên hồ sơ xin việc.",
         ["earn an industry credential", "recognized credentials"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("executive leadership", "n.phr", "năng lực lãnh đạo điều hành cấp cao", "/ɪɡˈzekjətɪv ˈliːdəʃɪp/",
         "Executive leadership seminars teach empathetic communication and conflict resolution.",
         "Các khóa đào tạo lãnh đạo điều hành dạy kỹ năng giao tiếp thấu cảm và giải quyết xung đột.",
         ["display executive leadership", "executive leadership skills"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("entrepreneurial spirit", "n.phr", "tinh thần khởi nghiệp sáng tạo dấn thân", "/ˌɒntrəprəˈnɜːriəl ˈspɪrɪt/",
         "Youth incubation hubs foster entrepreneurial spirit through pitch competitions and seed grants.",
         "Vườn ươm thanh niên nuôi dưỡng tinh thần khởi nghiệp qua các cuộc thi thuyết trình gọi vốn.",
         ["ignite entrepreneurial spirit", "foster entrepreneurial spirit"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("resume optimization", "n.phr", "tối ưu hóa hồ sơ xin việc nổi bật", "/ˈrezjuːmeɪ ˌɒptɪmaɪˈzeɪʃn/",
         "Resume optimization tools help candidates highlight quantitative metrics and leadership achievements.",
         "Công cụ tối ưu hóa hồ sơ giúp ứng viên nêu bật các số liệu định lượng và thành tích nổi trội.",
         ["tips for resume optimization", "effective optimization"],
         "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80"),
        ("mock interview", "n.phr", "buổi phỏng vấn thử nghiệm rèn tâm lý", "/ˌmɒk ˈɪntəvjuː/",
         "Practicing mock interviews with college career counselors boosts your poise and answers.",
         "Phỏng vấn thử cùng chuyên viên hướng nghiệp trường giúp bạn vững tâm lý và trả lời lưu loát.",
         ["conduct mock interviews", "benefit of mock interviews"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("career agility", "n.phr", "sự nhanh nhạy thích ứng với biến chuyển nghề nghiệp", "/kəˈrɪər əˈdʒɪləti/",
         "In an AI-driven economy, career agility allows professionals to pivot across domains.",
         "Trong nền kinh tế AI, sự nhanh nhạy nghề nghiệp giúp người lao động linh hoạt chuyển hướng.",
         ["develop career agility", "importance of career agility"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("job shadowing experience", "n.phr", "trải nghiệm đi theo quan sát công việc thực tế", "/ˈdʒɒb ʃædəʊɪŋ ɪkˈspɪəriəns/",
         "The hospital job shadowing experience solidified her decision to study neurosurgery.",
         "Trải nghiệm quan sát tại bệnh viện đã củng cố quyết tâm thi vào ngành phẫu thuật thần kinh của cô.",
         ["valuable shadowing experience", "participate in shadowing"],
         "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80"),
        ("workplace professionalism", "n.phr", "tác phong chuyên nghiệp chuẩn mực công sở", "/ˈwɜːkpleɪs prəˈfeʃənəlɪzəm/",
         "Punctuality and transparent communication are pillars of workplace professionalism.",
         "Đúng giờ và giao tiếp minh bạch là hai trụ cột của tác phong chuyên nghiệp nơi công sở.",
         ["uphold workplace professionalism", "standards of professionalism"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("lifelong employability", "n.phr", "khả năng duy trì cơ hội việc làm suốt đời", "/ˈlaɪflɒŋ ɪmˌplɔɪəˈbɪləti/",
         "Continuous upskilling guarantees lifelong employability regardless of technological disruption.",
         "Không ngừng học hỏi đảm bảo cơ hội việc làm suốt đời bất kể những biến động công nghệ.",
         ["secure lifelong employability", "strive for employability"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("career satisfaction", "n.phr", "sự hài lòng và hạnh phúc với công việc", "/kəˈrɪə ˌsætɪsˈfækʃn/",
         "Aligning your personal passions with your daily job brings genuine career satisfaction.",
         "Kết hợp đam mê cá nhân với công việc hàng ngày đem lại sự hài lòng nghề nghiệp đích thực.",
         ["high career satisfaction", "derive career satisfaction"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-10-lifelong-learning": [
        ("self-regulated learning", "n.phr", "việc tự điều tiết và làm chủ việc học", "/ˌself ˈreɡjuleɪtɪd ˈlɜːnɪŋ/",
         "Self-regulated learning enables adults to pace their online degree coursework effectively.",
         "Tự điều tiết học tập giúp người trưởng thành tự phân bổ bài vở đại học trực tuyến hiệu quả.",
         ["practice self-regulated learning", "strategies of self-regulated learning"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("intellectual growth", "n.phr", "sự phát triển và mở rộng trí tuệ tri thức", "/ˌɪntəˈlektʃuəl ɡrəʊθ/",
         "Reading deep philosophy and science books stimulates continuous intellectual growth.",
         "Đọc những cuốn sách triết học và khoa học sâu sắc kích thích sự phát triển trí tuệ không ngừng.",
         ["nurture intellectual growth", "catalyst for intellectual growth"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("online credentials", "n.pl", "chứng chỉ học tập trực tuyến xác thực", "/ˈɒnlaɪn krɪˈdenʃlz/",
         "Earning verified online credentials from top universities boosts career mobility.",
         "Sở hữu chứng chỉ trực tuyến từ các trường đại học hàng đầu giúp gia tăng cơ hội nghề nghiệp.",
         ["stackable online credentials", "verified credentials"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("mindset shift", "n.phr", "sự chuyển đổi tư duy tích cực", "/ˈmaɪndset ʃɪft/",
         "Embracing lifelong study requires a mindset shift from passive listener to active seeker.",
         "Đón nhận học tập suốt đời đòi hỏi sự chuyển đổi từ người nghe thụ động sang người chủ động tìm tòi.",
         ["undergo a mindset shift", "trigger a mindset shift"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("curiosity-driven", "adj", "được thôi thúc bởi lòng hiếu tri, say mê", "/ˌkjʊəriˈɒsəti ˈdrɪvn/",
         "Curiosity-driven study leads to surprising breakthroughs in unexpected domains.",
         "Học tập thôi thúc bởi lòng hiếu tri mở ra những bước đột phá kỳ diệu ở nhiều lĩnh vực.",
         ["curiosity-driven learning", "curiosity-driven research"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("cognitive flexibility", "n.phr", "sự linh hoạt, nhanh nhạy trong tư duy nhận thức", "/ˈkɒɡnətɪv ˌfleksəˈbɪləti/",
         "Solving puzzles and learning foreign languages enhances cognitive flexibility in elderly adults.",
         "Giải đố và học ngoại ngữ tăng cường sự linh hoạt nhận thức cho người cao tuổi.",
         ["boost cognitive flexibility", "maintain cognitive flexibility"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("reflective learning", "n.phr", "học tập qua phản tư và đúc kết kinh nghiệm", "/rɪˈflektɪv ˈlɜːnɪŋ/",
         "Keeping a daily learning journal is a proven method of reflective learning.",
         "Viết nhật ký học tập mỗi ngày là phương pháp học qua phản tư đã được chứng minh hiệu quả.",
         ["practice reflective learning", "benefits of reflective learning"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("digital learning tools", "n.phr", "công cụ hỗ trợ học tập kỹ thuật số", "/ˈdɪdʒɪtl ˈlɜːnɪŋ tuːlz/",
         "Digital learning tools like spaced repetition apps accelerate vocabulary retention threefold.",
         "Các công cụ học tập số như ứng dụng lặp lại ngắt quãng giúp nhớ từ vựng nhanh gấp ba lần.",
         ["use digital learning tools", "master digital learning tools"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("critical analysis", "n.phr", "phân tích phản biện có chiều sâu", "/ˌkrɪtɪkl əˈnæləsɪs/",
         "Academic essays require rigorous critical analysis rather than mere recitation of facts.",
         "Bài luận học thuật đòi hỏi phân tích phản biện chặt chẽ thay vì chỉ đơn thuần kể lại sự việc.",
         ["conduct critical analysis", "sharpen critical analysis"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("knowledge sharing", "n.phr", "chia sẻ và lan tỏa tri thức cùng nhau", "/ˈnɒlɪdʒ ˈʃeərɪŋ/",
         "Open online forums foster voluntary knowledge sharing among worldwide enthusiasts.",
         "Diễn đàn trực tuyến cởi mở thúc đẩy việc tự nguyện chia sẻ tri thức giữa những người say mê.",
         ["culture of knowledge sharing", "promote knowledge sharing"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("growth mindset", "n.phr", "tư duy phát triển đón nhận thử thách", "/ɡrəʊθ ˈmaɪndset/",
         "Students with a growth mindset view complex physics problems as fun challenges to conquer.",
         "Học sinh có tư duy phát triển xem bài toán vật lý khó như thử thách thú vị để chinh phục.",
         ["cultivate a growth mindset", "power of growth mindset"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("self-education", "n", "sự tự học kiên trì của bản thân", "/ˌself ˌedʒuˈkeɪʃn/",
         "Abraham Lincoln achieved historical greatness largely through diligent self-education by candlelight.",
         "Abraham Lincoln làm nên sự nghiệp vĩ đại phần lớn nhờ tự học miệt mài bên ánh đèn dầu.",
         ["pursue self-education", "value of self-education"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("intellectual stamina", "n.phr", "sức bền và sự dẻo dai của trí óc", "/ˌɪntəˈlektʃuəl ˈstæmɪnə/",
         "Solving lengthy mathematical proofs builds deep intellectual stamina over months.",
         "Giải các bài toán chứng minh dài giúp bồi đắp sức bền trí tuệ sau nhiều tháng rèn giũa.",
         ["build intellectual stamina", "display intellectual stamina"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("adaptive learner", "n.phr", "người học có năng lực thích ứng linh hoạt", "/əˈdæptɪv ˈlɜːnə(r)/",
         "The digital era rewards adaptive learners who readily acquire emerging skills.",
         "Kỷ nguyên số tưởng thưởng cho những người học linh hoạt sẵn sàng tiếp thu kỹ năng mới nổi.",
         ["become an adaptive learner", "traits of adaptive learners"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80")
    ]
}

g12_file = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "curriculum", "expanded-vocab-g12.ts")
with open(g12_file, "r", encoding="utf-8") as f:
    g12_text = f.read()

for unit_slug, extra_items in G12_EXTRA.items():
    search_str = f'"{unit_slug}": ['
    idx = g12_text.find(search_str)
    if idx != -1:
        close_idx = g12_text.find('  ],', idx)
        if close_idx != -1:
            new_lines = []
            for item in extra_items:
                word, pos, vi, ipa, en_ex, vi_ex, colocs, img = item
                clean_id = f"v12-extra-{word.lower().replace(' ', '-').replace('/', '-')}"
                audio = f"https://dict.youdao.com/dictvoice?audio={word.replace(' ', '+')}&type=2"
                new_lines.append('    ,')
                new_lines.append('    {')
                new_lines.append(f'      id: {json.dumps(clean_id)},')
                new_lines.append(f'      word: {json.dumps(word)},')
                new_lines.append(f'      partOfSpeech: {json.dumps(pos)},')
                new_lines.append(f'      meaningVi: {json.dumps(vi)},')
                new_lines.append(f'      ipa: {json.dumps(ipa)},')
                new_lines.append(f'      audioUrl: {json.dumps(audio)},')
                new_lines.append(f'      imageUrl: {json.dumps(img)},')
                new_lines.append(f'      exampleEn: {json.dumps(en_ex)},')
                new_lines.append(f'      exampleVi: {json.dumps(vi_ex)},')
                new_lines.append(f'      collocations: {json.dumps(colocs)}')
                new_lines.append('    }')
            insert_content = "\n".join(new_lines)
            g12_text = g12_text[:close_idx] + insert_content + "\n" + g12_text[close_idx:]

with open(g12_file, "w", encoding="utf-8") as f:
    f.write(g12_text)

print("Successfully injected booster words into Grade 12!")
