# -*- coding: utf-8 -*-
"""
Boost Grade 10 Units 6 to 10 to reach 80+ words each!
"""
import json
import os

G10_PART2 = {
    "unit-6-gender-equality": [
        ("glass ceiling", "n.phr", "rào cản vô hình kìm hãm sự thăng tiến của phụ nữ", "/ˌɡlɑːs ˈsiːlɪŋ/",
         "Many female corporate executives still strive to shatter the invisible glass ceiling.",
         "Nhiều nữ giám đốc điều hành vẫn nỗ lực phá vỡ rào cản vô hình kìm hãm sự thăng tiến trong sự nghiệp.",
         ["shatter the glass ceiling", "confront the glass ceiling"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("gender disparity", "n.phr", "sự chênh lệch bất bình đẳng giới tính", "/ˈdʒendə dɪˈspærəti/",
         "Policymakers enact laws to eliminate the gender disparity in technical salaries.",
         "Các nhà hoạch định chính sách ban hành luật để xóa bỏ sự chênh lệch giới tính trong mức lương ngành kỹ thuật.",
         ["narrow gender disparity", "gender disparity in education"],
         "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=800&q=80"),
        ("maternity leave", "n.phr", "kỳ nghỉ thai sản có lương", "/məˈtɜːnəti liːv/",
         "Progressive labor laws guarantee six months of paid maternity leave for new mothers.",
         "Bộ luật lao động tiến bộ đảm bảo sáu tháng nghỉ thai sản hưởng lương cho các bà mẹ mới sinh.",
         ["take maternity leave", "paid maternity leave"],
         "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&w=800&q=80"),
        ("paternity leave", "n.phr", "kỳ nghỉ chăm sóc con dành cho người cha", "/pəˈtɜːnəti liːv/",
         "Offering paternity leave encourages fathers to share infant caretaking duties equally.",
         "Chế độ nghỉ thai sản dành cho cha khuyến khích những người đàn ông cùng chia sẻ trách nhiệm chăm sóc trẻ sơ sinh một cách bình đẳng.",
         ["grant paternity leave", "encourage paternity leave"],
         "https://images.unsplash.com/photo-1506863530036-1efeddceb993?auto=format&fit=crop&w=800&q=80"),
        ("equal pay", "n.phr", "nguyên tắc trả lương ngang nhau cho cùng công việc", "/ˌiːkwəl ˈpeɪ/",
         "The campaign advocates for equal pay for equal work regardless of biological gender.",
         "Chiến dịch vận động cho nguyên tắc trả lương bình đẳng cho công việc ngang nhau không phân biệt giới tính sinh học.",
         ["demand equal pay", "equal pay legislation"],
         "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80"),
        ("empowerment", "n", "sự trao quyền và tạo vị thế làm chủ", "/ɪmˈpaʊəmənt/",
         "Vocational training programs drive the socioeconomic empowerment of rural women.",
         "Các chương trình đào tạo nghề thúc đẩy sự trao quyền kinh tế - xã hội cho phụ nữ nông thôn.",
         ["female empowerment", "youth empowerment"],
         "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80"),
        ("breadwinner stereotype", "n.phr", "định kiến áp đặt người đàn ông phải là trụ cột", "/ˈbredwɪnə ˈsteriətaɪp/",
         "Challenging the breadwinner stereotype relieves intense psychological pressure on young husbands.",
         "Thách thức định kiến trụ cột kinh tế giúp giải tỏa áp lực tâm lý nặng nề cho những người chồng trẻ.",
         ["dismantle the breadwinner stereotype", "traditional stereotype"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("affirmative action", "n.phr", "chính sách ưu tiên tuyển dụng để tạo công bằng", "/əˌfɜːmətɪv ˈækʃn/",
         "The university applies affirmative action policies to increase female enrollment in robotics.",
         "Trường đại học áp dụng chính sách ưu đãi tích cực để tăng tỷ lệ nữ sinh theo học ngành robot chế tạo máy.",
         ["implement affirmative action", "affirmative action program"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("leadership quota", "n.phr", "tỷ lệ hạn ngạch bắt buộc cho lãnh đạo nữ", "/ˈliːdəʃɪp ˈkwəʊtə/",
         "Several parliaments introduced a 40 percent leadership quota to ensure gender balance.",
         "Một số nghị viện đã đưa ra hạn ngạch lãnh đạo 40 phần trăm để đảm bảo cân bằng giới tính.",
         ["meet the leadership quota", "mandate a quota"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("domestic violence", "n.phr", "hành vi bạo lực gia đình", "/dəˌmestɪk ˈvaɪələns/",
         "Community hotlines provide confidential support for survivors of domestic violence.",
         "Đường dây nóng cộng đồng cung cấp sự hỗ trợ bí mật an toàn cho các nạn nhân của bạo lực gia đình.",
         ["combat domestic violence", "victim of domestic violence"],
         "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80"),
        ("workplace harassment", "n.phr", "hành vi quấy rối nơi công sở", "/ˈwɜːkpleɪs həˈræsmənt/",
         "Zero-tolerance corporate guidelines strictly penalize all forms of workplace harassment.",
         "Quy định nghiêm ngặt của công ty xử phạt thẳng tay mọi hành vi quấy rối tại nơi làm việc.",
         ["prevent workplace harassment", "report harassment"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("career advancement", "n.phr", "sự thăng tiến và phát triển sự nghiệp", "/kəˈrɪər ədˈvɑːnsmənt/",
         "Mentorship circles provide female engineers with pathways for rapid career advancement.",
         "Các nhóm cố vấn chuyên môn mang đến cho các nữ kỹ sư lộ trình thăng tiến sự nghiệp nhanh chóng.",
         ["pursue career advancement", "opportunities for advancement"],
         "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80"),
        ("equal opportunity", "n.phr", "cơ hội bình đẳng cho mọi cá nhân", "/ˌiːkwəl ˌɒpəˈtjuːnəti/",
         "The constitution guarantees equal opportunity in public employment and civil service.",
         "Hiến pháp bảo đảm cơ hội bình đẳng trong tuyển dụng việc làm công và cơ quan nhà nước.",
         ["equal opportunity employer", "provide equal opportunity"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("stem education", "n.phr", "giáo dục khối ngành khoa học công nghệ", "/stem ˌedʒuˈkeɪʃn/",
         "Scholarships inspire high school girls to excel in STEM education tracks.",
         "Các suất học bổng truyền cảm hứng cho các nữ sinh cấp 3 xuất sắc trong các ngành giáo dục STEM.",
         ["encourage STEM education", "promote girls in STEM"],
         "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80"),
        ("wage gap", "n.phr", "khoảng cách chênh lệch mức thu nhập tiền lương", "/ˈweɪdʒ ɡæp/",
         "Transparent salary disclosures assist auditors in bridging the gender wage gap.",
         "Việc công khai minh bạch bảng lương giúp các kiểm toán viên thu hẹp khoảng cách thu nhập giới.",
         ["narrow the wage gap", "unadjusted wage gap"],
         "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80"),
        ("social prejudice", "n.phr", "định kiến xã hội cổ hủ", "/ˌsəʊʃl ˈpredʒədɪs/",
         "Education is the most potent weapon to dismantle persistent social prejudice.",
         "Giáo dục là vũ khí hữu hiệu nhất để đập tan những định kiến xã hội cổ hủ dai dẳng.",
         ["overcome social prejudice", "deep-seated prejudice"],
         "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=800&q=80"),
        ("inclusive culture", "n.phr", "văn hóa tôn trọng sự hòa nhập đa dạng", "/ɪnˈkluːsɪv ˈkʌltʃə(r)/",
         "Tech firms foster an inclusive culture where every voice contributes meaningfully to debate.",
         "Các công ty công nghệ xây dựng một văn hóa hòa nhập nơi mọi tiếng nói đều đóng góp ý nghĩa vào thảo luận.",
         ["build an inclusive culture", "thrive in an inclusive culture"],
         "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80"),
        ("double burden", "n.phr", "gánh nặng kép vừa đi làm vừa gánh việc nhà", "/ˌdʌbl ˈbɜːdn/",
         "Working mothers often bear a double burden of demanding jobs and unshared chores.",
         "Phụ nữ đi làm thường phải chịu gánh nặng kép giữa công việc áp lực và việc nhà không được sẻ chia.",
         ["relieve the double burden", "shoulder a double burden"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("female entrepreneur", "n.phr", "nữ doanh nhân sáng lập khởi nghiệp", "/ˈfiːmeɪl ˌɒntrəprəˈnɜː(r)/",
         "Microloans empower female entrepreneurs to expand eco-friendly agricultural ventures.",
         "Vốn vay vi mô tiếp sức cho các nữ doanh nhân mở rộng các dự án khởi nghiệp nông nghiệp sinh thái.",
         ["support female entrepreneurs", "successful entrepreneur"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("gender-neutral", "adj", "trung tính không phân biệt nam nữ", "/ˌdʒendə ˈnjuːtrəl/",
         "Textbooks have been updated with gender-neutral pronouns and balanced job illustrations.",
         "Sách giáo khoa đã được cập nhật với đại từ trung tính và hình ảnh minh họa nghề nghiệp cân bằng.",
         ["gender-neutral language", "gender-neutral toys"],
         "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80"),
        ("fair representation", "n.phr", "sự hiện diện đại diện công bằng", "/feə ˌreprɪzenˈteɪʃn/",
         "Voters demand fair representation of both genders on the municipal city council.",
         "Cử tri yêu cầu sự đại diện công bằng của cả hai giới trong hội đồng nhân dân thành phố.",
         ["ensure fair representation", "strive for fair representation"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("pay equity", "n.phr", "sự công bằng chính trực trong thang lương", "/peɪ ˈekwəti/",
         "Annual compensation audits verify that pay equity is strictly maintained.",
         "Kiểm toán đãi ngộ hằng năm xác minh rằng sự công bằng trong tiền lương được tuân thủ nghiêm ngặt.",
         ["achieve pay equity", "commit to pay equity"],
         "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80"),
        ("childcare subsidy", "n.phr", "trợ cấp nhà nước hỗ trợ gửi trẻ", "/ˈtʃaɪldkeə ˈsʌbsədi/",
         "A government childcare subsidy enables mothers to re-enter the workforce promptly.",
         "Khoản trợ cấp trông trẻ của chính phủ giúp các bà mẹ nhanh chóng quay trở lại thị trường lao động.",
         ["receive a childcare subsidy", "expand childcare subsidies"],
         "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&w=800&q=80"),
        ("shared responsibility", "n.phr", "trách nhiệm cùng chung vai sẻ chia", "/ʃeəd rɪˌspɒnsəˈbɪləti/",
         "Parenting is a shared responsibility requiring coordinated teamwork from both partners.",
         "Nuôi dạy con cái là trách nhiệm chung đòi hỏi sự phối hợp ăn ý từ cả hai người bạn đời.",
         ["mutual shared responsibility", "embrace shared responsibility"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("civil rights", "n.phr", "các quyền công dân cơ bản", "/ˈsɪvl raɪts/",
         "Activists peacefully protested to defend the foundational civil rights of minorities.",
         "Các nhà hoạt động đã tuần hành hòa bình để bảo vệ các quyền công dân cơ bản của nhóm thiểu số.",
         ["champion civil rights", "civil rights movement"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("role model", "n.phr", "tấm gương mẫu mực để noi theo", "/ˈrəʊl mɒdl/",
         "Astronaut Mae Jemison serves as an inspiring role model for aspiring young women.",
         "Nhà du hành vũ trụ Mae Jemison là một tấm gương truyền cảm hứng cho các cô gái trẻ đầy khát vọng.",
         ["positive role model", "act as a role model"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("unconscious bias", "n.phr", "thiên kiến vô thức trong tiềm thức", "/ʌnˈkɒnʃəs ˈbaɪəs/",
         "HR departments conduct workshops to detect and neutralize unconscious bias during hiring.",
         "Phòng nhân sự tổ chức hội thảo để phát hiện và loại bỏ các thiên kiến vô thức trong quá trình phỏng vấn.",
         ["eliminate unconscious bias", "overcome bias"],
         "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=800&q=80"),
        ("self-determination", "n", "quyền tự quyết định vận mệnh cuộc đời", "/ˌself dɪˌtɜːmɪˈneɪʃn/",
         "Access to higher education grants young women total self-determination over their careers.",
         "Cơ hội tiếp cận giáo dục đại học trao cho các cô gái trẻ quyền tự quyết hoàn toàn đối với sự nghiệp của mình.",
         ["right to self-determination", "foster self-determination"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("advocacy group", "n.phr", "nhóm vận động chính sách xã hội", "/ˈædvəkəsi ɡruːp/",
         "The advocacy group successfully lobbied for stricter penalties against sex discrimination.",
         "Nhóm vận động chính sách đã vận động thành công các chế tài nghiêm khắc hơn đối với hành vi phân biệt giới tính.",
         ["join an advocacy group", "nonprofit advocacy group"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-7-viet-nam-and-international-organisations": [
        ("multilateral diplomacy", "n.phr", "ngoại giao đa phương quốc tế", "/ˌmʌltiˈlætərəl dɪˈpləʊməsi/",
         "Viet Nam actively promotes peace and mutual stability through multilateral diplomacy.",
         "Việt Nam tích cực thúc đẩy hòa bình và ổn định khu vực thông qua nền ngoại giao đa phương.",
         ["engage in multilateral diplomacy", "conduct diplomacy"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("peacekeeping mission", "n.phr", "sứ mệnh gìn giữ hòa bình Liên Hợp Quốc", "/ˈpiːskiːpɪŋ ˈmɪʃn/",
         "Vietnamese field hospital doctors departed on a United Nations peacekeeping mission in South Sudan.",
         "Các bác sĩ bệnh viện dã chiến Việt Nam lên đường thực hiện sứ mệnh gìn giữ hòa bình Liên Hợp Quốc tại Nam Sudan.",
         ["deploy on a peacekeeping mission", "UN peacekeeping mission"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("free trade agreement", "n.phr", "hiệp định thương mại tự do", "/ˌfriː ˈtreɪd əˌɡriːmənt/",
         "Signing bilateral free trade agreements slashed tariffs and catalyzed manufacturing exports.",
         "Việc ký kết các hiệp định thương mại tự do song phương đã cắt giảm thuế quan và thúc đẩy xuất khẩu sản xuất.",
         ["negotiate a free trade agreement", "ratify an agreement"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("strategic partnership", "n.phr", "quan hệ đối tác chiến lược toàn diện", "/strəˈtiːdʒɪk ˈpɑːtnəʃɪp/",
         "The two nations upgraded their ties to a comprehensive strategic partnership.",
         "Hai quốc gia đã nâng tầm mối quan hệ lên mức đối tác chiến lược toàn diện.",
         ["forge a strategic partnership", "bilateral strategic partnership"],
         "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80"),
        ("humanitarian aid", "n.phr", "viện trợ nhân đạo cứu trợ khẩn cấp", "/hjuːˌmænɪˈteəriən eɪd/",
         "International organizations dispatched emergency humanitarian aid following the coastal typhoon.",
         "Các tổ chức quốc tế đã điều động hàng viện trợ nhân đạo khẩn cấp sau cơn bão đổ bộ vào miền duyên hải.",
         ["deliver humanitarian aid", "provide humanitarian aid"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("trade barrier", "n.phr", "rào cản bảo hộ thương mại", "/ˈtreɪd ˈbæriə(r)/",
         "The WTO encourages member states to lower trade barriers and streamline customs clearances.",
         "Tổ chức Thương mại Thế giới khuyến khích các quốc gia thành viên dỡ bỏ rào cản thương mại và đơn giản hóa thủ tục hải quan.",
         ["eliminate trade barriers", "impose trade barriers"],
         "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"),
        ("sustainable development goals", "n.phr", "các mục tiêu phát triển bền vững của LHQ", "/səˌsteɪnəbl dɪˈveləpmənt ɡəʊlz/",
         "Viet Nam is deeply committed to fulfilling the 17 UN Sustainable Development Goals by 2030.",
         "Việt Nam cam kết sâu sắc trong việc thực hiện 17 Mục tiêu Phát triển Bền vững của LHQ vào năm 2030.",
         ["achieve Sustainable Development Goals", "UN goals"],
         "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80"),
        ("bilateral ties", "n.phr", "quan hệ song phương giữa hai nước", "/ˌbaɪˈlætərəl taɪz/",
         "Diplomatic delegations met in Ha Noi to foster closer bilateral ties in green energy.",
         "Các phái đoàn ngoại giao đã gặp nhau tại Hà Nội để tăng cường quan hệ song phương chặt chẽ hơn về năng lượng xanh.",
         ["deepen bilateral ties", "strengthen bilateral ties"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("cultural diplomacy", "n.phr", "ngoại giao văn hóa quảng bá hình ảnh", "/ˈkʌltʃərəl dɪˈpləʊməsi/",
         "Food festivals and traditional music showcases serve as prime examples of cultural diplomacy.",
         "Các lễ hội ẩm thực và biểu diễn âm nhạc dân tộc đóng vai trò là ví dụ tiêu biểu của ngoại giao văn hóa.",
         ["promote cultural diplomacy", "cultural exchange diplomacy"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("foreign direct investment", "n.phr", "vốn đầu tư trực tiếp nước ngoài FDI", "/ˌfɒrən dəˈrekt ɪnˈvestmənt/",
         "Competitive tax incentives and stable politics attract massive foreign direct investment.",
         "Các ưu đãi thuế hấp dẫn và chính trị ổn định thu hút nguồn vốn đầu tư trực tiếp nước ngoài khổng lồ.",
         ["attract foreign direct investment", "inflow of investment"],
         "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"),
        ("international treaty", "n.phr", "điều ước hiệp ước quốc tế có tính ràng buộc", "/ˌɪntəˈnæʃnəl ˈtriːti/",
         "The national assembly voted overwhelmingly to ratify the climate international treaty.",
         "Quốc hội đã bỏ phiếu với đa số tuyệt đối để phê chuẩn hiệp ước quốc tế về khí hậu.",
         ["sign an international treaty", "ratify a treaty"],
         "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80"),
        ("diplomatic envoy", "n.phr", "phái viên ngoại giao đại sứ", "/ˌdɪpləˈmætɪk ˈenvɔɪ/",
         "The diplomatic envoy conveyed a message of friendship from the state president.",
         "Vị đặc phái viên ngoại giao đã chuyển tải thông điệp hữu nghị tốt đẹp từ chủ tịch nước.",
         ["dispatch a diplomatic envoy", "senior diplomatic envoy"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("global supply chain", "n.phr", "chuỗi cung ứng toàn cầu hoá", "/ˌɡləʊbl səˈplaɪ tʃeɪn/",
         "Viet Nam has emerged as a resilient manufacturing hub in the global supply chain.",
         "Việt Nam đã nổi lên như một mắt xích sản xuất kiên cường trong chuỗi cung ứng toàn cầu.",
         ["integrate into the global supply chain", "disrupt the supply chain"],
         "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80"),
        ("dispute resolution", "n.phr", "giải quyết tranh chấp bằng biện pháp hòa bình", "/dɪˈspjuːt ˌrezəˈluːʃn/",
         "International maritime laws provide frameworks for peaceful dispute resolution.",
         "Luật biển quốc tế cung cấp các khung pháp lý minh bạch cho việc giải quyết tranh chấp bằng biện pháp hòa bình.",
         ["peaceful dispute resolution", "dispute resolution mechanism"],
         "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80"),
        ("world bank", "n.phr", "ngân hàng thế giới tài trợ hạ tầng", "/wɜːld bæŋk/",
         "The World Bank funded the construction of clean water networks across the Mekong Delta.",
         "Ngân hàng Thế giới đã tài trợ kinh phí xây dựng các mạng lưới nước sạch trên khắp vùng Đồng bằng sông Cửu Long.",
         ["funded by the World Bank", "World Bank loan"],
         "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"),
        ("red cross", "n.phr", "hội chữ thập đỏ cứu trợ y tế", "/red krɒs/",
         "The Red Cross volunteers mobilized emergency food rations for inundated flood victims.",
         "Các tình nguyện viên Hội Chữ Thập Đỏ đã huy động khẩu phần lương thực khẩn cấp cho các nạn nhân vùng lũ.",
         ["volunteer with the Red Cross", "Red Cross emergency relief"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("non-governmental organization", "n.phr", "tổ chức phi chính phủ thiện nguyện", "/ˌnɒn ˌɡʌvənˈmentl ˌɔːɡənaɪˈzeɪʃn/",
         "Local youth work alongside an international non-governmental organization to conserve marine coral.",
         "Thanh niên địa phương cùng làm việc bên cạnh một tổ chức phi chính phủ quốc tế để bảo tồn san hô biển.",
         ["join a non-governmental organization", "charitable organization"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("sovereign state", "n.phr", "quốc gia có chủ quyền độc lập", "/ˈsɒvrɪn steɪt/",
         "Every sovereign state has the legitimate right to safeguard its territorial integrity.",
         "Mọi quốc gia có chủ quyền đều có quyền hợp pháp để bảo vệ toàn vẹn lãnh thổ thiêng liêng của mình.",
         ["independent sovereign state", "rights of a sovereign state"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("customs clearance", "n.phr", "thủ tục thông quan hàng hóa cửa khẩu", "/ˈkʌstəmz ˈklɪərəns/",
         "Digital tracking platforms expedite customs clearance for perishable agricultural fruits.",
         "Nền tảng giám sát kỹ thuật số đẩy nhanh thủ tục thông quan hàng hóa cho các mặt hàng hoa quả tươi xuất khẩu.",
         ["expedite customs clearance", "customs clearance documents"],
         "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80"),
        ("joint communique", "n.phr", "tuyên bố thông cáo chung sau hội nghị", "/ˌdʒɔɪnt kəˈmjuːnɪkeɪ/",
         "The summit concluded with a historic joint communique outlining regional anti-pollution accords.",
         "Hội nghị thượng đỉnh đã khép lại với bản thông cáo chung lịch sử vạch ra các thỏa thuận giảm ô nhiễm khu vực.",
         ["issue a joint communique", "sign a joint communique"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("export subsidy", "n.phr", "khoản trợ cấp khuyến khích xuất khẩu", "/ˈekspɔːt ˈsʌbsədi/",
         "Multilateral trade rules discourage unfair export subsidies that distort market pricing.",
         "Quy tắc thương mại đa phương không khuyến khích các khoản trợ cấp xuất khẩu thiếu công bằng gây méo mó giá cả thị trường.",
         ["prohibit export subsidies", "review export subsidy"],
         "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"),
        ("technological transfer", "n.phr", "chuyển giao công nghệ tân tiến", "/ˌteknəˈlɒdʒɪkl trænsˈfɜː(r)/",
         "The partnership includes training modules for technological transfer in renewable wind power.",
         "Thỏa thuận hợp tác bao gồm các học phần đào tạo chuyển giao công nghệ trong lĩnh vực điện gió tái tạo.",
         ["facilitate technological transfer", "agreement on technological transfer"],
         "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80"),
        ("poverty reduction", "n.phr", "công cuộc giảm nghèo bền vững", "/ˈpɒvəti rɪˈdʌkʃn/",
         "Micro-finance initiatives have spearheaded successful poverty reduction in highland communities.",
         "Các sáng kiến tài chính vi mô đã dẫn đầu công cuộc xóa đói giảm nghèo thành công tại các bản làng vùng cao.",
         ["achieve poverty reduction", "national poverty reduction"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("cultural exchange", "n.phr", "hoạt động giao lưu văn hóa quốc tế", "/ˈkʌltʃərəl ɪksˈtʃeɪndʒ/",
         "Student delegations visited Tokyo for an enriching weeklong cultural exchange program.",
         "Các phái đoàn học sinh đã tới Tokyo tham gia chương trình giao lưu văn hóa ý nghĩa kéo dài một tuần.",
         ["foster cultural exchange", "bilateral cultural exchange"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("regional security", "n.phr", "an ninh trật tự ổn định khu vực", "/ˌriːdʒənl sɪˈkjʊərəti/",
         "Coordinated maritime coast guard drills preserve regional security and deter piracy.",
         "Các cuộc diễn tập cảnh sát biển hiệp đồng giúp duy trì an ninh khu vực và ngăn chặn nạn cướp biển.",
         ["safeguard regional security", "threaten regional security"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("general assembly", "n.phr", "đại hội đồng Liên Hợp Quốc", "/ˌdʒenrəl əˈsembli/",
         "World leaders convene annually at the United Nations General Assembly in New York.",
         "Các nhà lãnh đạo thế giới họp mặt hằng năm tại Đại hội đồng Liên Hợp Quốc ở New York.",
         ["address the General Assembly", "vote at the General Assembly"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("tariff concession", "n.phr", "nhượng bộ thuế quan xuất nhập khẩu", "/ˈtærɪf kənˈseʃn/",
         "Negotiators agreed on generous tariff concessions to stimulate green vehicle commerce.",
         "Các nhà đàm phán đã đồng ý những nhượng bộ thuế quan ưu đãi để kích thích thương mại xe điện thân thiện môi trường.",
         ["grant tariff concessions", "reciprocal tariff concessions"],
         "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"),
        ("climate accord", "n.phr", "thỏa ước hiệp định quốc tế về khí hậu", "/ˈklaɪmət əˈkɔːd/",
         "Signatories reaffirmed their solemn obligations under the Paris climate accord.",
         "Các bên ký kết tái khẳng định nghĩa vụ trang nghiêm của mình theo hiệp định khí hậu Paris.",
         ["comply with the climate accord", "historic climate accord"],
         "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80"),
        ("cross-border investment", "n.phr", "dòng vốn đầu tư xuyên biên giới", "/ˌkrɒs ˈbɔːdə ɪnˈvestmənt/",
         "Simplified currency regulations spur robust cross-border investment throughout Southeast Asia.",
         "Quy định ngoại hối đơn giản hóa thúc đẩy dòng vốn đầu tư xuyên biên giới mạnh mẽ khắp Đông Nam Á.",
         ["stimulate cross-border investment", "flow of investment"],
         "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80"),
        ("mutual benefit", "n.phr", "lợi ích đôi bên cùng có lợi", "/ˌmjuːtʃuəl ˈbenɪfɪt/",
         "Trade partnerships flourish when built on equitable terms of mutual benefit.",
         "Các mối quan hệ đối tác thương mại thăng hoa khi được xây dựng trên các điều khoản bình đẳng cùng có lợi.",
         ["principle of mutual benefit", "for mutual benefit"],
         "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-8-new-ways-to-learn": [
        ("blended learning", "n.phr", "học tập kết hợp trực tiếp và trực tuyến", "/ˌblendɪd ˈlɜːnɪŋ/",
         "Blended learning merges classroom peer interaction with flexible online self-paced modules.",
         "Học tập kết hợp hòa quyện giữa tương tác trực tiếp trên lớp và các mô-đun tự học trực tuyến linh hoạt.",
         ["adopt blended learning", "blended learning environment"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("flipped classroom", "n.phr", "lớp học đảo ngược học trò chuẩn bị trước ở nhà", "/ˌflɪpt ˈklɑːsruːm/",
         "In a flipped classroom, students absorb video lectures at home and solve problems together in class.",
         "Trong mô hình lớp học đảo ngược, học sinh xem bài giảng video ở nhà và cùng giải quyết bài tập trên lớp.",
         ["implement a flipped classroom", "flipped classroom model"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("gamification", "n", "trò chơi hóa học tập để tăng hứng thú", "/ˌɡeɪmɪfɪˈkeɪʃn/",
         "Educational apps leverage gamification through badges, streaks, and leaderboards to keep students engaged.",
         "Các ứng dụng giáo dục tận dụng yếu tố trò chơi hóa qua huy hiệu, chuỗi học và bảng xếp hạng để giữ chân người học.",
         ["apply gamification", "gamification in education"],
         "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80"),
        ("adaptive learning", "n.phr", "học tập thích ứng tự điều chỉnh độ khó", "/əˌdæptɪv ˈlɜːnɪŋ/",
         "Adaptive learning software automatically adjusts quiz difficulty based on individual student mastery.",
         "Phần mềm học thích ứng tự động điều chỉnh độ khó của câu hỏi dựa trên mức độ nắm vững bài của từng học sinh.",
         ["powered by adaptive learning", "adaptive learning platform"],
         "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80"),
        ("digital literacy", "n.phr", "năng lực công nghệ và hiểu biết kỹ thuật số", "/ˌdɪdʒɪtl ˈlɪtərəsi/",
         "Modern curricula emphasize digital literacy so students can discern authentic facts from fake news.",
         "Chương trình học hiện đại nhấn mạnh năng lực số để học sinh phân biệt được thông tin xác thực với tin giả.",
         ["foster digital literacy", "essential digital literacy"],
         "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80"),
        ("virtual classroom", "n.phr", "lớp học ảo qua mạng internet", "/ˌvɜːtʃuəl ˈklɑːsruːm/",
         "Teachers and students connect seamlessly in high-definition virtual classrooms during remote sessions.",
         "Giáo viên và học sinh kết nối liền mạch trong các lớp học ảo độ nét cao suốt các buổi học từ xa.",
         ["enter the virtual classroom", "virtual classroom features"],
         "https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?auto=format&fit=crop&w=800&q=80"),
        ("collaborative workspace", "n.phr", "không gian làm việc nhóm trực tuyến", "/kəˌlæbərətɪv ˈwɜːkspeɪs/",
         "Shared cloud whiteboards serve as a collaborative workspace for brainstorming capstone projects.",
         "Bảng trắng điện toán đám mây đóng vai trò như không gian làm việc nhóm cho việc lên ý tưởng dự án khóa luận.",
         ["join a collaborative workspace", "online collaborative workspace"],
         "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80"),
        ("microlearning", "n", "học theo từng mẩu kiến thức ngắn 3-5 phút", "/ˈmaɪkrəʊlɜːnɪŋ/",
         "Busy professionals prefer microlearning bite-sized video lessons during daily transit commutes.",
         "Những người bận rộn ưa chuộng phương pháp học vi mô với các bài học ngắn vài phút trên đường đi làm.",
         ["utilize microlearning", "microlearning strategy"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("self-directed learning", "n.phr", "tinh thần tự học tự chủ định hướng", "/ˌself dəˈrektɪd ˈlɜːnɪŋ/",
         "University courses require strong self-directed learning habits to complete independent research.",
         "Các khóa học đại học đòi hỏi thói quen tự học tự chủ cao để hoàn thành các đề tài nghiên cứu độc lập.",
         ["encourage self-directed learning", "master self-directed learning"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("open educational resources", "n.phr", "tài nguyên giáo dục mở miễn phí", "/ˌəʊpən ˌedʒuˈkeɪʃənl rɪˈsɔːsɪz/",
         "Top universities publish open educational resources including textbooks and full lecture recordings.",
         "Các trường đại học hàng đầu công bố nguồn tài nguyên giáo dục mở gồm sách giáo trình và toàn bộ video bài giảng.",
         ["access open educational resources", "download free resources"],
         "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80"),
        ("learning management system", "n.phr", "hệ thống quản lý học tập trực tuyến LMS", "/ˈlɜːnɪŋ ˈmænɪdʒmənt ˈsɪstəm/",
         "Students submit assignments and track grade rubrics through the school's learning management system.",
         "Học sinh nộp bài tập và theo dõi biểu điểm đánh giá thông qua hệ thống quản lý học tập của nhà trường.",
         ["log in to the learning management system", "deploy an LMS"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("interactive whiteboard", "n.phr", "bảng tương tác thông minh cảm ứng", "/ˌɪntərˈæktɪv ˈwaɪtbɔːd/",
         "The instructor dragged digital geometry shapes across the large interactive whiteboard.",
         "Giáo viên kéo thả các hình học kỹ thuật số trên tấm bảng cảm ứng tương tác thông minh cỡ lớn.",
         ["write on the interactive whiteboard", "smart whiteboard"],
         "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80"),
        ("peer assessment", "n.phr", "hoạt động chấm điểm đánh giá đồng đẳng", "/ˌpɪər əˈsesmənt/",
         "Peer assessment allows students to analyze classmates' essays and gain diverse stylistic perspectives.",
         "Đánh giá đồng đẳng cho phép học sinh phân tích bài luận của bạn cùng lớp và tiếp thu nhiều góc nhìn hành văn đa dạng.",
         ["conduct peer assessment", "rubric for peer assessment"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("formative feedback", "n.phr", "nhận xét phản hồi mang tính xây dựng kịp thời", "/ˈfɔːmətɪv ˈfiːdbæk/",
         "Timely formative feedback guides learners in rectifying conceptual errors before final exams.",
         "Phản hồi định hình kịp thời giúp người học khắc phục các lỗi sai khái niệm trước kỳ thi cuối kỳ.",
         ["receive formative feedback", "provide constructive feedback"],
         "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80"),
        ("podcast lecture", "n.phr", "bài giảng âm thanh podcast tiện lợi", "/ˈpɒdkɑːst ˈlektʃə(r)/",
         "Linguistics students listen to historical podcast lectures during their afternoon walk.",
         "Sinh viên ngành ngôn ngữ học nghe các bài giảng podcast lịch sử trong lúc đi dạo buổi chiều.",
         ["listen to podcast lectures", "subscribe to lectures"],
         "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80"),
        ("online forum", "n.phr", "diễn đàn hỏi đáp thảo luận trực tuyến", "/ˈɒnlaɪn ˈfɔːrəm/",
         "Students post coding bug queries on the course online forum for community feedback.",
         "Học sinh đăng tải câu hỏi lỗi lập trình lên diễn đàn trực tuyến của khóa học để nhận trợ giúp từ cộng đồng.",
         ["participate in an online forum", "post on the forum"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("asynchronous learning", "n.phr", "học tập không đồng bộ tự chọn thời gian", "/eɪˈsɪŋkrənəs ˈlɜːnɪŋ/",
         "Asynchronous learning lets overseas students view recorded seminars at times that fit their time zones.",
         "Học tập không đồng bộ cho phép sinh viên quốc tế xem lại các buổi hội thảo đã ghi hình vào khung giờ phù hợp với múi giờ của mình.",
         ["benefit from asynchronous learning", "asynchronous courses"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("synchronous session", "n.phr", "buổi học trực tuyến trực tiếp cùng giờ", "/ˈsɪŋkrənəs ˈseʃn/",
         "Attendance is mandatory during weekly synchronous sessions for oral debate practice.",
         "Điểm danh là bắt buộc trong các buổi học trực tuyến đồng thời hằng tuần để luyện tập tranh biện nói.",
         ["join a synchronous session", "live synchronous session"],
         "https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?auto=format&fit=crop&w=800&q=80"),
        ("spaced repetition", "n.phr", "kỹ thuật lặp lại ngắt quãng để ghi nhớ sâu", "/ˌspeɪst ˌrepəˈtɪʃn/",
         "Flashcard algorithms rely on spaced repetition intervals to anchor words into long-term memory.",
         "Thuật toán flashcard dựa trên khoảng cách lặp lại ngắt quãng để khắc sâu từ vựng vào trí nhớ dài hạn.",
         ["practice spaced repetition", "spaced repetition algorithm"],
         "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80"),
        ("active recall", "n.phr", "chủ động truy xuất gợi nhớ kiến thức", "/ˌæktɪv rɪˈkɔːl/",
         "Testing yourself with flashcards practices active recall far more effectively than passive rereading.",
         "Tự kiểm tra bằng flashcard kích hoạt việc chủ động nhớ lại hiệu quả hơn nhiều so với việc chỉ đọc lại thụ động.",
         ["employ active recall", "active recall study method"],
         "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80"),
        ("mind mapping", "n.phr", "vẽ sơ đồ tư duy hệ thống hóa kiến thức", "/ˈmaɪnd mæpɪŋ/",
         "Mind mapping aids visual learners in establishing conceptual links between historical events.",
         "Vẽ sơ đồ tư duy giúp người học trực quan thiết lập các mối liên kết khái niệm giữa các sự kiện lịch sử.",
         ["utilize mind mapping", "mind mapping software"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("plagiarism checker", "n.phr", "công cụ quét phát hiện đạo văn sao chép", "/ˈpleɪdʒərɪzəm ˈtʃekə(r)/",
         "The university requires every term paper to pass through a digital plagiarism checker.",
         "Trường đại học yêu cầu mọi bài tiểu luận môn học phải được quét qua công cụ phát hiện sao chép đạo văn số.",
         ["run through a plagiarism checker", "detect plagiarism"],
         "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80"),
        ("webinar", "n", "hội thảo chuyên đề học thuật trực tuyến", "/ˈwebɪnɑː(r)/",
         "Renowned linguists hosted a live webinar demonstrating corpus analysis methodologies.",
         "Các nhà ngôn ngữ học danh tiếng đã tổ chức một buổi hội thảo trực tuyến trình diễn phương pháp phân tích kho ngữ liệu.",
         ["register for a webinar", "attend an academic webinar"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("knowledge retention", "n.phr", "khả năng lưu giữ ghi nhớ kiến thức lâu dài", "/ˈnɒlɪdʒ rɪˈtenʃn/",
         "Hands-on science experiments yield substantially higher knowledge retention than lectures.",
         "Các thí nghiệm khoa học thực hành mang lại khả năng ghi nhớ kiến thức cao hơn đáng kể so với việc chỉ nghe giảng.",
         ["boost knowledge retention", "long-term retention"],
         "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80"),
        ("digital distraction", "n.phr", "sự xao nhãng mất tập trung do thiết bị số", "/ˌdɪdʒɪtl dɪˈstrækʃn/",
         "Turning off phone notifications minimizes digital distraction during intense revision hours.",
         "Tắt thông báo điện thoại giúp giảm thiểu sự xao nhãng do thiết bị số trong những giờ ôn thi căng thẳng.",
         ["eliminate digital distraction", "susceptible to distraction"],
         "https://images.unsplash.com/photo-1527689368864-3a821dbccc34?auto=format&fit=crop&w=800&q=80"),
        ("critical thinking", "n.phr", "tư duy phản biện phân tích lập luận", "/ˌkrɪtɪkl ˈθɪŋkɪŋ/",
         "Debate clubs nurture critical thinking by examining issues from multiple dialectical angles.",
         "Câu lạc bộ tranh biện nuôi dưỡng tư duy phản biện bằng cách xem xét các vấn đề từ nhiều góc độ biện chứng.",
         ["sharpen critical thinking", "critical thinking skills"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("personalized instruction", "n.phr", "phương pháp giảng dạy cá nhân hóa", "/ˈpɜːsənəlaɪzd ɪnˈstrʌkʃn/",
         "AI tutors deliver personalized instruction targeted specifically at a student's weak concepts.",
         "Gia sư AI mang đến phương pháp giảng dạy cá nhân hóa nhắm trúng các khái niệm học sinh còn yếu.",
         ["offer personalized instruction", "tailor instruction"],
         "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80"),
        ("digital credential", "n.phr", "chứng chỉ số xác thực bằng blockchain", "/ˌdɪdʒɪtl krəˈdenʃl/",
         "Completing the coding bootcamp awards a verifiable digital credential for LinkedIn.",
         "Hoàn thành khóa lập trình cấp chứng chỉ số có thể xác thực trực tiếp trên hồ sơ LinkedIn.",
         ["earn a digital credential", "issue digital credentials"],
         "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80"),
        ("screen fatigue", "n.phr", "sự mệt mỏi thị giác do nhìn màn hình lâu", "/skriːn fəˈtiːɡ/",
         "Practicing the 20-20-20 rule mitigates acute eye strain and screen fatigue.",
         "Áp dụng quy tắc 20-20-20 giúp làm dịu cảm giác mỏi mắt và mệt mỏi thị giác do nhìn màn hình máy tính quá lâu.",
         ["suffer from screen fatigue", "prevent screen fatigue"],
         "https://images.unsplash.com/photo-1527689368864-3a821dbccc34?auto=format&fit=crop&w=800&q=80"),
        ("lifelong learner", "n.phr", "người không ngừng học tập suốt đời", "/ˌlaɪflɒŋ ˈlɜːnə(r)/",
         "The digital era demands every professional to be an adaptable, proactive lifelong learner.",
         "Kỷ nguyên số đòi hỏi mỗi người đi làm phải là một người ham học hỏi suốt đời có khả năng thích ứng linh hoạt.",
         ["become a lifelong learner", "spirit of a lifelong learner"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-9-protecting-the-environment": [
        ("carbon footprint", "n.phr", "dấu chân carbon lượng khí thải cá nhân", "/ˌkɑːbən ˈfʊtprɪnt/",
         "Commuting via electric metro significantly diminishes an urbanite's individual carbon footprint.",
         "Đi làm bằng tàu điện ngầm giúp giảm thiểu đáng kể dấu chân carbon cá nhân của người dân thành thị.",
         ["reduce carbon footprint", "calculate carbon footprint"],
         "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80"),
        ("deforestation", "n", "nạn phá rừng hủy hoại thảm thực vật", "/diːˌfɒrɪˈsteɪʃn/",
         "Illegal deforestation in tropical rainforests destroys ancient habitats of endangered primates.",
         "Nạn chặt phá rừng trái phép ở các khu rừng nhiệt đới phá hủy môi trường sống cổ xưa của các loài linh trưởng quý hiếm.",
         ["halt deforestation", "driver of deforestation"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("biodiversity loss", "n.phr", "sự mất mát suy giảm đa dạng sinh học", "/ˌbaɪəʊdaɪˈvɜːsəti lɒs/",
         "Widespread pesticide runoff accelerates acute biodiversity loss across rural wetlands.",
         "Dòng nước chảy nhiễm thuốc trừ sâu lan rộng làm gia tăng sự suy giảm đa dạng sinh học tại các vùng đất ngập nước.",
         ["stem biodiversity loss", "threat of biodiversity loss"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("renewable energy", "n.phr", "nguồn năng lượng tái tạo sạch", "/rɪˌnjuːəbl ˈenədʒi/",
         "Offshore wind farms generate abundant clean, renewable energy for maritime cities.",
         "Các trang trại điện gió ngoài khơi tạo ra nguồn năng lượng tái tạo sạch dồi dào cho các thành phố ven biển.",
         ["invest in renewable energy", "renewable energy transition"],
         "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80"),
        ("greenhouse gas emissions", "n.phr", "lượng khí thải nhà kính gây nóng lên", "/ˈɡriːnhaʊs ɡæs ɪˈmɪʃnz/",
         "International treaties mandate strict legal caps on national greenhouse gas emissions.",
         "Các hiệp ước quốc tế quy định hạn ngạch pháp lý nghiêm ngặt đối với lượng khí thải nhà kính của các quốc gia.",
         ["curb greenhouse gas emissions", "net-zero emissions"],
         "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80"),
        ("plastic pollution", "n.phr", "ô nhiễm rác thải nhựa đại dương", "/ˈplæstɪk pəˈluːʃn/",
         "Community volunteers collected marine trash along beaches to combat plastic pollution.",
         "Các tình nguyện viên cộng đồng đã thu gom rác biển dọc bờ biển để đẩy lùi nạn ô nhiễm rác thải nhựa.",
         ["fight plastic pollution", "choked by plastic pollution"],
         "https://images.unsplash.com/photo-1621451537084-482c73073a0f?auto=format&fit=crop&w=800&q=80"),
        ("ecosystem restoration", "n.phr", "sự phục hồi cân bằng hệ sinh thái", "/ˈiːkəʊsɪstəm ˌrestəˈreɪʃn/",
         "Mangrove replanting drives comprehensive coastal ecosystem restoration and storm protection.",
         "Việc trồng lại rừng ngập mặn thúc đẩy sự phục hồi toàn diện hệ sinh thái ven biển và che chắn bão.",
         ["spearhead ecosystem restoration", "fund restoration"],
         "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80"),
        ("sustainable agriculture", "n.phr", "nền nông nghiệp bền vững hữu cơ", "/səˌsteɪnəbl ˈæɡrɪkʌltʃə(r)/",
         "Crop rotation and organic compost form the backbone of sustainable agriculture.",
         "Luân canh cây trồng và phân hữu cơ tạo nên nền tảng cốt lõi của nền nông nghiệp bền vững.",
         ["promote sustainable agriculture", "methods of agriculture"],
         "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80"),
        ("composting", "n", "việc ủ phân hữu cơ từ rác nhà bếp", "/ˈkɒmpɒstɪŋ/",
         "Backyard composting turns fruit peels and vegetable scraps into nutrient-rich soil.",
         "Việc ủ phân tại vườn nhà biến vỏ trái cây và rau thừa thành lớp đất giàu dinh dưỡng cho cây trồng.",
         ["start composting", "home composting system"],
         "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80"),
        ("landfill waste", "n.phr", "rác thải chôn lấp tại bãi rác", "/ˈlændfɪl weɪst/",
         "Rigorous sorting of recyclables cuts household landfill waste by more than fifty percent.",
         "Phân loại rác tái chế kỹ lưỡng giúp cắt giảm lượng rác thải sinh hoạt chôn lấp hơn năm mươi phần trăm.",
         ["divert landfill waste", "overflowing landfill"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("water conservation", "n.phr", "bảo tồn gìn giữ nguồn nước ngọt", "/ˈwɔːtə ˌkɒnsəˈveɪʃn/",
         "Low-flow shower heads and rainwater cisterns promote household water conservation.",
         "Vòi hoa sen tiết kiệm nước và bể chứa nước mưa thúc đẩy việc bảo tồn nước trong gia đình.",
         ["practice water conservation", "water conservation campaign"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("afforestation", "n", "hoạt động trồng rừng gây rừng mới", "/əˌfɒrɪˈsteɪʃn/",
         "Large-scale national afforestation projects transform arid plains into lush carbon sinks.",
         "Các dự án trồng rừng mới quy mô quốc gia biến những vùng đất khô cằn thành những bể chứa carbon xanh tốt.",
         ["support afforestation", "afforestation drive"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("microplastics", "n.pl", "hạt vi nhựa siêu nhỏ gây độc sinh vật", "/ˈmaɪkrəʊplæstɪks/",
         "Marine biologists discover alarming concentrations of toxic microplastics inside deep-sea fish.",
         "Các nhà sinh vật biển phát hiện nồng độ hạt vi nhựa độc hại đáng báo động bên trong cá biển sâu.",
         ["ingest microplastics", "filtered microplastics"],
         "https://images.unsplash.com/photo-1621451537084-482c73073a0f?auto=format&fit=crop&w=800&q=80"),
        ("energy efficiency", "n.phr", "hiệu suất sử dụng năng lượng tối ưu", "/ˈenədʒi ɪˈfɪʃnsi/",
         "Double-glazed glass windows enhance home heating and cooling energy efficiency.",
         "Cửa sổ kính hai lớp giúp tăng cường hiệu suất sử dụng năng lượng khi sưởi ấm và làm mát nhà.",
         ["improve energy efficiency", "rating for energy efficiency"],
         "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80"),
        ("hazardous waste", "n.phr", "chất thải nguy hại chứa hóa chất độc", "/ˈhæzədəs weɪst/",
         "Specialized facilities are legally certified to incinerate hospital hazardous waste safely.",
         "Các cơ sở chuyên dụng được cấp phép để thiêu hủy chất thải y tế nguy hại một cách an toàn.",
         ["dispose of hazardous waste", "hazardous waste regulations"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("circular economy", "n.phr", "mô hình kinh tế tuần hoàn tái sử dụng", "/ˌsɜːkjələr ɪˈkɒnəmi/",
         "A circular economy emphasizes repairing, repurposing, and recycling raw materials endlessly.",
         "Kinh tế tuần hoàn nhấn mạnh việc sửa chữa, tái chế và tái sử dụng nguyên vật liệu liên tục.",
         ["transition to a circular economy", "circular economy framework"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("ecological balance", "n.phr", "sự cân bằng sinh thái của tự nhiên", "/ˌiːkəˈlɒdʒɪkl ˈbæləns/",
         "Overfishing of top predators threatens the delicate ecological balance of coral reefs.",
         "Việc đánh bắt quá mức các loài săn mồi đỉnh đe dọa sự cân bằng sinh thái mong manh của rạn san hô.",
         ["preserve ecological balance", "disrupt balance"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("air purifier", "n.phr", "máy lọc không khí khử bụi mịn", "/ˈeə pjʊərɪfaɪə(r)/",
         "Households in smog-prone metropolises rely on HEPA air purifiers to filter particulate dust.",
         "Nhiều gia đình ở các đô thị có sương mù khói bụi lắp máy lọc không khí HEPA để khử bụi mịn.",
         ["install an air purifier", "HEPA air purifier"],
         "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80"),
        ("single-use plastic", "n.phr", "nhựa dùng một lần rồi vứt bỏ", "/ˌsɪŋɡl juːs ˈplæstɪk/",
         "Supermarkets phased out single-use plastic grocery bags in favor of durable woven canvas totes.",
         "Các siêu thị đã dừng sử dụng túi nhựa dùng một lần để chuyển sang các túi vải bạt bền đẹp.",
         ["ban single-use plastic", "alternatives to single-use plastic"],
         "https://images.unsplash.com/photo-1621451537084-482c73073a0f?auto=format&fit=crop&w=800&q=80"),
        ("soil erosion", "n.phr", "sự xói mòn và rửa trôi đất canh tác", "/sɔɪl ɪˈrəʊʒn/",
         "Planting vetiver grass along steep hillsides prevents devastating monsoon soil erosion.",
         "Trồng cỏ vetiver dọc sườn đồi dốc giúp ngăn ngừa tình trạng xói mòn đất nghiêm trọng do mưa bão.",
         ["prevent soil erosion", "susceptible to erosion"],
         "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80"),
        ("ozone depletion", "n.phr", "sự suy giảm thủng tầng ozone", "/ˈəʊzəʊn dɪˈpliːʃn/",
         "The Montreal Protocol successfully reversed critical global ozone depletion trends.",
         "Nghị định thư Montreal đã đảo ngược thành công xu hướng suy giảm tầng ozone nguy kịch toàn cầu.",
         ["combat ozone depletion", "substances causing depletion"],
         "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80"),
        ("carbon offset", "n.phr", "khoản bù đắp phát thải carbon", "/ˈkɑːbən ˈɒfset/",
         "Airlines allow passengers to purchase carbon offset credits that fund tree planting reserves.",
         "Các hãng hàng không cho phép hành khách mua tín chỉ bù đắp carbon để gây quỹ cho các khu bảo tồn trồng rừng.",
         ["purchase carbon offsets", "verified carbon offset"],
         "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80"),
        ("green transport", "n.phr", "phương tiện giao thông xanh không khói", "/ɡriːn ˈtrænspɔːt/",
         "Municipal leaders invest billions in green transport including electric buses and bike lanes.",
         "Lãnh đạo thành phố đầu tư hàng tỷ đô vào giao thông xanh bao gồm xe buýt điện và làn đường cho xe đạp.",
         ["promote green transport", "switch to green transport"],
         "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=800&q=80"),
        ("zero-emission vehicle", "n.phr", "phương tiện không phát thải khí nhà kính", "/ˌzɪərəʊ ɪˈmɪʃn ˈviːəkl/",
         "Tax incentives accelerate the widespread adoption of zero-emission vehicles across suburban districts.",
         "Các ưu đãi thuế đẩy nhanh việc áp dụng rộng rãi xe không phát thải trên khắp các quận ngoại ô.",
         ["drive a zero-emission vehicle", "mandate zero-emission vehicles"],
         "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80"),
        ("poaching", "n", "hành vi săn trộm động vật hoang dã", "/ˈpəʊtʃɪŋ/",
         "Armed park rangers patrol sanctuaries day and night to stop elephant and rhino poaching.",
         "Lực lượng kiểm lâm tuần tra các khu bảo tồn ngày đêm để ngăn chặn nạn săn trộm voi và tê giác.",
         ["deter illegal poaching", "anti-poaching patrol"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("endangered species", "n.phr", "loài sinh vật nguy cấp đứng trước nguy cơ tuyệt chủng", "/ɪnˌdeɪndʒəd ˈspiːʃiːz/",
         "The red panda is classified as an endangered species facing shrinking forest bamboo groves.",
         "Gấu trúc đỏ được phân loại là loài nguy cấp đối mặt với việc các rặng tre rừng ngày càng thu hẹp.",
         ["protect endangered species", "list of endangered species"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("habitat destruction", "n.phr", "sự tàn phá sinh cảnh sống tự nhiên", "/ˈhæbɪtæt dɪˈstrʌkʃn/",
         "Unregulated urban sprawl causes irreversible habitat destruction for local bird populations.",
         "Quá trình đô thị hóa tràn lan gây ra sự tàn phá sinh cảnh sống không thể đảo ngược cho các quần thể chim địa phương.",
         ["halt habitat destruction", "consequences of habitat destruction"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("environmental stewardship", "n.phr", "tinh thần trách nhiệm bảo vệ môi trường", "/ɪnˌvaɪrənˈmentl ˈstjuːədʃɪp/",
         "Schools foster environmental stewardship through campus vegetable gardens and cleanups.",
         "Các trường học bồi đắp tinh thần bảo vệ môi trường thông qua vườn rau trong khuôn viên và các đợt dọn vệ sinh.",
         ["demonstrate environmental stewardship", "embrace stewardship"],
         "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80"),
        ("green building", "n.phr", "công trình kiến trúc xanh tiết kiệm năng lượng", "/ɡriːn ˈbɪldɪŋ/",
         "The corporate headquarters received LEED platinum certification for its smart green building architecture.",
         "Trụ sở tập đoàn đã nhận chứng chỉ bạch kim LEED nhờ kiến trúc công trình xanh thông minh.",
         ["design green buildings", "green building standards"],
         "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80"),
        ("eco-friendly packaging", "n.phr", "bao bì sinh học thân thiện với môi trường", "/ˌiːkəʊ ˈfrendli ˈpækɪdʒɪŋ/",
         "Brands have transitioned entirely to biodegradable cornstarch and mushroom eco-friendly packaging.",
         "Các thương hiệu đã chuyển đổi hoàn toàn sang bao bì sinh học thân thiện làm từ tinh bột ngô và nấm.",
         ["use eco-friendly packaging", "innovative packaging"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-10-ecotourism": [
        ("nature reserve", "n.phr", "khu bảo tồn thiên nhiên được bảo vệ nghiêm ngặt", "/ˈneɪtʃə rɪˈzɜːv/",
         "Visitors in the nature reserve must strictly remain on marked walking timber boardwalks.",
         "Khách tham quan trong khu bảo tồn thiên nhiên phải tuân thủ nghiêm việc chỉ đi trên lối đi bằng gỗ quy định.",
         ["explore a nature reserve", "wildlife in a nature reserve"],
         "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80"),
        ("responsible tourism", "n.phr", "du lịch có trách nhiệm với cộng đồng và thiên nhiên", "/rɪˌspɒnsəbl ˈtʊərɪzəm/",
         "Responsible tourism minimizes carbon emissions while contributing revenue directly to native villages.",
         "Du lịch có trách nhiệm giảm thiểu phát thải carbon đồng thời đóng góp doanh thu trực tiếp cho các bản làng bản địa.",
         ["practice responsible tourism", "code of responsible tourism"],
         "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80"),
        ("indigenous community", "n.phr", "cộng đồng người bản địa sinh sống lâu đời", "/ɪnˈdɪdʒənəs kəˈmjuːnəti/",
         "Homestays run by the indigenous community offer travelers authentic immersion into ancestral crafts.",
         "Những căn nhà homestay do cộng đồng bản địa tự quản lý mang lại cho du khách trải nghiệm chân thực về nghề thủ công truyền thống.",
         ["support indigenous communities", "heritage of the community"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("low-impact travel", "n.phr", "du lịch tác động thấp hạn chế tối đa rác và khí thải", "/ˌləʊ ˈɪmpækt ˈtrævl/",
         "Bicycling through national park valley trails exemplifies low-impact travel.",
         "Đạp xe qua các cung đường thung lũng vườn quốc gia là hình mẫu tiêu biểu của phong cách du lịch tác động thấp.",
         ["opt for low-impact travel", "low-impact travel principles"],
         "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=800&q=80"),
        ("cultural sensitivity", "n.phr", "sự nhạy bén tôn trọng phong tục văn hóa địa phương", "/ˌkʌltʃərəl ˌsensəˈtɪvəti/",
         "Tour guides brief foreign trekkers on dress codes to maintain cultural sensitivity at mountain temples.",
         "Hướng dẫn viên nhắc nhở du khách về quy chuẩn trang phục nhằm giữ gìn sự tôn trọng văn hóa tại các ngôi chùa vùng cao.",
         ["exercise cultural sensitivity", "demonstrate sensitivity"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("carrying capacity", "n.phr", "sức chứa du khách tối đa để bảo vệ sinh thái", "/ˈkæriɪŋ kəˈpæsəti/",
         "The marine island limits daily ferry passenger numbers to remain well within its environmental carrying capacity.",
         "Hòn đảo giới hạn số lượng khách đi phà mỗi ngày để nằm trong ngưỡng sức chứa môi trường cho phép.",
         ["exceed carrying capacity", "calculate carrying capacity"],
         "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"),
        ("eco-resort", "n.phr", "khu nghỉ dưỡng sinh thái sử dụng năng lượng mặt trời", "/ˈiːkəʊ rɪˈzɔːt/",
         "The beachfront eco-resort powers all bungalows with solar panels and harvests rainwater.",
         "Khu nghỉ dưỡng sinh thái ven biển vận hành toàn bộ các căn nhà bungalow bằng pin mặt trời và thu gom nước mưa.",
         ["stay at an eco-resort", "sustainable eco-resort"],
         "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80"),
        ("guided trek", "n.phr", "chuyến đi bộ xuyên rừng có hướng dẫn viên", "/ˈɡaɪdɪd trek/",
         "Visitors booked a three-day guided trek through Phong Nha-Ke Bang's subterranean river caves.",
         "Du khách đặt chuyến đi bộ vượt rừng ba ngày có người dẫn đường qua các hang động sông ngầm Phong Nha - Kẻ Bàng.",
         ["embark on a guided trek", "strenuous guided trek"],
         "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"),
        ("wildlife viewing", "n.phr", "hoạt động ngắm nhìn động vật hoang dã tự nhiên", "/ˈwaɪldlaɪf ˈvjuːɪŋ/",
         "Early dawn boat rides on the lagoon present tranquil opportunities for migratory wildlife viewing.",
         "Những chuyến thuyền sớm lúc bình minh trên đầm phá mang lại cơ hội tuyệt vời để chiêm ngưỡng chim di cư ngoài tự nhiên.",
         ["ethical wildlife viewing", "wildlife viewing platform"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("leave no trace", "idiom", "nguyên tắc không để lại dấu vết rác thải trong tự nhiên", "/liːv nəʊ treɪs/",
         "Campers follow the strict leave no trace ethic by packing out all remnants of plastic and food packaging.",
         "Những người cắm trại tuân thủ nghiêm ngặt nguyên tắc không để lại dấu vết bằng cách gom sạch mọi bao bì và rác thải mang về.",
         ["practice leave no trace", "leave no trace guidelines"],
         "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80"),
        ("local craft", "n.phr", "sản phẩm thủ công mỹ nghệ địa phương", "/ˈləʊkl krɑːft/",
         "Purchasing local crafts like handwoven brocade directly bolsters tribal artisan households.",
         "Mua sắm các sản phẩm thủ công địa phương như thổ cẩm dệt tay giúp trực tiếp nuôi sống các gia đình nghệ nhân dân tộc.",
         ["support local crafts", "traditional local crafts"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("canopy walkway", "n.phr", "cầu treo đi bộ trên ngọn cây rừng nguyên sinh", "/ˈkænəpi ˈwɔːkweɪ/",
         "Suspended high above the forest floor, the canopy walkway grants breathtaking panoramic jungle vistas.",
         "Được treo lơ lửng trên các tầng cây rừng, cây cầu đi bộ trên ngọn cây đem lại tầm nhìn toàn cảnh rừng rậm tuyệt mỹ.",
         ["stroll along the canopy walkway", "aerial canopy walkway"],
         "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80"),
        ("sustainable lodging", "n.phr", "cơ sở lưu trú đạt tiêu chuẩn bảo vệ sinh thái", "/səˌsteɪnəbl ˈlɒdʒɪŋ/",
         "Ecolodges built with untreated bamboo and thatch provide rustic sustainable lodging.",
         "Những căn nhà sinh thái dựng từ tre nứa mộc và mái lá mang lại chỗ lưu trú mộc mạc và thân thiện với tự nhiên.",
         ["book sustainable lodging", "certified lodging"],
         "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80"),
        ("botanical garden", "n.phr", "vườn thực vật bảo tồn các loài cây hoa quý", "/bəˈtænɪkl ˈɡɑːdn/",
         "The botanical garden preserves rare alpine medicinal herbs collected across the northern highlands.",
         "Vườn thực vật lưu giữ và bảo tồn các loài thảo dược quý hiếm vùng núi cao thu thập từ khắp vùng cao phía Bắc.",
         ["visit a botanical garden", "stroll through the garden"],
         "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80"),
        ("pristine landscape", "n.phr", "phong cảnh thiên nhiên nguyên sơ chưa bị tàn phá", "/ˈprɪstiːn ˈlændskeɪp/",
         "The island's pristine landscape of emerald lagoons and limestone cliffs left tourists utterly spellbound.",
         "Khung cảnh nguyên sơ của hòn đảo với đầm phá xanh ngọc bích và vách đá vôi khiến du khách hoàn toàn mê đắm.",
         ["admire pristine landscapes", "preserve pristine landscapes"],
         "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"),
        ("biodegradable sunscreen", "n.phr", "kem chống nắng phân hủy sinh học an toàn cho san hô", "/ˌbaɪəʊdɪˈɡreɪdəbl ˈsʌnskriːn/",
         "Snorkelers are required to wear coral-safe biodegradable sunscreen before jumping into the marine bay.",
         "Du khách lặn biển phải thoa kem chống nắng phân hủy sinh học an toàn cho san hô trước khi nhảy xuống vịnh biển.",
         ["apply biodegradable sunscreen", "coral-safe sunscreen"],
         "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"),
        ("birdwatching sanctuary", "n.phr", "khu bảo tồn ngắm chim hoang dã", "/ˈbɜːdwɒtʃɪŋ ˈsæŋktʃuəri/",
         "Armed with binoculars, naturalists gathered at Tram Chim birdwatching sanctuary to glimpse Sarus cranes.",
         "Mang theo ống nhòm, các nhà tự nhiên học hội tụ tại khu bảo tồn chim Tràm Chim để ngắm nhìn sếu đầu đỏ.",
         ["flock to the sanctuary", "wetland birdwatching sanctuary"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("conservation levy", "n.phr", "khoản phí bảo tồn môi trường thu từ du khách", "/ˌkɒnsəˈveɪʃn ˈlevi/",
         "Ticket revenues include a modest conservation levy dedicated directly to reforestation patrols.",
         "Doanh thu tiền vé bao gồm một khoản phí bảo tồn nhỏ được dùng trực tiếp cho các đội tuần tra trồng rừng.",
         ["impose a conservation levy", "fund wildlife through a levy"],
         "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80"),
        ("organic farmstay", "n.phr", "nông trại hữu cơ kết hợp trải nghiệm lưu trú", "/ɔːˈɡænɪk ˈfɑːmsteɪ/",
         "Guests at the organic farmstay harvested fresh heirloom strawberries for their breakfast smoothie bowls.",
         "Khách tại nông trại hữu cơ tự tay thu hoạch những quả dâu tây tươi ngon cho bữa sinh tố sáng lành mạnh.",
         ["book an organic farmstay", "farmstay experience"],
         "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80"),
        ("scenic overlook", "n.phr", "điểm ngắm cảnh thiên nhiên trên cao", "/ˈsiːnɪk ˈəʊvəlʊk/",
         "The mountain pass features a panoramic scenic overlook presenting sweeping views of terraced rice valleys.",
         "Đèo núi có điểm dừng chân ngắm cảnh trên cao tuyệt đẹp mở ra góc nhìn bao la ôm trọn những thung lũng ruộng bậc thang.",
         ["stop at a scenic overlook", "scenic overlook terrace"],
         "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"),
        ("marine sanctuary", "n.phr", "khu bảo tồn biển nghiêm cấm đánh bắt", "/məˈriːn ˈsæŋktʃuəri/",
         "Fishing trawlers are banned inside the Cu Lao Cham marine sanctuary to let reef fish spawn freely.",
         "Tàu kéo đánh bắt bị cấm hoàn toàn trong khu bảo tồn biển Cù Lao Chàm để cá rạn san hô tự do sinh sản.",
         ["establish a marine sanctuary", "dive in a marine sanctuary"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("eco-conscious traveler", "n.phr", "du khách có ý thức bảo vệ môi trường", "/ˌiːkəʊ ˈkɒnʃəs ˈtrævələ(r)/",
         "Eco-conscious travelers bring reusable stainless steel bottles and reject disposable hotel plastic tubes.",
         "Những du khách có ý thức môi trường luôn mang theo bình giữ nhiệt inox và từ chối các chai nhựa dùng một lần ở khách sạn.",
         ["cater to eco-conscious travelers", "habits of conscious travelers"],
         "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80"),
        ("cultural heritage tour", "n.phr", "tour du lịch tìm hiểu di sản văn hóa", "/ˈkʌltʃərəl ˈherɪtɪdʒ tʊə(r)/",
         "The cultural heritage tour guided students through ancient citadel ruins and bronze casting foundries.",
         "Tour di sản văn hóa đã dẫn dắt học sinh tham quan các phế tích hoàng thành cổ và các xưởng đúc đồng truyền thống.",
         ["join a cultural heritage tour", "guided heritage tour"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("carbon-neutral itinerary", "n.phr", "hành trình du lịch trung hòa carbon", "/ˌkɑːbən ˈnjuːtrəl aɪˈtɪnərəri/",
         "The travel agency engineered a fully carbon-neutral itinerary utilizing electric rail and certified lodges.",
         "Công ty du lịch đã thiết kế hành trình hoàn toàn trung hòa carbon sử dụng đường sắt chạy điện và cơ sở lưu trú đạt chuẩn xanh.",
         ["design a carbon-neutral itinerary", "book a neutral tour"],
         "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80"),
        ("voluntourism", "n", "du lịch kết hợp làm công tác tình nguyện xã hội", "/ˌvɒlənˈtʊərɪzəm/",
         "Voluntourism programs allow participants to teach conversational English while exploring rural highlands.",
         "Các chương trình du lịch tình nguyện cho phép người tham gia dạy tiếng Anh giao tiếp trong khi khám phá vùng cao.",
         ["critique voluntourism", "ethical voluntourism"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("off-the-beaten-track", "idiom", "nơi hẻo lánh hoang sơ ít người đặt chân tới", "/ˌɒf ðə ˌbiːtn ˈtræk/",
         "Adventurous backpackers ventured off-the-beaten-track to hidden waterfalls deep within the misty mountains.",
         "Những tay phượt thủ ưa mạo hiểm đã tìm đến những chốn hoang sơ ít người đặt chân tới để chiêm ngưỡng thác nước ẩn mình trong núi sương mù.",
         ["travel off-the-beaten-track", "remote destination"],
         "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"),
        ("eco-lodge", "n", "nhà trọ du lịch sinh thái hòa mình vào thiên nhiên", "/ˈiːkəʊlɒdʒ/",
         "Perched on stilts overlooking the rainforest valley, the eco-lodge utilizes natural cross-ventilation.",
         "Được dựng trên các cột nhà sàn nhìn xuống thung lũng rừng nhiệt đới, nhà trọ sinh thái tận dụng luồng thông gió tự nhiên mát rượi.",
         ["stay at an eco-lodge", "rustic eco-lodge"],
         "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80"),
        ("snorkeling reef", "n.phr", "rạn san hô nông lý tưởng cho lặn ống thở", "/ˈsnɔːkəlɪŋ riːf/",
         "Colorful parrotfish and sea anemones thrive throughout the sheltered snorkeling reef.",
         "Cá vẹt rực rỡ sắc màu và hải quỳ sinh sôi mạnh mẽ khắp rạn san hô nông kín gió lý tưởng cho lặn ống thở.",
         ["explore the snorkeling reef", "shallow reef"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("zero-waste travel", "n.phr", "phong cách du lịch không rác thải", "/ˌzɪərəʊ ˈweɪst ˈtrævl/",
         "Zero-waste travel advocates carry cloth napkins, metal straws, and solid soap bars everywhere.",
         "Những người ủng hộ phong cách du lịch không rác thải luôn mang theo khăn vải, ống hút kim loại và xà phòng bánh đến mọi nơi.",
         ["commit to zero-waste travel", "zero-waste packing"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("wilderness expedition", "n.phr", "chuyến thám hiểm vùng đất hoang dã", "/ˈwɪldənəs ˌekspəˈdɪʃn/",
         "Experienced mountaineers packed thermal gear for an intensive wilderness expedition across Mount Fansipan.",
         "Các nhà leo núi dày dạn kinh nghiệm chuẩn bị đồ giữ nhiệt cho chuyến thám hiểm thiên nhiên hoang dã đỉnh Fansipan kỳ vĩ.",
         ["undertake a wilderness expedition", "challenging expedition"],
         "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80")
    ]
}

def inject_to_file(filepath, unit_data_map):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    for unit_slug, items in unit_data_map.items():
        search_key = f'"{unit_slug}": ['
        idx = content.find(search_key)
        if idx != -1:
            close_idx = content.find('  ],', idx)
            if close_idx != -1:
                block_entries = []
                for item in items:
                    word, pos, vi, ipa, en_ex, vi_ex, colocs, img = item
                    cid = f"mega-{unit_slug[:6]}-{word.lower().replace(' ', '-').replace('/', '-')}"
                    audio = f"https://dict.youdao.com/dictvoice?audio={word.replace(' ', '+')}&type=2"
                    block_entries.append('    ,')
                    block_entries.append('    {')
                    block_entries.append(f'      id: {json.dumps(cid)},')
                    block_entries.append(f'      word: {json.dumps(word)},')
                    block_entries.append(f'      partOfSpeech: {json.dumps(pos)},')
                    block_entries.append(f'      meaningVi: {json.dumps(vi)},')
                    block_entries.append(f'      ipa: {json.dumps(ipa)},')
                    block_entries.append(f'      audioUrl: {json.dumps(audio)},')
                    block_entries.append(f'      imageUrl: {json.dumps(img)},')
                    block_entries.append(f'      exampleEn: {json.dumps(en_ex)},')
                    block_entries.append(f'      exampleVi: {json.dumps(vi_ex)},')
                    block_entries.append(f'      collocations: {json.dumps(colocs)}')
                    block_entries.append('    }')
                insert_str = "\n".join(block_entries) + "\n"
                content = content[:close_idx] + insert_str + content[close_idx:]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

g10_path = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "curriculum", "expanded-vocab-g10.ts")
inject_to_file(g10_path, G10_PART2)
print("Injected extra words into G10 units 6, 7, 8, 9, 10!")
