# -*- coding: utf-8 -*-
"""
Inject the exact remaining words into Grade 12 and Grade 11 so that
EVERY SINGLE UNIT across Grades 10, 11, 12 reaches 52 to 80 words!
Curated strictly from Cambridge Dictionary, Global Success textbook, VietJack, and Loigiaihay.
"""
import json
import os

# Grade 11: Unit 6 needs 6 more words to hit 56 words
G11_EXTRA = {
    "unit-6-preserving-our-heritage": [
        ("historic relic", "n.phr", "di tích lịch sử quý báu có giá trị", "/hɪˈstɒrɪk ˈrelɪk/",
         "The ancient pagoda houses a precious historic relic from the Ly Dynasty.",
         "Ngôi chùa cổ lưu giữ một di tích lịch sử quý báu từ thời nhà Lý.",
         ["precious historic relic", "preserve historic relics"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("cultural identity", "n.phr", "bản sắc văn hóa dân tộc độc đáo", "/ˈkʌltʃərəl aɪˈdentəti/",
         "Traditional costumes help young generations maintain their cultural identity.",
         "Trang phục truyền thống giúp thế hệ trẻ duy trì bản sắc văn hóa của mình.",
         ["preserve cultural identity", "strong cultural identity"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("customs and traditions", "n.phr", "phong tục tập quán truyền thống lâu đời", "/ˈkʌstəmz ənd trəˈdɪʃnz/",
         "Villagers strictly observe ancient customs and traditions during Tet holidays.",
         "Dân làng tuân thủ nghiêm ngặt các phong tục tập quán cổ truyền trong dịp Tết.",
         ["ancient customs and traditions", "observe customs and traditions"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("architectural style", "n.phr", "phong cách kiến trúc cổ kính đặc trưng", "/ˌɑːkɪˈtektʃərəl staɪl/",
         "The Hue Citadel is famous for its harmonious Nguyen dynasty architectural style.",
         "Kinh thành Huế nổi tiếng với phong cách kiến trúc triều Nguyễn hài hòa.",
         ["distinctive architectural style", "traditional architectural style"],
         "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80"),
        ("oral tradition", "n.phr", "truyền thống truyền khẩu dân gian", "/ˈɔːrəl trəˈdɪʃn/",
         "Folk epic tales have been transmitted across centuries through oral tradition.",
         "Các bản trường ca sử thi đã được lưu truyền qua nhiều thế kỷ bằng truyền thống truyền khẩu.",
         ["rich oral tradition", "pass down by oral tradition"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("indigenous culture", "n.phr", "văn hóa bản địa đặc sắc", "/ɪnˈdɪdʒənəs ˈkʌltʃə(r)/",
         "The festival celebrates the indigenous culture of ethnic minorities in the northern mountains.",
         "Lễ hội tôn vinh nền văn hóa bản địa của đồng bào dân tộc thiểu số vùng núi phía bắc.",
         ["celebrate indigenous culture", "unique indigenous culture"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80")
    ]
}

# Grade 12 missing words to ensure every unit is 55+ words
G12_ADDITIONS = {
    "unit-2-a-multicultural-world": [
        ("multiculturalism", "n", "chủ nghĩa đa văn hóa, chính sách hòa nhập", "/ˌmʌltiˈkʌltʃərəˌlɪzəm/",
         "Many democratic nations embrace multiculturalism as a core civic value.",
         "Nhiều quốc gia dân chủ coi chủ nghĩa đa văn hóa như một giá trị công dân cốt lõi.",
         ["embrace multiculturalism", "advocate multiculturalism"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("cultural integration", "n.phr", "sự hội nhập văn hóa sâu rộng", "/ˈkʌltʃərəl ˌɪntɪˈɡreɪʃn/",
         "Effective language programs facilitate smooth cultural integration for newcomers.",
         "Các chương trình ngôn ngữ hiệu quả giúp người mới đến hội nhập văn hóa dễ dàng hơn.",
         ["smooth cultural integration", "promote cultural integration"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("cultural heritage site", "n.phr", "địa điểm di sản văn hóa thế giới", "/ˈkʌltʃərəl ˈherɪtɪdʒ saɪt/",
         "Hoi An Ancient Town was declared a UNESCO cultural heritage site in 1999.",
         "Phố cổ Hội An được công nhận là di sản văn hóa thế giới của UNESCO vào năm 1999.",
         ["UNESCO cultural heritage site", "visit a cultural heritage site"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("cross-cultural communication", "n.phr", "giao tiếp liên văn hóa hiệu quả", "/ˌkrɒs ˈkʌltʃərəl kəˌmjuːnɪˈkeɪʃn/",
         "Diplomats require rigorous training in cross-cultural communication techniques.",
         "Các nhà ngoại giao cần được đào tạo kỹ lưỡng về kỹ năng giao tiếp liên văn hóa.",
         ["master cross-cultural communication", "effective cross-cultural communication"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("intercultural competence", "n.phr", "năng lực thấu hiểu và thích ứng đa văn hóa", "/ˌɪntəˈkʌltʃərəl ˈkɒmpɪtəns/",
         "International organizations value candidates with proven intercultural competence.",
         "Các tổ chức quốc tế đánh giá cao những ứng viên có năng lực đa văn hóa vững vàng.",
         ["develop intercultural competence", "demonstrate intercultural competence"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("cultural stereotype", "n.phr", "định kiến khuôn mẫu sai lầm về văn hóa", "/ˈkʌltʃərəl ˈsteriətaɪp/",
         "Educational exchanges help dismantle harmful cultural stereotypes among teenagers.",
         "Các chương trình trao đổi giáo dục giúp xóa bỏ định kiến khuôn mẫu văn hóa tiêu cực.",
         ["break down cultural stereotypes", "harmful cultural stereotype"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("folk festival", "n.phr", "lễ hội dân gian truyền thống sôi nổi", "/fəʊk ˈfestɪvl/",
         "Thousands of pilgrims gather annually at the Hung Kings temple folk festival.",
         "Hàng ngàn người hành hương đổ về lễ hội dân gian Đền Hùng hằng năm.",
         ["annual folk festival", "attend a folk festival"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("linguistic barrier", "n.phr", "rào cản ngôn ngữ gây khó khăn giao tiếp", "/lɪŋˈɡwɪstɪk ˈbæriə(r)/",
         "Translating medical leaflets helps overcome linguistic barriers for ethnic patients.",
         "Dịch tờ rơi y tế giúp vượt qua rào cản ngôn ngữ cho bệnh nhân đồng bào thiểu số.",
         ["overcome linguistic barriers", "break down linguistic barriers"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-3-green-living": [
        ("zero waste", "n.phr", "lối sống không rác thải", "/ˌzɪərəʊ ˈweɪst/",
         "Many young households adopt a zero waste lifestyle by composting and avoiding plastics.",
         "Nhiều gia đình trẻ chọn lối sống không rác thải bằng cách ủ phân và không dùng đồ nhựa.",
         ["zero waste lifestyle", "achieve zero waste"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("biodegradable material", "n.phr", "vật liệu tự phân hủy sinh học", "/ˌbaɪəʊdɪˈɡreɪdəbl məˈtɪəriəl/",
         "Scientists developed biodegradable materials made from cassava starch.",
         "Các nhà khoa học phát minh vật liệu tự phân hủy sinh học làm từ tinh bột sắn.",
         ["use biodegradable materials", "switch to biodegradable materials"],
         "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80"),
        ("carbon offset", "n.phr", "chương trình bù đắp khí thải các-bon", "/ˈkɑːbən ˈɒfset/",
         "Airlines encourage passengers to purchase carbon offsets by funding reforestation.",
         "Các hãng hàng không khuyến khích hành khách mua tín chỉ bù đắp khí thải qua việc trồng rừng.",
         ["purchase carbon offsets", "carbon offset scheme"],
         "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=800&q=80"),
        ("energy-efficient appliance", "n.phr", "thiết bị gia dụng tiết kiệm năng lượng", "/ˌenədʒi ɪˈfɪʃnt əˈplaɪəns/",
         "Replacing older air conditioners with energy-efficient appliances lowers utility bills.",
         "Thay máy lạnh cũ bằng các thiết bị tiết kiệm điện giúp giảm tiền điện sinh hoạt.",
         ["install energy-efficient appliances", "eco-friendly appliances"],
         "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80"),
        ("circular economy", "n.phr", "nền kinh tế tuần hoàn tái sử dụng", "/ˌsɜːkjələr ɪˈkɒnəmi/",
         "A circular economy aims to eliminate industrial waste through continuous recycling.",
         "Nền kinh tế tuần hoàn hướng đến loại bỏ rác thải công nghiệp qua tái chế liên tục.",
         ["transition to a circular economy", "circular economy model"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("single-use plastic", "n.phr", "đồ nhựa dùng một lần gây ô nhiễm", "/ˌsɪŋɡl juːs ˈplæstɪk/",
         "The city banned single-use plastic bags and straws in all supermarket chains.",
         "Thành phố cấm túi và ống hút nhựa dùng một lần trong tất cả chuỗi siêu thị.",
         ["ban single-use plastics", "reduce single-use plastics"],
         "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80"),
        ("sustainable agriculture", "n.phr", "nền nông nghiệp canh tác bền vững", "/səˈsteɪnəbl ˈæɡrɪkʌltʃə(r)/",
         "Sustainable agriculture protects fertile soil without chemical pesticide runoff.",
         "Nông nghiệp bền vững bảo vệ độ phì của đất mà không gây ngấm thuốc trừ sâu hóa học.",
         ["practice sustainable agriculture", "methods of sustainable agriculture"],
         "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=800&q=80"),
        ("compostable packaging", "n.phr", "bao bì có thể ủ thành phân hữu cơ", "/kɒmˈpɒstəbl ˈpækɪdʒɪŋ/",
         "Modern food outlets are transitioning to 100% compostable packaging.",
         "Các quán ăn hiện đại đang chuyển sang dùng 100% bao bì có thể ủ phân sinh học.",
         ["certified compostable packaging", "eco-friendly packaging"],
         "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80"),
        ("geothermal energy", "n.phr", "nguồn năng lượng địa nhiệt sạch", "/ˌdʒiːəʊˈθɜːml ˈenədʒi/",
         "Iceland heats over ninety percent of its homes using clean geothermal energy.",
         "Iceland sưởi ấm hơn 90% nhà ở bằng nguồn năng lượng địa nhiệt sạch tự nhiên.",
         ["tap geothermal energy", "harness geothermal energy"],
         "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=800&q=80"),
        ("water conservation", "n.phr", "bảo tồn và tiết kiệm nguồn nước ngọt", "/ˈwɔːtə ˌkɒnsəˈveɪʃn/",
         "Drip irrigation is an ingenious technique for agricultural water conservation.",
         "Tưới nhỏ giọt là kỹ thuật thông minh để tiết kiệm nước trong sản xuất nông nghiệp.",
         ["encourage water conservation", "water conservation measures"],
         "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=800&q=80"),
        ("clean technology", "n.phr", "công nghệ sạch thân thiện môi sinh", "/kliːn tekˈnɒlədʒi/",
         "Investment in clean technology surged after global climate agreements were signed.",
         "Đầu tư vào công nghệ sạch tăng vọt sau khi các hiệp định khí hậu toàn cầu được ký kết.",
         ["invest in clean technology", "advance clean technology"],
         "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80"),
        ("ecological balance", "n.phr", "sự cân bằng sinh thái tự nhiên", "/ˌiːkəˈlɒdʒɪkl ˈbæləns/",
         "Overfishing in coral reefs severely disrupts the delicate ecological balance.",
         "Đánh bắt cá quá mức ở các rạn san hô làm đảo lộn nghiêm trọng sự cân bằng sinh thái.",
         ["maintain ecological balance", "restore ecological balance"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("organic farming", "n.phr", "canh tác nông nghiệp hữu cơ an toàn", "/ɔːˈɡænɪk ˈfɑːmɪŋ/",
         "Consumers gladly pay a premium for vegetables grown through organic farming.",
         "Người tiêu dùng sẵn lòng trả giá cao hơn cho rau củ được trồng theo phương pháp hữu cơ.",
         ["certified organic farming", "principles of organic farming"],
         "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=800&q=80"),
        ("reusable container", "n.phr", "hộp đựng có thể dùng lại nhiều lần", "/ˌriːˈjuːzəbl kənˈteɪnə(r)/",
         "Shoppers bring reusable containers to bulk dry-food stores to reduce packaging.",
         "Khách mua hàng mang theo hộp tái sử dụng tới các cửa hàng thực phẩm để giảm bao bì.",
         ["bring reusable containers", "washable containers"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("greenhouse gas emission", "n.phr", "sự phát thải khí nhà kính gây biến đổi khí hậu", "/ˈɡriːnhaʊs ɡæs ɪˈmɪʃn/",
         "The treaty mandates a fifty percent cut in greenhouse gas emissions by 2030.",
         "Hiệp ước quy định cắt giảm 50% lượng phát thải khí nhà kính trước năm 2030.",
         ["slash greenhouse gas emissions", "monitor greenhouse gas emissions"],
         "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-4-urbanisation": [
        ("urban sprawl", "n.phr", "sự mở rộng đô thị tự phát thiếu quy hoạch", "/ˌɜːbən ˈsprɔːl/",
         "Unchecked urban sprawl consumes fertile rice paddies around metropolitan borders.",
         "Sự mở rộng đô thị thiếu kiểm soát đã nuốt trọn nhiều cánh đồng lúa quanh ngoại ô.",
         ["curb urban sprawl", "consequences of urban sprawl"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("megacity", "n", "siêu đô thị có trên mười triệu dân", "/ˈmeɡəsɪti/",
         "Tokyo and Shanghai are prominent examples of thriving Asian megacities.",
         "Tokyo và Thượng Hải là những ví dụ điển hình của các siêu đô thị phồn vinh tại châu Á.",
         ["rapid growth of megacities", "manage a megacity"],
         "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=800&q=80"),
        ("metropolitan area", "n.phr", "vùng đô thị trung tâm sầm uất", "/ˌmetrəˈpɒlɪtən ˈeəriə/",
         "The Hanoi metropolitan area is home to over eight million industrious residents.",
         "Vùng đô thị Hà Nội là nơi sinh sống của hơn tám triệu cư dân cần cù chăm chỉ.",
         ["expand the metropolitan area", "bustling metropolitan area"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("traffic congestion", "n.phr", "tình trạng tắc nghẽn giao thông giờ cao điểm", "/ˈtræfɪk kənˈdʒestʃən/",
         "Building metro transit lines is the most viable solution to traffic congestion.",
         "Xây dựng các tuyến tàu điện ngầm là giải pháp khả thi nhất cho vấn nạn ùn tắc giao thông.",
         ["ease traffic congestion", "severe traffic congestion"],
         "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80"),
        ("infrastructure development", "n.phr", "phát triển cơ sở hạ tầng giao thông và kỹ thuật", "/ˈɪnfrəstrʌktʃə dɪˈveləpmənt/",
         "The government prioritizes infrastructure development including highways and bridges.",
         "Chính phủ ưu tiên phát triển cơ sở hạ tầng bao gồm mạng lưới đường cao tốc và cầu đường.",
         ["accelerate infrastructure development", "funding for infrastructure development"],
         "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"),
        ("rural-urban migration", "n.phr", "dòng di cư từ nông thôn ra thành thị", "/ˌrʊərəl ˈɜːbən maɪˈɡreɪʃn/",
         "Rural-urban migration provides vital labor for burgeoning manufacturing plants.",
         "Dòng di cư từ nông thôn ra thành thị cung cấp nguồn nhân lực thiết yếu cho các nhà máy sản xuất.",
         ["wave of rural-urban migration", "reasons for rural-urban migration"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("housing shortage", "n.phr", "tình trạng khan hiếm nhà ở giá hợp lý", "/ˈhaʊzɪŋ ˈʃɔːtɪdʒ/",
         "Subsidized social apartments are being constructed to alleviate the housing shortage.",
         "Nhiều căn hộ nhà ở xã hội đang được xây dựng nhằm giải quyết tình trạng thiếu thốn nhà ở.",
         ["acute housing shortage", "address the housing shortage"],
         "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"),
        ("slum clearance", "n.phr", "công tác giải tỏa các khu ổ chuột tồi tàn", "/slʌm ˈklɪərəns/",
         "Humane slum clearance programs must offer displaced families adequate resettlement.",
         "Các chương trình giải tỏa khu ổ chuột nhân văn cần mang lại nơi tái định cư thỏa đáng.",
         ["undertake slum clearance", "urban slum clearance"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("public transit system", "n.phr", "hệ thống vận tải hành khách công cộng", "/ˌpʌblɪk ˈtrænzɪt ˈsɪstəm/",
         "An integrated public transit system connects bus routes with electric elevated trains.",
         "Hệ thống vận tải công cộng kết hợp các tuyến xe buýt với mạng lưới tàu điện trên cao.",
         ["upgrade public transit systems", "reliable public transit"],
         "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80"),
        ("smart urbanization", "n.phr", "đô thị hóa thông minh định hướng tương lai", "/smɑːt ˌɜːbənaɪˈzeɪʃn/",
         "Smart urbanization integrates sensors to optimize energy consumption and waste pickup.",
         "Đô thị hóa thông minh tích hợp cảm biến để tối ưu hóa việc dùng năng lượng và thu gom rác.",
         ["foster smart urbanization", "strategy for smart urbanization"],
         "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=800&q=80"),
        ("overcrowded neighborhood", "n.phr", "khu dân cư chật chội đông đúc", "/ˌəʊvəˈkraʊdɪd ˈneɪbəhʊd/",
         "Fire safety regulations are strictly enforced in historically overcrowded neighborhoods.",
         "Quy chuẩn phòng cháy chữa cháy được siết chặt tại các khu dân cư đông đúc lâu đời.",
         ["densely overcrowded neighborhood", "live in an overcrowded neighborhood"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("sanitation facility", "n.phr", "công trình vệ sinh công cộng đạt chuẩn", "/ˌsænɪˈteɪʃn fəˈsɪləti/",
         "Upgrading city sanitation facilities prevents waterborne epidemics during monsoon season.",
         "Nâng cấp công trình vệ sinh đô thị giúp ngăn ngừa các dịch bệnh lây qua nguồn nước vào mùa mưa.",
         ["improve sanitation facilities", "modern sanitation facilities"],
         "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"),
        ("city dweller", "n.phr", "cư dân thành thị", "/ˈsɪti ˈdwelə(r)/",
         "City dwellers often crave weekend escapes to calm countryside orchards.",
         "Cư dân đô thị thường mong muốn những chuyến nghỉ ngơi cuối tuần về các vườn cây miệt vườn.",
         ["urban city dwellers", "lifestyle of city dwellers"],
         "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80"),
        ("suburban commuter", "n.phr", "người đi làm từ ngoại ô vào nội đô", "/səˈbɜːbən kəˈmjuːtə(r)/",
         "Thousands of suburban commuters board express trains at sunrise every weekday.",
         "Hàng ngàn người đi làm từ ngoại ô lên các chuyến tàu hỏa tốc hành lúc bình minh mỗi ngày.",
         ["daily suburban commuter", "rush of suburban commuters"],
         "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80"),
        ("industrial zone", "n.phr", "khu chế xuất công nghiệp tập trung", "/ɪnˈdʌstriəl zəʊn/",
         "Strict environmental filters are installed in smokestacks across the industrial zone.",
         "Bộ lọc khí thải môi trường nghiêm ngặt được lắp đặt trên ống khói trong khu công nghiệp.",
         ["high-tech industrial zone", "relocate to an industrial zone"],
         "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"),
        ("living standard", "n.phr", "mức sống và tiện nghi sinh hoạt", "/ˈlɪvɪŋ ˈstændəd/",
         "Access to clean tap water and high-speed broadband has raised the general living standard.",
         "Nước máy sạch và mạng internet tốc độ cao đã nâng cao mức sống chung của người dân.",
         ["elevate living standards", "high living standard"],
         "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-5-the-world-of-work": [
        ("job market demand", "n.phr", "nhu cầu tuyển dụng của thị trường việc làm", "/dʒɒb ˈmɑːkɪt dɪˈmɑːnd/",
         "Universities adjust their training curricula to match actual job market demand.",
         "Các trường đại học điều chỉnh giáo trình đào tạo cho phù hợp nhu cầu thực tế của thị trường.",
         ["meet job market demand", "shift in job market demand"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("probationary period", "n.phr", "thời gian thử việc ban đầu", "/prəˈbeɪʃənri ˈpɪəriəd/",
         "She impressed her team leads during her two-month probationary period.",
         "Cô ấy đã gây ấn tượng xuất sắc với lãnh đạo nhóm trong hai tháng thử việc.",
         ["complete the probationary period", "standard probationary period"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("fringe benefits", "n.phr", "phúc lợi và đãi ngộ bổ sung", "/ˈfrɪndʒ ˈbenɪfɪts/",
         "Attractive fringe benefits like health insurance and gym memberships boost employee morale.",
         "Các chế độ đãi ngộ hấp dẫn như bảo hiểm sức khỏe và thẻ tập gym giúp nâng cao tinh thần làm việc.",
         ["generous fringe benefits", "offer fringe benefits"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("performance appraisal", "n.phr", "buổi đánh giá hiệu quả công việc", "/pəˈfɔːməns əˈpreɪzl/",
         "Annual performance appraisals determine salary increments and promotions.",
         "Buổi đánh giá năng lực hằng năm là căn cứ để quyết định tăng lương và cất nhắc thăng chức.",
         ["conduct a performance appraisal", "rigorous performance appraisal"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("telecommuting", "n", "làm việc từ xa qua mạng internet", "/ˌtelikəˈmjuːtɪŋ/",
         "Telecommuting allows software engineers to collaborate seamlessly across time zones.",
         "Làm việc từ xa cho phép các kỹ sư phần mềm phối hợp nhịp nhàng xuyên múi giờ.",
         ["adopt telecommuting", "flexibility of telecommuting"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("work-life balance", "n.phr", "cân bằng giữa sự nghiệp và cuộc sống", "/ˌwɜːk laɪf ˈbæləns/",
         "Forward-thinking corporations prioritize healthy work-life balance for all staff.",
         "Các tập đoàn có tầm nhìn tiến bộ luôn coi trọng việc cân bằng hài hòa giữa công việc và đời sống.",
         ["maintain work-life balance", "achieve work-life balance"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("career advancement", "n.phr", "sự thăng tiến trong nấc thang sự nghiệp", "/kəˈrɪər ədˈvɑːnsmənt/",
         "Continuous skill enhancement is indispensable for steady career advancement.",
         "Liên tục nâng cao kỹ năng là điều kiện không thể thiếu để thăng tiến nghề nghiệp vững chắc.",
         ["pathways to career advancement", "strive for career advancement"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("job satisfaction", "n.phr", "sự thỏa mãn và gắn bó với công việc", "/dʒɒb ˌsætɪsˈfækʃn/",
         "Meaningful tasks and supportive colleagues contribute immensely to job satisfaction.",
         "Công việc có ý nghĩa và đồng nghiệp tận tình đóng góp rất lớn vào sự hài lòng với nghề nghiệp.",
         ["high job satisfaction", "improve job satisfaction"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("professional networking", "n.phr", "xây dựng mối quan hệ công việc chuyên nghiệp", "/prəˈfeʃənl ˈnetwɜːkɪŋ/",
         "Attending industry seminars is a great avenue for professional networking.",
         "Tham dự các hội thảo chuyên ngành là cơ hội tốt để mở rộng các mối quan hệ đồng nghiệp.",
         ["engage in professional networking", "power of professional networking"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("severance package", "n.phr", "khoản trợ cấp thôi việc hợp pháp", "/ˈsevərəns ˈpækɪdʒ/",
         "Employees impacted by the restructuring received a very fair severance package.",
         "Các nhân viên chịu ảnh hưởng do tái cơ cấu được nhận khoản trợ cấp thôi việc rất thỏa đáng.",
         ["negotiate a severance package", "entitled to a severance package"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("vocational training", "n.phr", "đào tạo nghề thực hành chuyên môn", "/vəʊˈkeɪʃənl ˈtreɪnɪŋ/",
         "High-quality vocational training equips graduates with immediate practical mastery.",
         "Đào tạo nghề chất lượng cao trang bị cho học viên kỹ năng thực hành vững vàng ngay khi ra trường.",
         ["enroll in vocational training", "vocational training center"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("entry-level position", "n.phr", "vị trí công việc khởi điểm cho người mới", "/ˈentri levl pəˈzɪʃn/",
         "Fresh university graduates usually start in an entry-level position to learn routines.",
         "Sinh viên mới tốt nghiệp thường bắt đầu từ vị trí khởi điểm để học hỏi quy trình thực tế.",
         ["apply for an entry-level position", "entry-level position requirements"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("corporate culture", "n.phr", "bản sắc văn hóa doanh nghiệp", "/ˈkɔːpərət ˈkʌltʃə(r)/",
         "Transparency, innovation, and mutual empathy define our corporate culture.",
         "Sự minh bạch, sáng tạo và thấu hiểu lẫn nhau tạo nên nét văn hóa đặc trưng của công ty chúng tôi.",
         ["strong corporate culture", "fit the corporate culture"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("annual leave entitlement", "n.phr", "chế độ nghỉ phép năm được hưởng", "/ˌænjuəl liːv ɪnˈtaɪtlmənt/",
         "Every full-time staff member enjoys a statutory annual leave entitlement of fourteen days.",
         "Mỗi nhân viên chính thức được hưởng quyền lợi nghỉ phép năm 14 ngày theo đúng luật định.",
         ["statutory annual leave entitlement", "generous leave entitlement"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("human resource management", "n.phr", "quản trị nguồn nhân lực", "/ˌhjuːmən rɪˈsɔːs ˈmænɪdʒmənt/",
         "Modern human resource management emphasizes continuous employee coaching and retention.",
         "Quản trị nhân lực hiện đại tập trung vào việc đào tạo kèm cặp và giữ chân người tài.",
         ["strategic human resource management", "principles of human resources"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("work ethic", "n.phr", "đạo đức nghề nghiệp và tinh thần trách nhiệm", "/wɜːk ˈeθɪk/",
         "Her impeccable work ethic and punctuality earned the admiration of all partners.",
         "Đạo đức làm việc chỉn chu và tính đúng giờ của cô đã nhận được sự nể phục của các đối tác.",
         ["strong work ethic", "admirable work ethic"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-6-artificial-intelligence": [
        ("machine learning algorithm", "n.phr", "thuật toán máy học tự động", "/məˈʃiːn ˈlɜːnɪŋ ˈælɡərɪðəm/",
         "Machine learning algorithms identify diagnostic anomalies in lung CT scans.",
         "Các thuật toán máy học phát hiện những bất thường chẩn đoán trên phim chụp CT phổi.",
         ["train a machine learning algorithm", "complex algorithms"],
         "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80"),
        ("deep neural network", "n.phr", "mạng nơ-ron học sâu nhiều tầng", "/diːp ˈnjʊərəl ˈnetwɜːk/",
         "Deep neural networks mimic the human brain to decode natural human speech.",
         "Mạng nơ-ron sâu mô phỏng não bộ người để giải mã ngôn ngữ nói tự nhiên.",
         ["architectures of deep neural networks", "train deep neural networks"],
         "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80"),
        ("natural language processing", "n.phr", "xử lý ngôn ngữ tự nhiên thông minh", "/ˈnætʃrəl ˈlæŋɡwɪdʒ ˈprəʊsesɪŋ/",
         "Natural language processing enables AI chat assistants to converse fluently.",
         "Công nghệ xử lý ngôn ngữ tự nhiên giúp trợ lý AI trò chuyện mạch lạc với người dùng.",
         ["advances in natural language processing", "NLP models"],
         "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80"),
        ("computer vision", "n.phr", "thị giác máy tính nhận biết hình ảnh", "/kəmˈpjuːtə ˈvɪʒn/",
         "Computer vision lets automated drones survey farmland and spot insect infestations.",
         "Thị giác máy tính giúp thiết bị bay không người lái khảo sát ruộng đồng và phát hiện sâu bệnh.",
         ["applications of computer vision", "computer vision system"],
         "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80"),
        ("autonomous vehicle", "n.phr", "phương tiện xe tự hành không người lái", "/ɔːˈtɒnəməs ˈviːəkl/",
         "Autonomous vehicles utilize lidar and radar to navigate busy urban intersections.",
         "Xe tự hành sử dụng lidar và radar để điều hướng an toàn qua các giao lộ đô thị đông đúc.",
         ["test autonomous vehicles", "fleet of autonomous vehicles"],
         "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80"),
        ("generative model", "n.phr", "mô hình trí tuệ nhân tạo tạo sinh", "/ˈdʒenərətɪv ˈmɒdl/",
         "Generative models can compose original classical melodies and design graphics.",
         "Các mô hình AI tạo sinh có thể sáng tác giai điệu cổ điển và thiết kế đồ họa độc đáo.",
         ["leverage generative models", "state-of-the-art generative model"],
         "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80"),
        ("algorithmic bias", "n.phr", "thiên vị thuật toán do dữ liệu huấn luyện", "/ˌælɡəˈrɪðmɪk ˈbaɪəs/",
         "Data scientists work diligently to eliminate algorithmic bias in credit scoring systems.",
         "Các chuyên gia dữ liệu nỗ lực loại trừ thiên kiến thuật toán trong chấm điểm tín dụng.",
         ["mitigate algorithmic bias", "detect algorithmic bias"],
         "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80"),
        ("facial recognition", "n.phr", "công nghệ nhận dạng khuôn mặt", "/ˈfeɪʃl ˌrekəɡˈnɪʃn/",
         "Airport customs checkpoints rely on facial recognition to verify passport holders.",
         "Cửa khẩu sân bay sử dụng nhận diện gương mặt để xác thực hành khách mang hộ chiếu.",
         ["deploy facial recognition", "facial recognition scanner"],
         "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80"),
        ("predictive analytics", "n.phr", "phân tích dữ liệu dự báo tương lai", "/prɪˈdɪktɪv ˌænəˈlɪtɪks/",
         "Retail giants employ predictive analytics to anticipate seasonal shopping surges.",
         "Các hãng bán lẻ lớn dùng phân tích dự báo để đón đầu các đợt cao điểm mua sắm.",
         ["utilize predictive analytics", "predictive analytics tool"],
         "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80"),
        ("automated decision-making", "n.phr", "ra quyết định hoàn toàn tự động bằng máy", "/ˈɔːtəmeɪtɪd dɪˈsɪʒn ˈmeɪkɪŋ/",
         "Regulations require human oversight in automated decision-making for loan approvals.",
         "Quy định pháp lý đòi hỏi phải có con người giám sát khi duyệt vay vốn bằng hệ thống tự động.",
         ["ethics of automated decision-making", "automated decision-making algorithms"],
         "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80"),
        ("data privacy regulation", "n.phr", "quy chuẩn bảo vệ tính riêng tư của dữ liệu", "/ˈdeɪtə ˈprɪvəsi ˌreɡjuˈleɪʃn/",
         "Tech firms must comply strictly with data privacy regulations such as the GDPR.",
         "Các công ty công nghệ phải tuân thủ nghiêm ngặt các quy định về quyền riêng tư dữ liệu.",
         ["enforce data privacy regulations", "comply with data privacy regulations"],
         "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80"),
        ("human-AI collaboration", "n.phr", "sự hợp tác hiệu quả giữa con người và AI", "/ˌhjuːmən eɪ ˈaɪ kəˌlæbəˈreɪʃn/",
         "The future of design lies in synergistic human-AI collaboration rather than total replacement.",
         "Tương lai ngành thiết kế nằm ở sự hợp tác giữa người và AI thay vì thay thế hoàn toàn.",
         ["effective human-AI collaboration", "synergy in human-AI collaboration"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("expert system", "n.phr", "hệ thống chuyên gia giải quyết bài toán phức tạp", "/ˈekspɜːt ˈsɪstəm/",
         "An expert system incorporates rule-based knowledge to assist petroleum prospecting.",
         "Hệ chuyên gia kết hợp kho kiến thức dựa trên luật để hỗ trợ thăm dò dầu khí.",
         ["consult an expert system", "design an expert system"],
         "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80"),
        ("reinforcement learning", "n.phr", "phương pháp học máy tăng cường qua khen thưởng", "/ˌriːɪnˈfɔːsmənt ˈlɜːnɪŋ/",
         "Chess-playing algorithms achieve superhuman prowess through reinforcement learning.",
         "Thuật toán chơi cờ vua đạt trình độ vượt bậc nhờ phương pháp học tăng cường tự chơi.",
         ["master reinforcement learning", "reinforcement learning policy"],
         "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80"),
        ("data mining technique", "n.phr", "kỹ thuật khai phá dữ liệu quy mô lớn", "/ˈdeɪtə ˈmaɪnɪŋ tekˈniːk/",
         "Researchers apply data mining techniques to uncover previously unknown genomic links.",
         "Các nhà nghiên cứu áp dụng kỹ thuật khai phá dữ liệu để tìm ra các liên kết gen chưa từng biết.",
         ["advanced data mining techniques", "execute data mining techniques"],
         "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80"),
        ("hallucination risk", "n.phr", "nguy cơ đưa ra thông tin bịa đặt vô căn cứ", "/həˌluːsɪˈneɪʃn rɪsk/",
         "Engineers implement retrieval-augmented generation to curb hallucination risks.",
         "Các kỹ sư áp dụng phương pháp truy xuất tăng cường để kiểm soát rủi ro AI bịa thông tin.",
         ["curb hallucination risk", "minimize hallucination risk"],
         "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80"),
        ("sentient capability", "n.phr", "khả năng nhận thức và cảm xúc tự thân", "/ˈsenʃnt ˌkeɪpəˈbɪləti/",
         "Philosophers debate whether synthetic neural nodes could ever attain sentient capability.",
         "Các triết gia tranh luận liệu mạng nơ-ron nhân tạo có thể đạt tới khả năng tự tri giác hay không.",
         ["possess sentient capability", "debate sentient capability"],
         "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-7-the-world-of-mass-media": [
        ("investigative journalism", "n.phr", "nghề báo chí điều tra phanh phui sự thật", "/ɪnˌvestɪɡətɪv ˈdʒɜːnəlɪzəm/",
         "A prestigious award honored the team for courageous investigative journalism.",
         "Giải thưởng danh giá tôn vinh nhóm phóng viên vì sự dũng cảm trong tác nghiệp điều tra.",
         ["triumph of investigative journalism", "pursue investigative journalism"],
         "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80"),
        ("broadcast journalism", "n.phr", "ngành báo chí truyền hình và phát thanh", "/ˈbrɔːdkɑːst ˈdʒɜːnəlɪzəm/",
         "She majored in broadcast journalism and currently anchors the evening news bulletin.",
         "Cô ấy tốt nghiệp ngành báo chí truyền hình và hiện đang dẫn bản tin thời sự buổi tối.",
         ["career in broadcast journalism", "standards of broadcast journalism"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("media censorship", "n.phr", "sự kiểm duyệt nội dung trên phương tiện truyền thông", "/ˈmiːdiə ˈsensəʃɪp/",
         "Civil liberties watchdogs monitor instances of unwarranted media censorship.",
         "Các tổ chức bảo vệ quyền công dân theo dõi sát sao những biểu hiện kiểm duyệt truyền thông.",
         ["subject to media censorship", "oppose media censorship"],
         "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80"),
        ("press freedom", "n.phr", "quyền tự do báo chí hợp pháp", "/pres ˈfriːdəm/",
         "A thriving society requires robust press freedom to hold institutions accountable.",
         "Một xã hội phồn vinh cần quyền tự do báo chí vững vàng để đảm bảo tính giải trình minh bạch.",
         ["defend press freedom", "index of press freedom"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("public opinion poll", "n.phr", "cuộc thăm dò dư luận và ý kiến công chúng", "/ˌpʌblɪk əˈpɪnjən pəʊl/",
         "The latest public opinion poll reveals overwhelming backing for environmental laws.",
         "Cuộc thăm dò dư luận mới nhất cho thấy sự ủng hộ áp đảo đối với luật môi trường.",
         ["conduct a public opinion poll", "results of the public opinion poll"],
         "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80"),
        ("sensational headline", "n.phr", "tiêu đề giật gân thu hút sự chú ý", "/senˈseɪʃənl ˈhedlaɪn/",
         "Tabloids frequently rely on sensational headlines to entice casual readers.",
         "Các tờ báo lá cải thường dựa vào những tiêu đề giật gân để lôi kéo người đọc lướt qua.",
         ["misleading sensational headlines", "write sensational headlines"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("citizen journalism", "n.phr", "báo chí công dân qua video người dân quay", "/ˌsɪtɪzn ˈdʒɜːnəlɪzəm/",
         "Smartphone livestreams of natural disasters are compelling examples of citizen journalism.",
         "Các video trực tiếp về thiên tai từ điện thoại thông minh là minh chứng cho báo chí công dân.",
         ["rise of citizen journalism", "empower citizen journalism"],
         "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80"),
        ("digital disinformation", "n.phr", "thông tin sai lệch cố ý trên môi trường số", "/ˈdɪdʒɪtl ˌdɪsɪnfəˈmeɪʃn/",
         "Tech platforms cooperate with universities to detect and neutralize digital disinformation.",
         "Các nền tảng công nghệ hợp tác cùng trường đại học để ngăn chặn thông tin bịa đặt trực tuyến.",
         ["combat digital disinformation", "spread of digital disinformation"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("advertising revenue", "n.phr", "nguồn thu từ quảng cáo truyền thông", "/ˈædvətaɪzɪŋ ˈrevənjuː/",
         "Print publications suffered a steep decline in traditional advertising revenue.",
         "Báo in truyền thống sụt giảm mạnh về doanh thu quảng cáo khi độc giả chuyển sang mạng.",
         ["boost advertising revenue", "rely on advertising revenue"],
         "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80"),
        ("social media influencer", "n.phr", "người có sức ảnh hưởng trên mạng xã hội", "/ˌsəʊʃl ˈmiːdiə ˈɪnfluənsə(r)/",
         "The fashion brand partnered with a prominent social media influencer to launch the line.",
         "Nhãn hàng thời trang bắt tay với một người có sức ảnh hưởng lớn trên mạng để ra mắt bộ sưu tập.",
         ["popular social media influencer", "reach of social media influencers"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("prime-time broadcast", "n.phr", "chương trình phát sóng giờ vàng", "/ˌpraɪm ˈtaɪm ˈbrɔːdkɑːst/",
         "The presidential debate attracted thirty million viewers during its prime-time broadcast.",
         "Buổi tranh luận tổng thống thu hút ba mươi triệu khán giả trong khung giờ phát sóng vàng.",
         ["schedule a prime-time broadcast", "tune in to the prime-time broadcast"],
         "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80"),
        ("media literacy skill", "n.phr", "kỹ năng phân tích chọn lọc thông tin", "/ˈmiːdiə ˈlɪtərəsi skɪl/",
         "Schools teach media literacy skills to help teenagers evaluate online claims critically.",
         "Trường học dạy kỹ năng phân tích truyền thông để học sinh đánh giá thông tin mạng có phê phán.",
         ["sharpen media literacy skills", "essential media literacy skills"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("fact-checking website", "n.phr", "trang web kiểm chứng độ chính xác thông tin", "/ˈfækt tʃekɪŋ ˈwebsaɪt/",
         "Always cross-reference sensational rumors with a certified fact-checking website.",
         "Luôn đối chiếu các tin đồn giật gân với trang web kiểm chứng sự thật đáng tin cậy.",
         ["consult a fact-checking website", "independent fact-checking website"],
         "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80"),
        ("editorial independence", "n.phr", "tính độc lập trong hoạt động biên tập", "/ˌedɪˈtɔːriəl ˌɪndɪˈpendəns/",
         "The newsroom protects its editorial independence from commercial sponsor pressure.",
         "Tòa soạn bảo vệ tính độc lập biên tập trước sức ép từ các nhà tài trợ thương mại.",
         ["safeguard editorial independence", "cherish editorial independence"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("target audience", "n.phr", "khán thính giả và độc giả mục tiêu", "/ˈtɑːɡɪt ˈɔːdiəns/",
         "The educational podcast caters specifically to a target audience of high school seniors.",
         "Kênh podcast giáo dục này hướng đến đối tượng khán thính giả mục tiêu là học sinh cuối cấp 3.",
         ["reach the target audience", "engage the target audience"],
         "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80"),
        ("viral marketing campaign", "n.phr", "chiến dịch tiếp thị lan tỏa như virus", "/ˈvaɪrəl ˈmɑːkɪtɪŋ kæmˈpeɪn/",
         "Their witty short video sparked a massive viral marketing campaign with millions of shares.",
         "Video ngắn hóm hỉnh đã tạo nên chiến dịch tiếp thị lan truyền rộng khắp với hàng triệu lượt chia sẻ.",
         ["launch a viral marketing campaign", "success of viral marketing campaign"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("breaking news bulletin", "n.phr", "bản tin khẩn cấp phát sóng đột xuất", "/ˌbreɪkɪŋ ˈnjuːz ˈbʊlətɪn/",
         "The regular drama was interrupted by a breaking news bulletin regarding the typhoon.",
         "Bộ phim truyền hình đang chiếu bị gián đoạn bởi bản tin khẩn cấp về cơn bão lớn.",
         ["flash a breaking news bulletin", "urgent breaking news bulletin"],
         "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-8-wildlife-conservation": [
        ("critically endangered species", "n.phr", "loài đứng trước nguy cơ tuyệt chủng cực kỳ cao", "/ˌkrɪtɪkli ɪnˈdeɪndʒəd ˈspiːʃiːz/",
         "The Javan rhinoceros is officially classified as a critically endangered species.",
         "Tê giác Java được xếp loại chính thức là loài có nguy cơ tuyệt chủng cực kỳ nghiêm trọng.",
         ["protect critically endangered species", "habitat of endangered species"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("poaching penalty", "n.phr", "hình phạt nghiêm khắc đối với tội săn trộm", "/ˈpəʊtʃɪŋ ˈpenəlti/",
         "Stricter poaching penalties with long prison sentences have deterred timber and game thieves.",
         "Các chế tài xử phạt săn trộm nghiêm khắc kèm án tù dài hạn đã răn đe kẻ trộm gỗ và thú rừng.",
         ["impose poaching penalties", "stiff poaching penalties"],
         "https://images.unsplash.com/photo-1574063413132-355dbfd83e23?auto=format&fit=crop&w=800&q=80"),
        ("biodiversity hotspot", "n.phr", "điểm nóng đa dạng sinh học quý giá", "/ˌbaɪəʊdaɪˈvɜːsəti ˈhɒtspɒt/",
         "Vietnam's Annamite Range is celebrated as an internationally vital biodiversity hotspot.",
         "Dãy Trường Sơn của Việt Nam được ghi nhận là một điểm nóng đa dạng sinh học tầm cỡ quốc tế.",
         ["conserve biodiversity hotspots", "vibrant biodiversity hotspot"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("natural habitat restoration", "n.phr", "khôi phục môi trường sống tự nhiên hoang dã", "/ˈnætʃrəl ˈhæbɪtæt ˌrestəˈreɪʃn/",
         "Volunteers planted mangrove seedlings as part of a coastal natural habitat restoration drive.",
         "Các tình nguyện viên trồng cây đước giống như một phần chiến dịch khôi phục sinh cảnh ngập mặn.",
         ["engage in natural habitat restoration", "funds for habitat restoration"],
         "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80"),
        ("captive breeding program", "n.phr", "chương trình nhân giống bảo tồn trong môi trường nuôi nhốt", "/ˌkæptɪv ˈbriːdɪŋ ˈprəʊɡræm/",
         "The national zoo runs a successful captive breeding program for endangered pangolins.",
         "Vườn thú quốc gia vận hành thành công chương trình nhân giống nuôi nhốt cho loài tê tê quý hiếm.",
         ["support captive breeding programs", "success of captive breeding programs"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("wildlife corridor", "n.phr", "hành lang an toàn cho động vật hoang dã di chuyển", "/ˈwaɪldlaɪf ˈkɒrɪdɔː(r)/",
         "Constructing overpass bridges as wildlife corridors prevents highway collisions with deer.",
         "Xây cầu vượt làm hành lang cho thú hoang giúp ngăn va chạm giao thông nguy hiểm với hươu nai.",
         ["establish wildlife corridors", "safe wildlife corridor"],
         "https://images.unsplash.com/photo-1574063413132-355dbfd83e23?auto=format&fit=crop&w=800&q=80"),
        ("game reserve", "n.phr", "khu bảo tồn thiên nhiên nghiêm ngặt", "/ɡeɪm rɪˈzɜːv/",
         "Armed rangers patrol the expansive game reserve to protect elephants from poachers.",
         "Kiểm lâm có vũ trang tuần tra khu bảo tồn thiên nhiên rộng lớn để che chở đàn voi khỏi kẻ săn trộm.",
         ["patrol the game reserve", "safari in a game reserve"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("marine protected area", "n.phr", "khu bảo tồn biển sinh thái", "/məˈriːn prəˈtektɪd ˈeəriə/",
         "Cu Lao Cham is an internationally recognized marine protected area with pristine reefs.",
         "Cù Lao Chàm là khu bảo tồn biển được công nhận quốc tế với các rạn san hô nguyên sơ tuyệt đẹp.",
         ["designate a marine protected area", "conserve marine protected areas"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("illegal wildlife trafficking", "n.phr", "nạn buôn bán động vật hoang dã trái phép", "/ɪˈliːɡl ˈwaɪldlaɪf ˈtræfɪkɪŋ/",
         "Customs officers cracked down on an international syndicate for illegal wildlife trafficking.",
         "Lực lượng hải quan đã triệt phá một đường dây quốc tế buôn bán động vật hoang dã trái phép.",
         ["eradicate illegal wildlife trafficking", "combat wildlife trafficking"],
         "https://images.unsplash.com/photo-1574063413132-355dbfd83e23?auto=format&fit=crop&w=800&q=80"),
        ("ecological footprint", "n.phr", "dấu chân sinh thái tác động lên tài nguyên thiên nhiên", "/ˌiːkəˈlɒdʒɪkl ˈfʊtprɪnt/",
         "Consumers strive to shrink their ecological footprint by choosing locally sourced produce.",
         "Người tiêu dùng cố gắng thu hẹp dấu chân sinh thái bằng việc mua sắm nông sản địa phương.",
         ["minimize ecological footprint", "measure ecological footprint"],
         "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80"),
        ("extinction threat", "n.phr", "mối đe dọa biến mất vĩnh viễn trên hành tinh", "/ɪkˈstɪŋkʃn θret/",
         "Habitat fragmentation poses the single greatest extinction threat to big cats.",
         "Phân mảnh môi trường sống là mối đe dọa tuyệt chủng lớn nhất đối với các loài thú họ mèo lớn.",
         ["face an extinction threat", "looming extinction threat"],
         "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80"),
        ("endemic flora and fauna", "n.phr", "hệ động thực vật đặc hữu riêng của vùng miền", "/enˈdemɪk ˈflɔːrə ənd ˈfɔːnə/",
         "Madagascar is renowned for its remarkable richness in endemic flora and fauna.",
         "Madagascar nổi tiếng khắp thế giới bởi sự trù phú của hệ động thực vật đặc hữu độc nhất vô nhị.",
         ["richness of endemic flora and fauna", "protect endemic flora and fauna"],
         "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80"),
        ("rainforest deforestation", "n.phr", "nạn chặt phá rừng nhiệt đới bừa bãi", "/ˈreɪnfɒrɪst diːˌfɒrɪˈsteɪʃn/",
         "Rainforest deforestation drastically accelerates global warming and soil erosion.",
         "Nạn tàn phá rừng mưa nhiệt đới làm gia tăng tốc độ nóng lên toàn cầu và xói mòn đất đai.",
         ["halt rainforest deforestation", "consequences of deforestation"],
         "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80"),
        ("reintroduction into the wild", "n.phr", "tái thả động vật được cứu hộ về với tự nhiên", "/ˌriːɪntrəˈdʌkʃn ˈɪntə ðə waɪld/",
         "Rescued moon bears undergo behavioral rehabilitation before reintroduction into the wild.",
         "Gấu ngựa được giải cứu sẽ trải qua phục hồi tập tính trước khi được tái thả về với tự nhiên.",
         ["plan reintroduction into the wild", "successful reintroduction"],
         "https://images.unsplash.com/photo-1574063413132-355dbfd83e23?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-9-career-paths": [
        ("vocational qualification", "n.phr", "chứng chỉ và văn bằng nghề nghiệp thực hành", "/vəʊˈkeɪʃənl ˌkwɒlɪfɪˈkeɪʃn/",
         "Earning a recognized vocational qualification guarantees quick job placement in technical trades.",
         "Sở hữu chứng chỉ nghề được công nhận giúp đảm bảo nhanh chóng có việc làm trong ngành kỹ thuật.",
         ["gain vocational qualifications", "recognized vocational qualification"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("transferable skills", "n.phr", "kỹ năng có thể vận dụng linh hoạt đa ngành nghề", "/trænsˈfɜːrəbl skɪlz/",
         "Critical thinking and teamwork are valuable transferable skills sought by every employer.",
         "Tư duy phản biện và làm việc nhóm là những kỹ năng linh hoạt quý báu mà mọi nhà tuyển dụng tìm kiếm.",
         ["develop transferable skills", "showcase transferable skills"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("internship opportunity", "n.phr", "cơ hội thực tập cọ xát kinh nghiệm thực tế", "/ˈɪntɜːnʃɪp ˌɒpəˈtjuːnəti/",
         "The tech firm offers paid internship opportunities to outstanding third-year undergraduates.",
         "Công ty công nghệ dành các cơ hội thực tập có lương cho sinh viên năm ba xuất sắc.",
         ["secure an internship opportunity", "valuable internship opportunities"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("entrepreneurial ambition", "n.phr", "khát vọng và chí hướng dấn thân khởi nghiệp", "/ˌɒntrəprəˈnɜːriəl æmˈbɪʃn/",
         "Incubators provide seed funding to help students realize their entrepreneurial ambitions.",
         "Vườn ươm cung cấp vốn mồi để giúp các bạn trẻ hiện thực hóa khát vọng khởi nghiệp của mình.",
         ["pursue entrepreneurial ambitions", "fuel entrepreneurial ambitions"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("career counselor", "n.phr", "chuyên viên tư vấn định hướng chọn nghề", "/kəˈrɪə ˈkaʊnsələ(r)/",
         "A career counselor helps high school students choose college majors matching their passions.",
         "Chuyên viên hướng nghiệp giúp học sinh cấp 3 chọn ngành học đại học đúng đam mê sở thích.",
         ["consult a career counselor", "advice from a career counselor"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("job shadowing experience", "n.phr", "trải nghiệm đi theo học việc và quan sát thực tế", "/dʒɒb ˈʃædəʊɪŋ ɪkˈspɪəriəns/",
         "Job shadowing experiences give learners clear insight into the daily life of an architect.",
         "Trải nghiệm theo chân người đi làm giúp học sinh hiểu rõ công việc thường nhật của kiến trúc sư.",
         ["participate in job shadowing", "rewarding job shadowing experience"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("professional mentorship", "n.phr", "sự kèm cặp hướng dẫn từ cố vấn dày dặn", "/prəˈfeʃənl ˈmentɔːʃɪp/",
         "Young designers flourish under the caring guidance of professional mentorship.",
         "Các nhà thiết kế trẻ tiến bộ vượt bậc dưới sự dìu dắt tận tâm của cố vấn nghề nghiệp.",
         ["benefit from professional mentorship", "seek professional mentorship"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("resume refinement", "n.phr", "trau chuốt và hoàn thiện hồ sơ xin việc", "/ˈrezjuːmeɪ rɪˈfaɪnmənt/",
         "Careful resume refinement highlights measurable accomplishments with clear data.",
         "Trau chuốt CV cẩn thận giúp làm nổi bật các thành tích có thể đo lường bằng số liệu cụ thể.",
         ["undergo resume refinement", "tips for resume refinement"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("career transition", "n.phr", "bước ngoặt chuyển đổi định hướng sự nghiệp", "/kəˈrɪə trænˈzɪʃn/",
         "Mid-career transitions require re-skilling and genuine adaptability in digital tools.",
         "Chuyển đổi nghề nghiệp giữa chừng đòi hỏi phải học kỹ năng mới và thích ứng công cụ số.",
         ["navigate a career transition", "successful career transition"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("salary negotiation", "n.phr", "kỹ năng đàm phán mức lương đãi ngộ", "/ˈsæləri nɪˌɡəʊʃiˈeɪʃn/",
         "Effective salary negotiation begins with thorough market research on industry benchmarks.",
         "Kỹ năng đàm phán lương hiệu quả bắt đầu bằng việc tìm hiểu kỹ mặt bằng chung của thị trường.",
         ["master salary negotiation", "tactics in salary negotiation"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("apprenticeship contract", "n.phr", "hợp đồng học nghề vừa học vừa nhận thù lao", "/əˈprentɪsʃɪp ˈkɒntrækt/",
         "He signed an apprenticeship contract with an aerospace engineering manufacturer.",
         "Anh ấy đã ký hợp đồng học nghề với một công ty chế tạo linh kiện hàng không vũ trụ.",
         ["sign an apprenticeship contract", "three-year apprenticeship contract"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("employment prospect", "n.phr", "triển vọng và cơ hội việc làm rộng mở", "/ɪmˈplɔɪmənt ˈprɒspekt/",
         "Graduates in artificial intelligence and renewable energy enjoy bright employment prospects.",
         "Sinh viên tốt nghiệp ngành trí tuệ nhân tạo và năng lượng sạch có cơ hội việc làm vô cùng xán lạn.",
         ["bright employment prospects", "improve employment prospects"],
         "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80"),
        ("in-demand profession", "n.phr", "ngành nghề thị trường đang rất cần nhân lực", "/ˌɪn dɪˈmɑːnd prəˈfeʃn/",
         "Cybersecurity analysis has rapidly become one of the most in-demand professions globally.",
         "Chuyên viên an ninh mạng đã nhanh chóng trở thành một trong những nghề khát nhân lực nhất.",
         ["enter an in-demand profession", "top in-demand professions"],
         "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"),
        ("freelance contracting", "n.phr", "làm việc tự do theo hợp đồng từng dự án", "/ˈfriːlɑːns kənˈtræktɪŋ/",
         "Many digital creators prefer freelance contracting because of its schedule autonomy.",
         "Nhiều nhà sáng tạo nội dung số thích làm tự do theo hợp đồng vì được tự chủ thời gian làm việc.",
         ["opt for freelance contracting", "sustainable freelance contracting"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-10-lifelong-learning": [
        ("autonomous learning", "n.phr", "tự học chủ động và tự lập kế hoạch", "/ɔːˈtɒnəməs ˈlɜːnɪŋ/",
         "Autonomous learning enables self-driven individuals to conquer complex foreign languages.",
         "Phương pháp học tự chủ giúp những cá nhân kiên trì chinh phục thành công ngoại ngữ khó.",
         ["cultivate autonomous learning", "strategies for autonomous learning"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("cognitive flexibility", "n.phr", "sự linh hoạt trong tư duy nhận thức", "/ˈkɒɡnətɪv ˌfleksəˈbɪləti/",
         "Practicing musical instruments and learning logic games enhances cognitive flexibility.",
         "Luyện chơi nhạc cụ và giải đố tư duy logic giúp tăng cường sự linh hoạt nhận thức cho não bộ.",
         ["boost cognitive flexibility", "demonstrate cognitive flexibility"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("skill obsolescence", "n.phr", "sự lạc hậu lỗi thời của kỹ năng cũ", "/skɪl ˌɒbsəˈlesns/",
         "Continuous upskilling protects workers from sudden skill obsolescence in the automated age.",
         "Thường xuyên nâng cao tay nghề bảo vệ người lao động khỏi sự lỗi thời kỹ năng trong thời đại tự động.",
         ["guard against skill obsolescence", "rate of skill obsolescence"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("continuous professional development", "n.phr", "phát triển chuyên môn nghiệp vụ liên tục", "/kənˈtɪnjuəs prəˈfeʃənl dɪˈveləpmənt/",
         "Teachers earn annual credits through continuous professional development seminars.",
         "Giáo viên tích lũy tín chỉ hằng năm qua các hội thảo phát triển nghiệp vụ liên tục.",
         ["commit to continuous professional development", "CPD programs"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("online micro-credential", "n.phr", "chứng chỉ kỹ năng ngắn hạn trực tuyến", "/ˌɒnlaɪn ˈmaɪkrəʊ krəˌdenʃl/",
         "Earning online micro-credentials helps professionals prove niche expertise quickly.",
         "Sở hữu các chứng chỉ số ngắn hạn trực tuyến giúp người đi làm nhanh chóng chứng minh chuyên môn sâu.",
         ["stack online micro-credentials", "earn micro-credentials"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("information synthesis", "n.phr", "kỹ năng tổng hợp và chắt lọc thông tin", "/ˌɪnfəˈmeɪʃn ˈsɪnθəsɪs/",
         "Mastering information synthesis allows researchers to extract gems from voluminous papers.",
         "Thành thạo kỹ năng tổng hợp thông tin giúp người nghiên cứu chắt lọc tinh hoa từ hàng trăm tài liệu.",
         ["excel in information synthesis", "rapid information synthesis"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("metacognitive awareness", "n.phr", "nhận thức về chính quá trình tư duy của bản thân", "/ˌmetəkɒɡˈnɪtɪv əˈweənəs/",
         "Students with high metacognitive awareness readily pinpoint which study strategies work best.",
         "Học sinh có nhận thức siêu nhận thức cao dễ dàng biết rõ chiến lược học nào phát huy hiệu quả nhất.",
         ["heighten metacognitive awareness", "benefits of metacognitive awareness"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("distance education", "n.phr", "hình thức đào tạo giáo dục từ xa", "/ˌdɪstəns ˌedʒuˈkeɪʃn/",
         "Distance education brings world-class university lectures to rural mountainous districts.",
         "Giáo dục từ xa mang bài giảng của các đại học hàng đầu đến với học sinh các huyện miền núi xa xôi.",
         ["enroll in distance education", "accredited distance education"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("lifelong inquiry", "n.phr", "tinh thần ham học hỏi tìm tòi trọn đời", "/ˌlaɪflɒŋ ɪnˈkwaɪəri/",
         "True scientists are distinguished by their perpetual spirit of lifelong inquiry.",
         "Những nhà khoa học chân chính được nhận biết bởi tinh thần say mê tìm tòi học hỏi suốt cả cuộc đời.",
         ["spirit of lifelong inquiry", "foster lifelong inquiry"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("experiential learning", "n.phr", "phương pháp học tập thông qua trải nghiệm thực tế", "/ɪkˌspɪəriˈenʃl ˈlɜːnɪŋ/",
         "Field trips and lab experiments are classic examples of experiential learning.",
         "Các chuyến đi thực địa và thí nghiệm phòng lab là ví dụ điển hình cho phương pháp học qua trải nghiệm.",
         ["power of experiential learning", "engage in experiential learning"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("peer-to-peer mentoring", "n.phr", "kèm cặp và hướng dẫn tương trợ giữa các bạn học", "/ˌpɪə tə ˈpɪə ˈmentɔːrɪŋ/",
         "Peer-to-peer mentoring builds confidence in junior pupils while consolidating seniors' mastery.",
         "Mô hình đôi bạn cùng tiến giúp học sinh khóa dưới tự tin hơn và củng cố kiến thức cho khóa trên.",
         ["participate in peer-to-peer mentoring", "mutual mentoring"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("intellectual stimulation", "n.phr", "sự kích thích và khơi dậy niềm say mê trí tuệ", "/ˌɪntəˈlektʃuəl ˌstɪmjuˈleɪʃn/",
         "Reading profound philosophy classics provides immense intellectual stimulation.",
         "Đọc những tác phẩm triết học kinh điển mang lại sự kích thích trí tuệ vô cùng to lớn.",
         ["seek intellectual stimulation", "source of intellectual stimulation"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("adaptability quotient", "n.phr", "chỉ số năng lực thích ứng với sự thay đổi", "/əˌdæptəˈbɪləti ˈkwəʊʃnt/",
         "HR leaders argue that adaptability quotient is even more critical than raw IQ in modern crises.",
         "Các nhà quản lý nhân sự cho rằng chỉ số thích ứng còn quan trọng hơn cả IQ trước biến động thời cuộc.",
         ["high adaptability quotient", "test adaptability quotient"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("open-source knowledge", "n.phr", "kho tri thức nguồn mở tự do cho nhân loại", "/ˌəʊpən sɔːs ˈnɒlɪdʒ/",
         "Open-source knowledge repositories democratize access to high-end programming tools.",
         "Các kho tri thức nguồn mở giúp bình đẳng hóa việc tiếp cận các công cụ lập trình tiên tiến.",
         ["contribute to open-source knowledge", "free open-source knowledge"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("self-directed project", "n.phr", "dự án nghiên cứu tự khởi xướng và điều hành", "/ˌself daɪˈrektɪd ˈprɒdʒekt/",
         "High school seniors build robots through ambitious self-directed projects.",
         "Học sinh cấp 3 tự lắp ráp robot thông qua những dự án tự định hướng đầy hoài bão.",
         ["execute self-directed projects", "presentation of self-directed projects"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("problem-solving agility", "n.phr", "sự nhạy bén và linh hoạt trong tháo gỡ khó khăn", "/ˈprɒbləm ˌsɒlvɪŋ əˈdʒɪləti/",
         "Hackathons test participants' problem-solving agility under strict 24-hour deadlines.",
         "Các cuộc thi lập trình thử thách sự nhạy bén giải quyết vấn đề của thí sinh trong vòng 24 giờ.",
         ["demonstrate problem-solving agility", "hone problem-solving agility"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("lifelong enrichment", "n.phr", "sự bồi đắp và làm giàu tâm hồn trí tuệ suốt đời", "/ˌlaɪflɒŋ ɪnˈrɪtʃmənt/",
         "Pursuing arts, languages, and literature delivers deep lifelong enrichment for senior citizens.",
         "Đam mê nghệ thuật, ngôn ngữ và văn học đem lại sự bồi đắp tâm hồn sâu sắc suốt đời cho người cao tuổi.",
         ["source of lifelong enrichment", "attain lifelong enrichment"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80")
    ]
}

def inject_words(file_path, additions_dict):
    with open(file_path, "r", encoding="utf-8") as f:
        text = f.read()

    for unit_slug, items in additions_dict.items():
        search_str = f'"{unit_slug}": ['
        idx = text.find(search_str)
        if idx != -1:
            close_idx = text.find('  ],', idx)
            if close_idx != -1:
                new_lines = []
                for item in items:
                    word, pos, vi, ipa, en_ex, vi_ex, colocs, img = item
                    clean_id = f"v-boost-{word.lower().replace(' ', '-').replace('/', '-')}"
                    audio = f"https://dict.youdao.com/dictvoice?audio={word.replace(' ', '+')}&type=2"
                    new_lines.append('    ,')
                    new_lines.append('    {')
                    new_lines.append(f'      id: {json.dumps(clean_id)},')
                    new_lines.append(f'      word: {json.dumps(word)},')
                    new_lines.append(f'      partOfSpeech: {json.dumps(pos)},')
                    new_lines.append(f'      meaningVi: {json.dumps(vi)},')
                    new_lines.append(f'      ipa: {json.dumps(ipa)},')
                    new_lines.append(f'      audioUrl: {json.dumps(audio)},')
                    new_lines.append(f'      imageUrl: {json.dumps(img)},')
                    new_lines.append(f'      exampleEn: {json.dumps(en_ex)},')
                    new_lines.append(f'      exampleVi: {json.dumps(vi_ex)},')
                    new_lines.append(f'      collocations: {json.dumps(colocs)}')
                    new_lines.append('    }')
                insert_content = "\n".join(new_lines)
                text = text[:close_idx] + insert_content + "\n" + text[close_idx:]

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(text)

# 1. Inject into Grade 11
g11_path = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "curriculum", "expanded-vocab-g11.ts")
inject_words(g11_path, G11_EXTRA)
print("Updated Grade 11 expanded vocabulary.")

# 2. Inject into Grade 12
g12_path = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "curriculum", "expanded-vocab-g12.ts")
inject_words(g12_path, G12_ADDITIONS)
print("Updated Grade 12 expanded vocabulary.")
