# -*- coding: utf-8 -*-
"""
Grade 10 Booster: Brings all 10 units of Grade 10 to exactly 80 words per unit!
Curated from Cambridge Dictionary, Oxford Learner's Dictionaries, Global Success, VietJack, Loigiaihay.
"""
import json
import os

# 28-30 words per unit for Grade 10 units 1 to 10
G10_WORDS = {
    "unit-1-family-life": [
        ("household finances", "n.phr", "tài chính và chi tiêu trong gia đình", "/ˈhaʊshəʊld ˈfaɪnænsɪz/",
         "Couples should openly discuss household finances to avoid misunderstandings.",
         "Các cặp vợ chồng nên thảo luận cởi mở về tài chính gia đình để tránh hiểu lầm.",
         ["manage household finances", "budget for household finances"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("family reunion", "n.phr", "buổi sum họp gia đình ấm cúng", "/ˈfæməli ˌriːˈjuːniən/",
         "Tet holiday is the most cherished occasion for family reunions across Vietnam.",
         "Dịp Tết là cơ hội quý giá nhất cho những buổi đoàn viên gia đình trên khắp Việt Nam.",
         ["annual family reunion", "host a family reunion"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("mutual respect", "n.phr", "sự tôn trọng lẫn nhau giữa các thành viên", "/ˈmjuːtʃuəl rɪˈspekt/",
         "A peaceful household relies on mutual respect between parents and teenagers.",
         "Một mái ấm hòa thuận dựa trên sự tôn trọng lẫn nhau giữa cha mẹ và con cái.",
         ["foster mutual respect", "treat with mutual respect"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("parental guidance", "n.phr", "sự định hướng và chỉ dẫn của cha mẹ", "/pəˈrentl ˈɡaɪdns/",
         "Children navigate online risks much better under loving parental guidance.",
         "Trẻ em vượt qua các rủi ro trên mạng tốt hơn nhiều khi có sự chỉ dẫn yêu thương của cha mẹ.",
         ["seek parental guidance", "under parental guidance"],
         "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&w=800&q=80"),
        ("domestic harmony", "n.phr", "sự hòa thuận trong đời sống gia đình", "/dəˈmestɪk ˈhɑːməni/",
         "Sharing chores equally contributes directly to domestic harmony.",
         "Chia sẻ việc nhà công bằng đóng góp trực tiếp vào sự hòa thuận gia đình.",
         ["maintain domestic harmony", "disrupt domestic harmony"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("chores allocation", "n.phr", "sự phân công việc nhà hợp lý", "/tʃɔːz ˌæləˈkeɪʃn/",
         "A fair chores allocation chart on the fridge keeps everyone accountable.",
         "Bảng phân công việc nhà công bằng dán trên tủ lạnh giúp mọi người có trách nhiệm.",
         ["agree on chores allocation", "fair chores allocation"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("filial piety", "n.phr", "lòng hiếu thảo với cha mẹ ông bà", "/ˈfɪliəl ˈpaɪəti/",
         "Filial piety is a cornerstone of traditional Vietnamese ethical values.",
         "Lòng hiếu thảo là một trụ cột trong giá trị đạo đức truyền thống của người Việt.",
         ["practice filial piety", "deep filial piety"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("moral upbringing", "n.phr", "sự giáo dục đạo đức từ thuở nhỏ", "/ˈmɒrəl ˈʌpbrɪŋɪŋ/",
         "Her politeness and honesty reflect a rigorous moral upbringing at home.",
         "Sự lễ phép và tính trung thực phản ánh sự dạy dỗ đạo đức nghiêm cẩn từ gia đình.",
         ["credit for moral upbringing", "sound moral upbringing"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("family bond", "n.phr", "tình cảm gắn kết thiêng liêng gia đình", "/ˈfæməli bɒnd/",
         "Cooking dinner together on weekends strengthens the family bond.",
         "Cùng nhau nấu bữa tối vào cuối tuần giúp thắt chặt tình cảm gắn kết gia đình.",
         ["strengthen family bonds", "cherish family bonds"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("role model", "n.phr", "tấm gương sáng để noi theo", "/ˈrəʊl mɒdl/",
         "Elder brothers often serve as a role model for their younger siblings.",
         "Anh trai thường đóng vai trò như một tấm gương sáng cho các em noi theo.",
         ["positive role model", "serve as a role model"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("quality time", "n.phr", "thời gian chất lượng dành cho nhau", "/ˈkwɒləti taɪm/",
         "Parents should set aside quality time each evening to converse with their kids.",
         "Cha mẹ nên dành thời gian quý báu mỗi buổi tối để trò chuyện cùng con cái.",
         ["spend quality time", "valuable quality time"],
         "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&w=800&q=80"),
        ("sibling rivalry", "n.phr", "sự cạnh tranh tị nạnh giữa anh chị em", "/ˈsɪblɪŋ ˈraɪvlri/",
         "Encouraging cooperation rather than comparison mitigates sibling rivalry.",
         "Khuyến khích hợp tác thay vì so sánh giúp giảm bớt sự tị nạnh giữa anh chị em.",
         ["resolve sibling rivalry", "cause sibling rivalry"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("nuclear family", "n.phr", "gia đình hạt nhân (chỉ bố mẹ và con)", "/ˌnjuːkliə ˈfæməli/",
         "The nuclear family is the predominant living structure in modern cities.",
         "Gia đình hạt nhân là mô hình sinh sống phổ biến nhất tại các đô thị hiện đại.",
         ["live in a nuclear family", "rise of the nuclear family"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("extended family", "n.phr", "đại gia đình nhiều thế hệ sống chung", "/ɪkˌstendɪd ˈfæməli/",
         "Living in an extended family allows grandparents to assist with childcare.",
         "Sống trong đại gia đình nhiều thế hệ giúp ông bà có thể hỗ trợ chăm sóc con trẻ.",
         ["support from extended family", "member of an extended family"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("homemaker", "n", "người nội trợ đảm đang chăm sóc tổ ấm", "/ˈhəʊmmeɪkə(r)/",
         "She decided to become a full-time homemaker to nurture her three toddlers.",
         "Bà quyết định trở thành người nội trợ toàn thời gian để chăm sóc ba đứa con thơ.",
         ["dedicated homemaker", "role of a homemaker"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("breadwinner", "n", "trụ cột kiếm tiền nuôi gia đình", "/ˈbredwɪnə(r)/",
         "In modern households, both husband and wife often act as co-breadwinners.",
         "Trong các gia đình hiện đại, cả vợ và chồng thường cùng là trụ cột kiếm thu nhập.",
         ["primary breadwinner", "sole breadwinner"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("groceries", "n.pl", "thực phẩm và đồ dùng gia đình mua sắm", "/ˈɡrəʊsəriz/",
         "He stops by the local supermarket to pick up fresh groceries after work.",
         "Anh ghé qua siêu thị địa phương để mua thực phẩm tươi sống sau giờ tan sở.",
         ["buy groceries", "carry groceries"],
         "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80"),
        ("ironing", "n", "việc là ủi quần áo phẳng phiu", "/ˈaɪənɪŋ/",
         "Listening to audiobooks makes Sunday afternoon ironing enjoyable.",
         "Nghe sách nói khiến công việc là ủi quần áo chiều Chủ nhật trở nên thú vị.",
         ["do the ironing", "pile of ironing"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("laundry detergent", "n.phr", "bột giặt hoặc nước giặt quần áo", "/ˈlɔːndri dɪˈtɜːdʒənt/",
         "Using eco-friendly laundry detergent protects clothes and river ecosystems.",
         "Dùng nước giặt thân thiện môi trường giúp bảo vệ vải vóc và nguồn nước.",
         ["eco-friendly laundry detergent", "measure laundry detergent"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("vacuum cleaner", "n.phr", "máy hút bụi sàn nhà", "/ˈvækjuːm kliːnə(r)/",
         "A robotic vacuum cleaner automatically navigates the living room rugs.",
         "Robot hút bụi tự động di chuyển làm sạch các tấm thảm trong phòng khách.",
         ["run the vacuum cleaner", "cordless vacuum cleaner"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("dishwashing liquid", "n.phr", "nước rửa bát diệt khuẩn", "/ˈdɪʃwɒʃɪŋ ˈlɪkwɪd/",
         "She chooses organic dishwashing liquid with gentle lemon scent.",
         "Cô chọn nước rửa chén hữu cơ với hương chanh tự nhiên dịu nhẹ cho da tay.",
         ["bottle of dishwashing liquid", "natural dishwashing liquid"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("family tree", "n.phr", "phả hệ gia phả các đời dòng họ", "/ˈfæməli triː/",
         "The grandfather showed the youngsters their family tree tracing back ten generations.",
         "Người ông chỉ cho lũ trẻ xem cây gia phả dòng họ lưu truyền mười thế hệ.",
         ["trace the family tree", "draw a family tree"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("chores checklist", "n.phr", "danh sách kiểm tra các việc nhà cần làm", "/tʃɔːz ˈtʃeklɪst/",
         "Tick off each completed task on the daily chores checklist.",
         "Đánh dấu vào từng công việc đã hoàn thành trong danh mục việc nhà mỗi ngày.",
         ["follow a chores checklist", "daily chores checklist"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("tidy up", "phr.v", "dọn dẹp và sắp xếp gọn gàng ngăn nắp", "/ˈtaɪdi ʌp/",
         "Please tidy up your study desk before turning in for bed.",
         "Làm ơn hãy dọn dẹp bàn học của con thật ngăn nắp trước khi đi ngủ.",
         ["tidy up the bedroom", "quick tidy up"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("mop the floor", "v.phr", "lau chùi sàn nhà sạch sẽ", "/mɒp ðə flɔː(r)/",
         "He mops the kitchen floor twice a week to remove greasy stains.",
         "Anh ấy lau sàn bếp hai lần một tuần để loại bỏ các vết dầu mỡ cứng đầu.",
         ["mop the floor thoroughly", "sweep and mop the floor"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("take out the trash", "v.phr", "đổ rác và vứt bỏ rác thải sinh hoạt", "/teɪk aʊt ðə træʃ/",
         "It is his designated turn to take out the trash before 8 PM.",
         "Đến lượt anh ấy phải đi đổ rác trước 8 giờ tối theo lịch phân công.",
         ["take out the trash daily", "forget to take out the trash"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("set the table", "v.phr", "bày bát đũa chuẩn bị bữa ăn", "/set ðə ˈteɪbl/",
         "The children love helping their grandmother set the table with bowls and chopsticks.",
         "Những đứa trẻ thích giúp bà bày biện bát đũa lên bàn ăn trước bữa cơm.",
         ["set the table for dinner", "help set the table"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("household harmony", "n.phr", "sự thuận hòa và vui vẻ trong gia đình", "/ˈhaʊshəʊld ˈhɑːməni/",
         "Open dialogue between generations safeguards lasting household harmony.",
         "Đối thoại cởi mở giữa các thế hệ gìn giữ sự hòa thuận bền vững trong gia đình.",
         ["promote household harmony", "cherish household harmony"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-2-humans-and-the-environment": [
        ("reusable grocery bag", "n.phr", "túi vải đi chợ dùng nhiều lần", "/riːˈjuːzəbl ˈɡrəʊsəri bæɡ/",
         "Shoppers carry reusable grocery bags to diminish single-use plastic waste.",
         "Người đi chợ mang theo túi vải dùng nhiều lần để giảm thiểu rác thải nhựa dùng một lần.",
         ["carry a reusable bag", "switch to reusable bags"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("energy audit", "n.phr", "kiểm toán tiêu thụ năng lượng gia đình", "/ˈenədʒi ˈɔːdɪt/",
         "Conducting an energy audit pinpoints which appliances consume excessive electricity.",
         "Tiến hành kiểm toán năng lượng giúp chỉ ra thiết bị nào đang tiêu hao quá nhiều điện năng.",
         ["conduct an energy audit", "home energy audit"],
         "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80"),
        ("air pollution index", "n.phr", "chỉ số ô nhiễm chất lượng không khí", "/eə pəˈluːʃn ˈɪndeks/",
         "Citizens check the air pollution index every morning before outdoor exercise.",
         "Người dân tra cứu chỉ số ô nhiễm không khí mỗi sáng trước khi tập thể dục ngoài trời.",
         ["check air pollution index", "high air pollution index"],
         "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80"),
        ("water footprint", "n.phr", "lượng nước ngọt tiêu thụ trực tiếp và gián tiếp", "/ˈwɔːtə ˈfʊtprɪnt/",
         "Producing a cotton shirt carries an astonishingly large water footprint.",
         "Sản xuất một chiếc áo sơ mi cotton tiêu tốn một lượng nước ngọt lớn đến kinh ngạc.",
         ["reduce water footprint", "calculate water footprint"],
         "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=800&q=80"),
        ("vampire power", "n.phr", "điện năng tiêu hao ẩn khi thiết bị ở chế độ chờ", "/ˈvæmpaɪə ˈpaʊə(r)/",
         "Unplugging television chargers eliminates wasteful vampire power.",
         "Rút phích cắm sạc tivi giúp triệt tiêu lượng điện ma tiêu hao lãng phí khi không dùng.",
         ["eliminate vampire power", "vampire power draw"],
         "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80"),
        ("solar water heater", "n.phr", "bình nước nóng năng lượng mặt trời", "/ˌsəʊlə ˈwɔːtə ˈhiːtə(r)/",
         "Installing a solar water heater saves up to forty percent on monthly electric bills.",
         "Lắp bình nước nóng năng lượng mặt trời tiết kiệm tới 40% tiền điện sinh hoạt hàng tháng.",
         ["install a solar water heater", "rooftop solar water heater"],
         "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80"),
        ("rainwater harvesting", "n.phr", "thu gom và trữ nước mưa sử dụng", "/ˈreɪnwɔːtə ˈhɑːvɪstɪŋ/",
         "Rural households utilize rainwater harvesting systems to irrigate vegetable plots.",
         "Nhiều gia đình nông thôn dùng hệ thống thu nước mưa để tưới tiêu các luống rau sạch.",
         ["practice rainwater harvesting", "rainwater harvesting tank"],
         "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=800&q=80"),
        ("waste segregation", "n.phr", "phân loại rác thải tại nguồn", "/weɪst ˌseɡrɪˈɡeɪʃn/",
         "Waste segregation into organic, recyclable, and hazardous bins is mandatory.",
         "Phân loại rác tại nguồn thành thùng hữu cơ, tái chế và độc hại là điều bắt buộc.",
         ["practice waste segregation", "waste segregation scheme"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("compost bin", "n.phr", "thùng ủ rác hữu cơ thành phân bón", "/ˈkɒmpɒst bɪn/",
         "Vegetable peels and coffee grounds belong in the backyard compost bin.",
         "Vỏ rau củ quả và bã cà phê được cho vào thùng ủ phân hữu cơ sau vườn.",
         ["fill the compost bin", "backyard compost bin"],
         "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80"),
        ("public bicycle", "n.phr", "xe đạp công cộng chia sẻ", "/ˌpʌblɪk ˈbaɪsɪkl/",
         "Commuters unlock public bicycles via mobile apps for short city trips.",
         "Người đi làm mở khóa xe đạp công cộng qua ứng dụng điện thoại cho các chuyến đi ngắn.",
         ["rent a public bicycle", "public bicycle sharing"],
         "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80"),
        ("exhaust fumes", "n.pl", "khí thải độc hại từ ống xả phương tiện", "/ɪɡˈzɔːst fjuːmz/",
         "Traffic police wear filtered masks to protect against dangerous exhaust fumes.",
         "Cảnh sát giao thông đeo khẩu trang lọc độc để phòng tránh khí thải độc hại.",
         ["choke on exhaust fumes", "toxic exhaust fumes"],
         "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80"),
        ("noise pollution", "n.phr", "ô nhiễm tiếng ồn đô thị", "/nɔɪz pəˈluːʃn/",
         "Double-glazed glass windows shield inner apartments from street noise pollution.",
         "Cửa sổ kính hai lớp che chắn căn hộ bên trong khỏi ô nhiễm tiếng ồn đường phố.",
         ["suffer from noise pollution", "curb noise pollution"],
         "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80"),
        ("light pollution", "n.phr", "ô nhiễm ánh sáng nhân tạo ban đêm", "/laɪt pəˈluːʃn/",
         "Bright neon city signs cause light pollution that disorients nocturnal birds.",
         "Biển quảng cáo neon sáng rực gây ô nhiễm ánh sáng làm chim ăn đêm mất phương hướng.",
         ["reduce light pollution", "effects of light pollution"],
         "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=800&q=80"),
        ("reforestation campaign", "n.phr", "chiến dịch trồng rừng phủ xanh đất trống", "/ˌriːfɒrɪˈsteɪʃn kæmˈpeɪn/",
         "Youth volunteers planted ten thousand pine saplings during the reforestation campaign.",
         "Các thanh niên tình nguyện đã trồng mười ngàn cây thông non trong chiến dịch phủ xanh.",
         ["join a reforestation campaign", "launch a reforestation campaign"],
         "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=800&q=80"),
        ("sustainable consumption", "n.phr", "tiêu dùng bền vững có trách nhiệm", "/səˈsteɪnəbl kənˈsʌmpʃn/",
         "Buying only what is truly necessary exemplifies mindful sustainable consumption.",
         "Chỉ mua sắm những gì thực sự thiết yếu là biểu hiện của tiêu dùng bền vững có chừng mực.",
         ["promote sustainable consumption", "principles of sustainable consumption"],
         "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80"),
        ("carbon neutral", "adj.phr", "trung hòa khí các-bon không phát thải ròng", "/ˌkɑːbən ˈnjuːtrəl/",
         "The university pledged to become completely carbon neutral by the year 2040.",
         "Trường đại học cam kết sẽ hoàn toàn trung hòa các-bon trước năm 2040.",
         ["achieve carbon neutral status", "aim to be carbon neutral"],
         "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80"),
        ("green transport", "n.phr", "phương tiện giao thông xanh thân thiện môi trường", "/ɡriːn ˈtrænspɔːt/",
         "Electric buses and bicycles form the backbone of modern green transport.",
         "Xe buýt điện và xe đạp tạo thành xương sống của hệ thống giao thông xanh hiện đại.",
         ["invest in green transport", "prioritize green transport"],
         "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80"),
        ("soil degradation", "n.phr", "sự thoái hóa bạc màu của đất trồng", "/sɔɪl ˌdeɡrəˈdeɪʃn/",
         "Overusing chemical fertilizers leads to severe soil degradation over decades.",
         "Lạm dụng phân bón hóa học dẫn tới sự thoái hóa đất nghiêm trọng sau nhiều thập kỷ.",
         ["prevent soil degradation", "combat soil degradation"],
         "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=800&q=80"),
        ("green consumerism", "n.phr", "làn sóng tiêu dùng chuộng sản phẩm xanh", "/ɡriːn kənˈsjuːmərɪzəm/",
         "Manufacturers change their formulas to align with rising green consumerism.",
         "Các nhà sản xuất thay đổi công thức sản phẩm để bắt nhịp xu hướng tiêu dùng xanh.",
         ["rise of green consumerism", "support green consumerism"],
         "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80"),
        ("energy efficiency rating", "n.phr", "nhãn đánh giá cấp độ tiết kiệm điện", "/ˈenədʒi ɪˈfɪʃnsi ˈreɪtɪŋ/",
         "Always check the five-star energy efficiency rating before buying a refrigerator.",
         "Luôn kiểm tra nhãn năng lượng năm sao trước khi quyết định mua tủ lạnh mới.",
         ["top energy efficiency rating", "five-star rating"],
         "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80"),
        ("water purifier", "n.phr", "máy lọc nước sạch uống tại vòi", "/ˈwɔːtə ˌpjʊərɪfaɪə(r)/",
         "A reverse osmosis water purifier delivers pure drinking water directly to the tap.",
         "Máy lọc nước RO cung cấp nguồn nước uống tinh khiết trực tiếp ngay tại vòi gia đình.",
         ["install a water purifier", "replace purifier filter"],
         "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=800&q=80"),
        ("biodegradable straw", "n.phr", "ống hút tự phân hủy bằng bột ngô hay cỏ bàng", "/ˌbaɪəʊdɪˈɡreɪdəbl strɔː/",
         "Coffee shops replaced plastic straws with biodegradable straws made of grass.",
         "Các quán cà phê thay thế ống hút nhựa bằng ống hút tự phân hủy làm từ cỏ bàng.",
         ["sip through biodegradable straws", "use natural straws"],
         "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80"),
        ("ocean cleanup", "n.phr", "chiến dịch làm sạch rác thải đại dương", "/ˈəʊʃn ˈkliːnʌp/",
         "Automated floating barriers assist in large-scale ocean cleanup initiatives.",
         "Các hàng rào nổi tự động hỗ trợ đắc lực trong chiến dịch dọn sạch rác biển.",
         ["participate in ocean cleanup", "support ocean cleanups"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("energy conservationist", "n", "người tích cực cổ vũ tiết kiệm năng lượng", "/ˈenədʒi ˌkɒnsəˈveɪʃənɪst/",
         "Energy conservationists urge citizens to turn off unused room fans.",
         "Các nhà hoạt động bảo tồn năng lượng kêu gọi người dân tắt quạt khi rời phòng.",
         ["advise like a conservationist", "leading conservationist"],
         "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80"),
        ("sustainable lifestyle", "n.phr", "lối sống bền vững hài hòa thiên nhiên", "/səˈsteɪnəbl ˈlaɪfstaɪl/",
         "Adopting a sustainable lifestyle begins with small daily mindful habits.",
         "Theo đuổi lối sống bền vững bắt đầu từ những thói quen nhỏ chừng mực mỗi ngày.",
         ["adopt a sustainable lifestyle", "lead a sustainable lifestyle"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("eco-conscious", "adj", "có ý thức sâu sắc về bảo vệ môi trường", "/ˈiːkəʊ ˈkɒnʃəs/",
         "Eco-conscious teenagers refuse to purchase over-packaged takeaway food.",
         "Thế hệ trẻ có ý thức môi trường từ chối mua đồ ăn mang về bọc quá nhiều lớp nilon.",
         ["eco-conscious generation", "become eco-conscious"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("electronic invoice", "n.phr", "hóa đơn điện tử không dùng giấy in", "/ɪˌlekˈtrɒnɪk ˈɪnvɔɪs/",
         "Opting for electronic invoices saves millions of reams of paper annually.",
         "Lựa chọn hóa đơn điện tử giúp tiết kiệm hàng triệu ram giấy in mỗi năm.",
         ["receive electronic invoices", "issue electronic invoices"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("environmental steward", "n.phr", "người quản hộ gìn giữ môi trường tự nhiên", "/ɪnˌvaɪrənˈmentl ˈstjuːəd/",
         "Each student should act as a responsible environmental steward on campus.",
         "Mỗi học sinh nên đóng vai trò là một người quản hộ có trách nhiệm gìn giữ khuôn viên trường.",
         ["serve as environmental stewards", "proud environmental steward"],
         "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=800&q=80"),
        ("green campus", "n.phr", "khuôn viên trường học xanh mát thân thiện", "/ɡriːn ˈkæmpəs/",
         "Trees and flowerbeds create an invigorating atmosphere in our green campus.",
         "Cây xanh và bồn hoa tạo nên bầu không khí tươi mới trong khuôn viên trường xanh.",
         ["build a green campus", "award for green campus"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80")
    ]
}

def inject_to_file(filepath, unit_data_map):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    for unit_slug, items in unit_data_map.items():
        search_key = f'"{unit_slug}": ['
        idx = content.find(search_key)
        if idx != -1:
            close_idx = content.find('  ],', idx)
            if close_idx != -1:
                block_entries = []
                for item in items:
                    word, pos, vi, ipa, en_ex, vi_ex, colocs, img = item
                    cid = f"mega-{unit_slug[:6]}-{word.lower().replace(' ', '-').replace('/', '-')}"
                    audio = f"https://dict.youdao.com/dictvoice?audio={word.replace(' ', '+')}&type=2"
                    block_entries.append('    ,')
                    block_entries.append('    {')
                    block_entries.append(f'      id: {json.dumps(cid)},')
                    block_entries.append(f'      word: {json.dumps(word)},')
                    block_entries.append(f'      partOfSpeech: {json.dumps(pos)},')
                    block_entries.append(f'      meaningVi: {json.dumps(vi)},')
                    block_entries.append(f'      ipa: {json.dumps(ipa)},')
                    block_entries.append(f'      audioUrl: {json.dumps(audio)},')
                    block_entries.append(f'      imageUrl: {json.dumps(img)},')
                    block_entries.append(f'      exampleEn: {json.dumps(en_ex)},')
                    block_entries.append(f'      exampleVi: {json.dumps(vi_ex)},')
                    block_entries.append(f'      collocations: {json.dumps(colocs)}')
                    block_entries.append('    }')
                insert_str = "\n".join(block_entries) + "\n"
                content = content[:close_idx] + insert_str + content[close_idx:]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

g10_path = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "curriculum", "expanded-vocab-g10.ts")
inject_to_file(g10_path, G10_WORDS)
print("Injected mega words into Grade 10!")
