# -*- coding: utf-8 -*-
"""
Boost Grade 11 and Grade 12 vocabulary so that every single unit reaches 55 to 80 words!
Curated from textbook syllabus, VietJack, Loigiaihay, and Cambridge Dictionary.
"""
import json
import os

G11_EXTRA = {
    "unit-4-asean-and-vietnam": [
        ("regional bloc", "n.phr", "khối liên minh khu vực", "/ˈriːdʒənl blɒk/",
         "ASEAN is one of the most dynamic regional economic blocs in Asia.",
         "ASEAN là một trong những khối liên minh kinh tế khu vực năng động nhất châu Á.",
         ["dynamic regional bloc", "member of a regional bloc"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("youth delegation", "n.phr", "phái đoàn thanh niên đại biểu", "/juːθ ˌdelɪˈɡeɪʃn/",
         "Vietnamese youth delegations actively contribute creative initiatives at ASEAN forums.",
         "Các phái đoàn thanh niên Việt Nam tích cực đóng góp sáng kiến tại các diễn đàn ASEAN.",
         ["send a youth delegation", "represent the youth delegation"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("treaty of amity", "n.phr", "hiệp ước thân thiện và hợp tác", "/ˈtriːti əv ˈæməti/",
         "The Treaty of Amity and Cooperation embodies peaceful coexistence in Southeast Asia.",
         "Hiệp ước Thân thiện và Hợp tác thể hiện tinh thần chung sống hòa bình ở Đông Nam Á.",
         ["sign the Treaty of Amity", "principles of amity"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("multilateral ties", "n.phr", "mối quan hệ liên kết đa phương", "/ˌmʌltiˈlætərəl taɪz/",
         "Deepening multilateral ties safeguards national sovereignty and maritime peace.",
         "Làm sâu sắc các mối quan hệ đa phương giúp bảo vệ chủ quyền và hòa bình trên biển.",
         ["strengthen multilateral ties", "develop multilateral ties"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("communique", "n", "thông cáo chung sau hội nghị cấp cao", "/kəˈmjuːnɪkeɪ/",
         "The foreign ministers issued a landmark joint communique on maritime security.",
         "Các ngoại trưởng đã ra thông cáo chung mang tính bước ngoặt về an ninh biển.",
         ["issue a joint communique", "official communique"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("cross-cultural dialogue", "n.phr", "đối thoại giao lưu liên văn hóa", "/ˌkrɒs ˈkʌltʃərəl ˈdaɪəlɒɡ/",
         "Cross-cultural dialogue builds lasting empathy and dismantles historical prejudices.",
         "Đối thoại liên văn hóa bồi đắp lòng thấu cảm và xóa bỏ các định kiến lịch sử.",
         ["foster cross-cultural dialogue", "participate in dialogue"],
         "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=800&q=80"),
        ("socio-cultural", "adj", "thuộc về lĩnh vực văn hóa xã hội", "/ˌsəʊsiəʊ ˈkʌltʃərəl/",
         "The ASEAN Socio-Cultural Community focuses on education and social welfare.",
         "Cộng đồng Văn hóa - Xã hội ASEAN tập trung vào giáo dục và phúc lợi xã hội.",
         ["socio-cultural pillar", "socio-cultural development"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("chairmanship", "n", "vai trò chủ tịch luân phiên nhiệm kỳ", "/ˈtʃeəmənʃɪp/",
         "Vietnam successfully concluded its 2020 ASEAN chairmanship despite pandemic difficulties.",
         "Việt Nam đã hoàn thành xuất sắc trọng trách chủ tịch ASEAN 2020 bất chấp dịch bệnh.",
         ["assume the chairmanship", "successful chairmanship"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("trade barrier", "n.phr", "hàng rào thuế quan và mậu dịch", "/ˈtreɪd ˈbæriə(r)/",
         "AFTA agreements dismantle technical and tariff trade barriers across Southeast Asia.",
         "Hiệp định AFTA dỡ bỏ các hàng rào thuế quan và kỹ thuật trên khắp Đông Nam Á.",
         ["lower trade barriers", "remove trade barriers"],
         "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&q=80"),
        ("connectivity", "n", "sự kết nối giao thông và số hóa", "/ˌkɒnekˈtɪvəti/",
         "Master plans for ASEAN connectivity link highways, fiber optics, and power grids.",
         "Kế hoạch tổng thể về kết nối ASEAN liên kết đường cao tốc, cáp quang và lưới điện.",
         ["enhance connectivity", "regional connectivity"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-5-global-warming": [
        ("carbon capture", "n.phr", "công nghệ thu giữ và chôn lấp carbon", "/ˈkɑːbən ˈkæptʃə(r)/",
         "Carbon capture technology traps factory emissions and stores them deep underground.",
         "Công nghệ thu giữ carbon chặn khí thải nhà máy và chôn lấp sâu dưới lòng đất.",
         ["invest in carbon capture", "carbon capture and storage"],
         "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80"),
        ("tipping point", "n.phr", "điểm bùng phát khí hậu không thể đảo ngược", "/ˈtɪpɪŋ pɔɪnt/",
         "Scientists warn that Amazon forest loss is dangerously near an irreversible tipping point.",
         "Các nhà khoa học cảnh báo mất rừng Amazon đang tiến gần điểm bùng phát nguy hiểm.",
         ["reach a tipping point", "climate tipping point"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("methane emissions", "n.phr", "khí thải metan gây nóng lên toàn cầu", "/ˈmiːθeɪn ɪˈmɪʃnz/",
         "Methane emissions from animal husbandry trap heat eighty times faster than carbon dioxide.",
         "Khí thải metan từ chăn nuôi giữ nhiệt gấp tám mươi lần so với khí CO2.",
         ["cut methane emissions", "reduce methane emissions"],
         "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80"),
        ("afforestation", "n", "trồng rừng phủ xanh đất trống đồi trọc", "/æˌfɒrɪˈsteɪʃn/",
         "National afforestation campaigns absorb hundreds of thousands of tons of emissions.",
         "Các chiến dịch trồng rừng phủ xanh hấp thụ hàng trăm ngàn tấn khí thải nhà kính.",
         ["support afforestation", "large-scale afforestation"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("climate refugee", "n.phr", "người tị nạn do biến đổi khí hậu", "/ˈklaɪmət ˌrefjuˈdʒiː/",
         "Rising sea waters may force millions of delta residents to become climate refugees.",
         "Mực nước biển dâng cao có thể buộc hàng triệu cư dân đồng bằng phải tị nạn khí hậu.",
         ["protect climate refugees", "plight of climate refugees"],
         "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"),
        ("greenhouse gas inventory", "n.phr", "kiểm kê lượng phát thải khí nhà kính", "/ˈɡriːnhaʊs ɡæs ˈɪnvəntri/",
         "Enterprises must submit an annual greenhouse gas inventory to environmental authorities.",
         "Các doanh nghiệp phải nộp báo cáo kiểm kê khí nhà kính hàng năm cho cơ quan môi trường.",
         ["conduct a greenhouse gas inventory", "national inventory"],
         "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80"),
        ("carbon footprint audit", "n.phr", "kiểm toán đo lường dấu chân carbon", "/ˈkɑːbən ˈfʊtprɪnt ˈɔːdɪt/",
         "The green university underwent a comprehensive carbon footprint audit.",
         "Ngôi trường đại học xanh đã thực hiện kiểm toán toàn diện về dấu chân carbon.",
         ["carry out a carbon audit", "carbon footprint audit report"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("energy transition", "n.phr", "chuyển dịch cơ cấu năng lượng xanh", "/ˈenədʒi trænˈzɪʃn/",
         "The national energy transition replaces coal generators with offshore wind turbines.",
         "Chuyển dịch năng lượng quốc gia thay thế nhiệt điện than bằng tua-bin gió ngoài khơi.",
         ["just energy transition", "accelerate energy transition"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-7-education-options-for-school-leavers": [
        ("scholarship recipient", "n.phr", "người vinh dự được nhận học bổng", "/ˈskɒləʃɪp rɪˈsɪpiənt/",
         "The scholarship recipient thanked her teachers for their unwavering encouragement.",
         "Nữ sinh nhận học bổng đã gửi lời cảm ơn sâu sắc tới thầy cô vì sự động viên không ngừng.",
         ["proud scholarship recipient", "annual scholarship recipient"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("postgraduate degree", "n.phr", "bằng sau đại học (thạc sĩ, tiến sĩ)", "/ˌpəʊstˈɡrædʒuət dɪˈɡriː/",
         "She enrolled in a postgraduate degree in artificial intelligence and robotics.",
         "Cô ấy đã đăng ký học bằng sau đại học về trí tuệ nhân tạo và chế tạo robot.",
         ["pursue a postgraduate degree", "postgraduate degree studies"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("job placement rate", "n.phr", "tỷ lệ sinh viên có việc làm sau tốt nghiệp", "/ˈdʒɒb ˈpleɪsmənt reɪt/",
         "The technical college boasts a 98% job placement rate within six months of graduation.",
         "Trường cao đẳng kỹ thuật tự hào có tỷ lệ 98% sinh viên có việc làm sau 6 tháng tốt nghiệp.",
         ["high job placement rate", "measure job placement rates"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("hands-on workshop", "n.phr", "buổi tập huấn thực hành tay nghề", "/ˌhændz ˈɒn ˈwɜːkʃɒp/",
         "Automotive students spent four hours in the hands-on workshop diagnosing car engines.",
         "Sinh viên ngành ô tô đã dành bốn tiếng trong xưởng thực hành để chẩn đoán động cơ xe.",
         ["attend a hands-on workshop", "conduct a hands-on workshop"],
         "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80"),
        ("credit transfer", "n.phr", "chuyển đổi và công nhận tín chỉ học tập", "/ˈkredɪt trænsˈfɜː(r)/",
         "The partnership program allows easy credit transfer to international universities.",
         "Chương trình liên kết cho phép chuyển đổi tín chỉ dễ dàng sang các trường đại học quốc tế.",
         ["eligible for credit transfer", "credit transfer agreement"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("dual degree", "n.phr", "chương trình nhận song bằng đại học", "/ˌdjuːəl dɪˈɡriː/",
         "Graduating with a dual degree in business and software engineering is a great advantage.",
         "Tốt nghiệp với song bằng kinh doanh và kỹ thuật phần mềm là lợi thế cạnh tranh rất lớn.",
         ["earn a dual degree", "dual degree program"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("continuing education", "n.phr", "hệ đào tạo giáo dục thường xuyên", "/kənˌtɪnjuːɪŋ ˌedʒuˈkeɪʃn/",
         "Adults attend evening continuing education classes to learn accounting software.",
         "Người lớn tuổi tham gia các lớp giáo dục thường xuyên buổi tối để học phần mềm kế toán.",
         ["center for continuing education", "enroll in continuing education"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("academic advisor", "n.phr", "cố vấn học tập cho sinh viên", "/ˌækəˈdemɪk ədˈvaɪzə(r)/",
         "Meet with your academic advisor before selecting elective courses for the semester.",
         "Hãy gặp cố vấn học tập trước khi chọn các môn học tự chọn cho học kỳ mới.",
         ["consult an academic advisor", "guidance from academic advisors"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("probation period", "n.phr", "thời gian thử việc trước tuyển chính thức", "/prəˈbeɪʃn ˈpɪəriəd/",
         "Engineering recruits receive full coaching during their three-month probation period.",
         "Kỹ sư mới tuyển được hướng dẫn tận tình trong suốt thời gian thử việc ba tháng.",
         ["pass the probation period", "complete probation period"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("work-study program", "n.phr", "chương trình vừa học vừa làm thực tế", "/ˈwɜːk stʌdi ˈprəʊɡræm/",
         "The university work-study program allows students to earn pocket money on campus.",
         "Chương trình vừa học vừa làm của trường cho phép sinh viên kiếm thêm thu nhập tại khuôn viên.",
         ["apply for a work-study program", "benefit of work-study programs"],
         "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80"),
        ("career fair", "n.phr", "ngày hội việc làm tuyển dụng sinh viên", "/kəˈrɪə feə(r)/",
         "Dozens of multinational technology corporations set up recruitment booths at the career fair.",
         "Hàng chục tập đoàn công nghệ đa quốc gia đặt bàn tuyển dụng tại ngày hội việc làm.",
         ["attend a career fair", "annual career fair"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("practical training", "n.phr", "đào tạo thực hành tay nghề chuyên sâu", "/ˈpræktɪkl ˈtreɪnɪŋ/",
         "Hands-on practical training ensures nursing graduates administer injections accurately.",
         "Đào tạo thực hành bài bản đảm bảo sinh viên điều dưỡng tiêm truyền chính xác.",
         ["undergo practical training", "comprehensive practical training"],
         "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80"),
        ("job interview", "n.phr", "buổi phỏng vấn xin việc trực tiếp", "/ˈdʒɒb ˈɪntəvjuː/",
         "Wear professional attire and maintain polite eye contact during the job interview.",
         "Hãy mặc trang phục trang nhã và giao tiếp mắt tự tin trong buổi phỏng vấn xin việc.",
         ["pass the job interview", "job interview preparation"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("professional ethics", "n.phr", "đạo đức nghề nghiệp chuyên môn", "/prəˈfeʃənl ˈeθɪks/",
         "Medical and legal students must adhere strictly to professional ethics.",
         "Sinh viên ngành y và luật phải luôn tuân thủ nghiêm ngặt chuẩn mực đạo đức nghề nghiệp.",
         ["adhere to professional ethics", "standards of professional ethics"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-8-becoming-independent": [
        ("self-reliant living", "n.phr", "cuộc sống tự lập, tự lo liệu", "/ˌself rɪˈlaɪənt ˈlɪvɪŋ/",
         "Self-reliant living involves cooking, washing clothes, and budgeting personal funds.",
         "Sống tự lập bao gồm tự nấu nướng, giặt giũ và cân đối chi tiêu cá nhân.",
         ["embrace self-reliant living", "skills for self-reliant living"],
         "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80"),
        ("financial prudence", "n.phr", "sự thận trọng và khôn ngoan về tài chính", "/faɪˈnænʃl ˈpruːdns/",
         "Practicing financial prudence prevents college students from accumulating credit debts.",
         "Thận trọng trong chi tiêu giúp sinh viên đại học không bị vướng vào nợ nần thẻ tín dụng.",
         ["exercise financial prudence", "principles of financial prudence"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("grocery budgeting", "n.phr", "lập ngân sách chi tiêu mua thực phẩm", "/ˈɡrəʊsəri ˈbʌdʒɪtɪŋ/",
         "Planning weekly meals ahead of time makes grocery budgeting far more efficient.",
         "Lên thực đơn tuần trước giúp việc dự toán tiền đi chợ hiệu quả hơn rất nhiều.",
         ["practice grocery budgeting", "grocery budgeting tips"],
         "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80"),
        ("household maintenance", "n.phr", "bảo trì, chăm sóc nhà cửa đồ đạc", "/ˈhaʊshəʊld ˈmeɪntənəns/",
         "Basic household maintenance like unblocking sinks saves considerable repair expenses.",
         "Bảo trì nhà cửa cơ bản như thông tắc bồn rửa giúp tiết kiệm chi phí gọi thợ.",
         ["learn household maintenance", "routine household maintenance"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("personal boundary", "n.phr", "ranh giới cá nhân trong quan hệ xã hội", "/ˈpɜːsənl ˈbaʊndri/",
         "Setting healthy personal boundaries ensures roommates respect your quiet study hours.",
         "Thiết lập ranh giới cá nhân rõ ràng giúp bạn cùng phòng tôn trọng giờ tự học của bạn.",
         ["establish personal boundaries", "respect personal boundaries"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("stress management", "n.phr", "kỹ năng quản lý và giải tỏa căng thẳng", "/ˈstres ˌmænɪdʒmənt/",
         "Regular exercise and meditation are proven stress management techniques for teens.",
         "Tập thể dục đều đặn và thiền là các phương pháp xả stress đã được chứng minh hiệu quả.",
         ["practice stress management", "stress management seminar"],
         "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80"),
        ("self-advocacy", "n", "khả năng tự lên tiếng bảo vệ quyền lợi bản thân", "/ˌself ˈædvəkəsi/",
         "Developing self-advocacy helps college freshmen speak up when unfair grades occur.",
         "Rèn luyện kỹ năng tự lên tiếng giúp tân sinh viên biết bảo vệ quyền lợi khi có nhầm lẫn điểm số.",
         ["practice self-advocacy", "learn self-advocacy"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("mental resilience", "n.phr", "nghị lực tinh thần vững vàng trước sóng gió", "/ˌmentl rɪˈzɪliəns/",
         "Facing setbacks builds mental resilience that prepares you for adult career challenges.",
         "Đối mặt với khó khăn giúp bồi đắp nghị lực tinh thần chuẩn bị cho sự nghiệp sau này.",
         ["foster mental resilience", "build mental resilience"],
         "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80"),
        ("punctuality", "n", "tác phong đúng giờ giấc kỷ luật", "/ˌpʌŋktʃuˈæləti/",
         "Punctuality reflects personal respect for your teachers and fellow study group members.",
         "Đúng giờ thể hiện sự tôn trọng của bạn đối với thầy cô và các bạn trong nhóm học tập.",
         ["strict punctuality", "importance of punctuality"],
         "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80"),
        ("autonomous", "adj", "tự chủ, có khả năng tự vận hành", "/ɔːˈtɒnəməs/",
         "Independent students become autonomous decision-makers who don't rely on constant reminders.",
         "Học sinh tự lập trở thành những người tự chủ ra quyết định mà không cần ai phải nhắc nhở.",
         ["autonomous learner", "autonomous individual"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("accountability", "n", "tinh thần tự chịu trách nhiệm về kết quả", "/əˌkaʊntəˈbɪləti/",
         "Personal accountability means holding yourself responsible for meeting study milestones.",
         "Tinh thần tự chịu trách nhiệm là tự cam kết hoàn thành các mục tiêu học tập đề ra.",
         ["take accountability", "sense of accountability"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("frugality", "n", "đức tính tiết kiệm, không lãng phí", "/fruːˈɡæləti/",
         "Practicing frugality allowed the student to save enough money for a new laptop.",
         "Thực hành tính tiết kiệm đã giúp bạn sinh viên dành dụm đủ tiền mua máy tính xách tay mới.",
         ["embrace frugality", "habit of frugality"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("first-aid skill", "n.phr", "kỹ năng sơ cấp cứu khẩn cấp cơ bản", "/ˈfɜːst eɪd skɪl/",
         "Every teenager living alone should master basic first-aid skills like treating burns.",
         "Mọi bạn trẻ sống tự lập nên nắm vững kỹ năng sơ cứu cơ bản như xử lý vết bỏng.",
         ["learn first-aid skills", "essential first-aid skills"],
         "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80"),
        ("daily routine", "n.phr", "thói quen sinh hoạt nề nếp hàng ngày", "/ˈdeɪli ruːˈtiːn/",
         "A structured daily routine of regular sleep and study maximizes productivity.",
         "Thói quen sinh hoạt nề nếp ngủ nghỉ và học tập khoa học giúp tối ưu hóa năng suất.",
         ["stick to a daily routine", "healthy daily routine"],
         "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80"),
        ("resourcefulness", "n", "sự tháo vát, biết xoay xở linh hoạt", "/rɪˈzɔːsflnəs/",
         "Living independently builds resourcefulness when cooking with limited ingredients.",
         "Sống tự lập rèn luyện sự tháo vát khi phải nấu bữa cơm với những nguyên liệu sẵn có.",
         ["demonstrate resourcefulness", "practical resourcefulness"],
         "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"),
        ("self-awareness", "n", "sự tự nhận thức rõ điểm mạnh yếu bản thân", "/ˌself əˈweənəs/",
         "Developing honest self-awareness helps you choose realistic academic and career goals.",
         "Tự nhận thức rõ bản thân giúp bạn lựa chọn các mục tiêu học tập và nghề nghiệp thực tế.",
         ["heighten self-awareness", "accurate self-awareness"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("perseverance", "n", "lòng kiên trì theo đuổi mục tiêu", "/ˌpɜːsəˈvɪərəns/",
         "Success in independent college research requires continuous focus and perseverance.",
         "Thành công trong nghiên cứu đại học tự lập đòi hỏi sự tập trung và lòng kiên trì không ngừng.",
         ["display perseverance", "reward for perseverance"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("self-care routine", "n.phr", "thói quen tự chăm sóc bản thân", "/ˌself ˈkeə ruːˌtiːn/",
         "Taking an evening walk and drinking water are simple components of a self-care routine.",
         "Đi dạo buổi tối và uống đủ nước là những thói quen đơn giản để tự chăm sóc cơ thể.",
         ["maintain a self-care routine", "daily self-care routine"],
         "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-9-social-issues": [
        ("social safety", "n.phr", "an toàn trật tự xã hội khu dân cư", "/ˈsəʊʃl ˈseɪfti/",
         "Neighborhood watch programs enhance social safety and prevent petty street theft.",
         "Các tổ dân phòng tuần tra giúp nâng cao an toàn xã hội và phòng chống trộm cắp vặt.",
         ["ensure social safety", "social safety measures"],
         "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80"),
        ("school bullying", "n.phr", "bạo lực và bắt nạt học đường", "/skuːl ˈbʊliɪŋ/",
         "Schools organize open assemblies to educate students on combating school bullying.",
         "Nhà trường tổ chức các buổi sinh hoạt dưới cờ để giáo dục học sinh phòng chống bạo lực học đường.",
         ["eradicate school bullying", "victims of school bullying"],
         "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80"),
        ("mental well-being", "n.phr", "sức khỏe tinh thần an yên, lành mạnh", "/ˌmentl ˈwel biːɪŋ/",
         "Regular physical sports in fresh air promote both physical fitness and mental well-being.",
         "Tập thể thao ngoài trời nâng cao cả thể lực lẫn sức khỏe tinh thần an yên.",
         ["nurture mental well-being", "enhance mental well-being"],
         "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80"),
        ("community support", "n.phr", "sự hỗ trợ đùm bọc từ cộng đồng", "/kəˈmjuːnəti səˈpɔːt/",
         "Vulnerable orphans thrive when they receive affectionate community support.",
         "Trẻ mồ côi thiệt thòi sẽ lớn khôn khi nhận được sự đùm bọc yêu thương của cộng đồng.",
         ["rally community support", "rely on community support"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("social alienation", "n.phr", "sự cô lập và xa lánh xã hội", "/ˈsəʊʃl ˌeɪliəˈneɪʃn/",
         "Spending twelve hours a day online causes severe social alienation from real peers.",
         "Dành 12 tiếng mỗi ngày trên mạng gây ra sự cô lập xã hội nghiêm trọng khỏi bạn bè ngoài đời.",
         ["suffer from social alienation", "overcome social alienation"],
         "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80"),
        ("digital addiction", "n.phr", "chứng nghiện thiết bị kỹ thuật số", "/ˈdɪdʒɪtl əˈdɪkʃn/",
         "Setting phone curfew hours at night is an effective way to beat digital addiction.",
         "Quy định giờ cất điện thoại ban đêm là cách hiệu quả để chữa chứng nghiện thiết bị số.",
         ["break digital addiction", "signs of digital addiction"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("child protection", "n.phr", "công tác bảo vệ chăm sóc trẻ em", "/ˈtʃaɪld prəˈtekʃn/",
         "The national hotline 111 provides round-the-clock emergency child protection services.",
         "Tổng đài quốc gia 111 cung cấp dịch vụ bảo vệ trẻ em khẩn cấp suốt 24/7.",
         ["child protection law", "advocate child protection"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("delinquent behavior", "n.phr", "hành vi vi phạm pháp luật tuổi vị thành niên", "/dɪˈlɪŋkwənt bɪˈheɪvjə(r)/",
         "Caring mentorship helps troubled adolescents turn away from delinquent behavior.",
         "Sự kèm cặp yêu thương giúp thiếu niên lầm lỡ từ bỏ các hành vi vi phạm pháp luật.",
         ["curb delinquent behavior", "signs of delinquent behavior"],
         "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80"),
        ("psychological counseling", "n.phr", "tư vấn và tham vấn tâm lý chuyên sâu", "/ˌsaɪkəˈlɒdʒɪkl ˈkaʊnsəlɪŋ/",
         "High schools provide free psychological counseling for students facing academic burnout.",
         "Các trường THPT cung cấp dịch vụ tư vấn tâm lý miễn phí cho học sinh bị kiệt sức thi cử.",
         ["seek psychological counseling", "receive psychological counseling"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("social justice", "n.phr", "công bằng và lẽ phải trong xã hội", "/ˈsəʊʃl ˈdʒʌstɪs/",
         "Equal access to clean water and healthcare is fundamental to social justice.",
         "Tiếp cận bình đẳng với nước sạch và y tế là nền tảng cốt lõi của công bằng xã hội.",
         ["fight for social justice", "champion social justice"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("inclusive society", "n.phr", "xã hội hòa nhập, không ai bị bỏ lại phía sau", "/ɪnˈkluːsɪv səˈsaɪəti/",
         "Building barrier-free sidewalks for wheelchairs helps foster an inclusive society.",
         "Xây dựng vỉa hè không rào cản cho xe lăn giúp xây dựng một xã hội hòa nhập văn minh.",
         ["build an inclusive society", "promote an inclusive society"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("substance dependency", "n.phr", "sự lệ thuộc vào chất kích thích", "/ˈsʌbstəns dɪˈpendənsi/",
         "Early medical intervention halts the progression of dangerous substance dependency.",
         "Can thiệp y tế sớm giúp ngăn chặn sự tiến triển của tình trạng lệ thuộc chất độc hại.",
         ["treat substance dependency", "overcome substance dependency"],
         "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80"),
        ("vulnerable population", "n.phr", "nhóm dân cư yếu thế cần được chở che", "/ˈvʌlnərəbl ˌpɒpjuˈleɪʃn/",
         "Social workers distribute warm blankets and canned food to vulnerable populations.",
         "Các cán bộ xã hội trao tặng chăn ấm và đồ hộp cho các nhóm dân cư yếu thế.",
         ["protect vulnerable populations", "support vulnerable populations"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("anti-bullying campaign", "n.phr", "chiến dịch phòng chống bắt nạt học đường", "/ˌænti ˈbʊliɪŋ kæmˈpeɪn/",
         "Students created colorful posters as part of the nationwide anti-bullying campaign.",
         "Các em học sinh vẽ tranh cổ động hưởng ứng chiến dịch phòng chống bạo lực học đường toàn quốc.",
         ["join an anti-bullying campaign", "school anti-bullying campaign"],
         "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80"),
        ("family breakdown", "n.phr", "sự đổ vỡ hôn nhân và rạn nứt gia đình", "/ˈfæməli ˈbreɪkdaʊn/",
         "Counselors provide emotional support to adolescents coping with family breakdown.",
         "Các chuyên gia tâm lý hỗ trợ cảm xúc cho thanh thiếu niên đối mặt với sự đổ vỡ gia đình.",
         ["cope with family breakdown", "effects of family breakdown"],
         "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=800&q=80"),
        ("homelessness", "n", "tình trạng vô gia cư không nơi nương tựa", "/ˈhəʊmləsnəs/",
         "Municipal social housing initiatives aim to eliminate urban homelessness permanently.",
         "Các đề án nhà ở xã hội của thành phố hướng tới việc xóa bỏ vĩnh viễn nạn vô gia cư.",
         ["tackle homelessness", "eradicate homelessness"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("emotional distress", "n.phr", "nỗi đau đớn và khủng hoảng cảm xúc", "/ɪˈməʊʃənl dɪˈstres/",
         "Online harassment can inflict severe, long-lasting emotional distress on teenagers.",
         "Quấy rối trên mạng có thể gây ra nỗi khủng hoảng cảm xúc đau đớn kéo dài cho tuổi teen.",
         ["suffer emotional distress", "alleviate emotional distress"],
         "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80"),
        ("public awareness", "n.phr", "nhận thức hiểu biết của công chúng xã hội", "/ˈpʌblɪk əˈweənəs/",
         "Media campaigns raise public awareness regarding teenage mental health support.",
         "Các chiến dịch truyền thông nâng cao nhận thức cộng đồng về chăm sóc sức khỏe tâm thần tuổi teen.",
         ["raise public awareness", "heightened public awareness"],
         "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80"),
        ("social cohesion", "n.phr", "sự gắn kết tương thân tương ái trong xã hội", "/ˈsəʊʃl kəʊˈhiːʒn/",
         "Cultural festivals and community sports build strong bonds of social cohesion.",
         "Các lễ hội văn hóa và thể thao cộng đồng xây đắp mối gắn kết xã hội bền chặt.",
         ["strengthen social cohesion", "foster social cohesion"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("peer support group", "n.phr", "nhóm bạn bè hỗ trợ đồng đẳng", "/ˈpɪə səˈpɔːt ɡruːp/",
         "Joining a peer support group provides a safe space to share anxiety and overcome fears.",
         "Tham gia nhóm hỗ trợ đồng đẳng mang lại không gian an toàn để sẻ chia lo âu và vượt qua sợ hãi.",
         ["facilitate a peer support group", "benefits of peer support groups"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("civic duty", "n.phr", "nghĩa vụ và trách nhiệm công dân", "/ˈsɪvɪk ˈdjuːti/",
         "Reporting domestic violence or child abuse to police hotlines is a civic duty.",
         "Báo cáo bạo lực gia đình hoặc bạo hành trẻ em cho đường dây nóng là nghĩa vụ công dân.",
         ["fulfill your civic duty", "sense of civic duty"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-10-the-ecosystem": [
        ("marine ecosystem", "n.phr", "hệ sinh thái biển đại dương", "/məˈriːn ˈiːkəʊsɪstəm/",
         "Coral reefs and mangrove forests are cornerstones of a healthy marine ecosystem.",
         "Rạn san hô và rừng ngập mặn là những nền tảng của một hệ sinh thái biển khỏe mạnh.",
         ["protect marine ecosystems", "fragile marine ecosystem"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("terrestrial ecosystem", "n.phr", "hệ sinh thái trên cạn lục địa", "/təˈrestriəl ˈiːkəʊsɪstəm/",
         "Tropical savannahs and temperate pine forests are diverse terrestrial ecosystems.",
         "Xavan nhiệt đới và rừng thông ôn đới là các hệ sinh thái trên cạn đa dạng.",
         ["terrestrial ecosystem diversity", "study terrestrial ecosystems"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("biosphere", "n", "sinh quyển bao quanh trái đất", "/ˈbaɪəʊsfɪə(r)/",
         "Human pollution threatens to destabilize delicate biochemical cycles across the biosphere.",
         "Ô nhiễm do con người gây ra đe dọa làm mất cân bằng các chu trình sinh hóa trong sinh quyển.",
         ["protect the biosphere", "global biosphere"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("trophic cascade", "n.phr", "hiệu ứng thác dinh dưỡng lan truyền", "/ˈtrəʊfɪk kæˈskeɪd/",
         "Reintroducing wolves triggered a beneficial trophic cascade that restored riverbanks.",
         "Tái thả loài sói đã kích hoạt hiệu ứng thác dinh dưỡng giúp hồi sinh những bờ sông.",
         ["trigger a trophic cascade", "ecological trophic cascade"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80"),
        ("symbiosis", "n", "mối quan hệ cộng sinh tương hỗ", "/ˌsɪmbaɪˈəʊsɪs/",
         "Clownfish and sea anemones live in a classic mutual symbiosis for mutual protection.",
         "Cá hề và hải quỳ sống trong mối quan hệ cộng sinh tương hỗ kinh điển để bảo vệ lẫn nhau.",
         ["mutual symbiosis", "live in symbiosis"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("keystone predator", "n.phr", "loài săn mồi chủ chốt định hình hệ sinh thái", "/ˈkiːstəʊn ˈpredətə(r)/",
         "The sea otter is a keystone predator that prevents sea urchins from mowing down kelp.",
         "Rái cá biển là loài săn mồi chủ chốt ngăn nhím biển gặm sạch các thảm tảo bẹ.",
         ["role of keystone predators", "protect keystone predators"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("nutrient cycle", "n.phr", "chu trình tuần hoàn dinh dưỡng tự nhiên", "/ˈnjuːtriənt ˈsaɪkl/",
         "Decomposers like worms and earth fungi drive the essential soil nutrient cycle.",
         "Sinh vật phân giải như giun và nấm đất vận hành chu trình dinh dưỡng thiết yếu trong đất.",
         ["maintain nutrient cycles", "disrupt nutrient cycles"],
         "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80"),
        ("carrying capacity", "n.phr", "sức tải tối đa của môi trường sống", "/ˈkæriɪŋ kəˌpæsəti/",
         "Overpopulation exceeds the carrying capacity of grazing pastures, causing desertification.",
         "Quá tải số lượng vượt sức chứa của đồng cỏ, dẫn đến hiện tượng sa mạc hóa.",
         ["exceed carrying capacity", "environmental carrying capacity"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("endemic species", "n.phr", "loài đặc hữu duy nhất của một vùng", "/enˈdemɪk ˈspiːʃiːz/",
         "The Tonkin snub-nosed monkey is an endemic species found only in northern Vietnam.",
         "Voọc mũi hếch là loài đặc hữu quý hiếm chỉ tìm thấy tại vùng núi phía Bắc Việt Nam.",
         ["shelter endemic species", "rare endemic species"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80"),
        ("primary producer", "n.phr", "sinh vật sản xuất sơ cấp (thực vật quang hợp)", "/ˈpraɪməri prəˈdjuːsə(r)/",
         "Green plants and microscopic phytoplankton are the primary producers of organic sugars.",
         "Cây xanh và thực vật phù du là những sinh vật sản xuất sơ cấp tạo nên các hợp chất hữu cơ.",
         ["role of primary producers", "aquatic primary producers"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("biodiversity assessment", "n.phr", "đánh giá khảo sát đa dạng sinh học", "/ˌbaɪəʊdaɪˈvɜːsəti əˈsesmənt/",
         "Biologists conducted a comprehensive biodiversity assessment before park expansion.",
         "Các nhà sinh vật học đã tiến hành khảo sát đa dạng sinh học toàn diện trước khi mở rộng vườn.",
         ["conduct a biodiversity assessment", "rigorous assessment"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("ecological niche", "n.phr", "vị trí ổ sinh thái trong sinh cảnh", "/ˌiːkəˈlɒdʒɪkl niːʃ/",
         "No two competing species can stably occupy the exact same ecological niche indefinitely.",
         "Không có hai loài cạnh tranh nào có thể cùng chiếm giữ chung một ổ sinh thái mãi mãi.",
         ["occupy a distinct niche", "specialized ecological niche"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("photosynthesis", "n", "quá trình quang hợp hấp thụ ánh sáng", "/ˌfəʊtəʊˈsɪnθəsɪs/",
         "Through photosynthesis, green forest foliage converts carbon dioxide and sunlight into oxygen.",
         "Qua quang hợp, tán lá rừng xanh chuyển đổi khí carbon dioxide và ánh nắng thành oxy.",
         ["rate of photosynthesis", "process of photosynthesis"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80"),
        ("biodiversity preservation", "n.phr", "gìn giữ và bảo tồn đa dạng sinh thái", "/ˌbaɪəʊdaɪˈvɜːsəti ˌprezəˈveɪʃn/",
         "Biodiversity preservation in national parks safeguards irreplaceable gene pools.",
         "Bảo tồn đa dạng sinh học trong các vườn quốc gia bảo vệ các nguồn gen vô giá không thể thay thế.",
         ["fund biodiversity preservation", "commit to preservation"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80")
    ]
}

# Update expanded-vocab-g11.ts
g11_file = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "curriculum", "expanded-vocab-g11.ts")
with open(g11_file, "r", encoding="utf-8") as f:
    g11_text = f.read()

for unit_slug, extra_items in G11_EXTRA.items():
    search_str = f'"{unit_slug}": ['
    idx = g11_text.find(search_str)
    if idx != -1:
        close_idx = g11_text.find('  ],', idx)
        if close_idx != -1:
            new_lines = []
            for item in extra_items:
                word, pos, vi, ipa, en_ex, vi_ex, colocs, img = item
                clean_id = f"v11-boost-{word.lower().replace(' ', '-').replace('/', '-')}"
                audio = f"https://dict.youdao.com/dictvoice?audio={word.replace(' ', '+')}&type=2"
                new_lines.append('    ,')
                new_lines.append('    {')
                new_lines.append(f'      id: {json.dumps(clean_id)},')
                new_lines.append(f'      word: {json.dumps(word)},')
                new_lines.append(f'      partOfSpeech: {json.dumps(pos)},')
                new_lines.append(f'      meaningVi: {json.dumps(vi)},')
                new_lines.append(f'      ipa: {json.dumps(ipa)},')
                new_lines.append(f'      audioUrl: {json.dumps(audio)},')
                new_lines.append(f'      imageUrl: {json.dumps(img)},')
                new_lines.append(f'      exampleEn: {json.dumps(en_ex)},')
                new_lines.append(f'      exampleVi: {json.dumps(vi_ex)},')
                new_lines.append(f'      collocations: {json.dumps(colocs)}')
                new_lines.append('    }')
            insert_content = "\n".join(new_lines)
            g11_text = g11_text[:close_idx] + insert_content + "\n" + g11_text[close_idx:]

with open(g11_file, "w", encoding="utf-8") as f:
    f.write(g11_text)

print("Successfully injected booster words into Grade 11!")
