# -*- coding: utf-8 -*-
"""
Boost Units 3 to 10 of Grade 10 to reach 80 words per unit!
"""
import json
import os

G10_REMAINING = {
    "unit-3-music": [
        ("melody", "n", "giai điệu bài hát du dương", "/ˈmelədi/",
         "The sweet violin melody lingered in the concert hall long after the performance ended.",
         "Giai điệu vĩ cầm ngọt ngào còn ngân vang trong khán phòng rất lâu sau khi buổi biểu diễn kết thúc.",
         ["catchy melody", "haunting melody"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("harmony", "n", "sự hòa âm phối khí du dương", "/ˈhɑːməni/",
         "The choir singers blended their voices in sublime four-part harmony.",
         "Dàn hợp xướng hòa giọng trong bản hòa âm bốn bè tuyệt mỹ.",
         ["vocal harmony", "rich harmonies"],
         "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80"),
        ("rhythm section", "n.phr", "bộ phận tiết tấu trống và bass trong ban nhạc", "/ˈrɪðəm ˈsekʃn/",
         "A tight rhythm section keeps the jazz ensemble synchronized.",
         "Bộ phận gõ tiết tấu chắc nhịp giúp ban nhạc jazz giữ được sự đồng điệu.",
         ["solid rhythm section", "drive the rhythm section"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("orchestra conductor", "n.phr", "nhạc trưởng chỉ huy dàn nhạc giao hưởng", "/ˈɔːkɪstrə kənˈdʌktə(r)/",
         "The orchestra conductor raised his baton and the grand overture commenced.",
         "Vị nhạc trưởng giơ đũa chỉ huy và khúc dạo đầu hoành tráng bắt đầu cất lên.",
         ["renowned orchestra conductor", "cue from conductor"],
         "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80"),
        ("musical score", "n.phr", "bản tổng phổ ghi nốt nhạc", "/ˈmjuːzɪkl skɔː(r)/",
         "Pianists read complex musical scores effortlessly during recitals.",
         "Nghệ sĩ piano đọc các bản tổng phổ phức tạp một cách thuần thục trong buổi độc tấu.",
         ["read a musical score", "compose a score"],
         "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=800&q=80"),
        ("percussion instrument", "n.phr", "nhạc cụ gõ như trống hay thanh la", "/pəˈkʌʃn ˈɪnstrəmənt/",
         "Xylophones and kettle drums belong to the percussion instrument family.",
         "Mộc cầm và trống định âm thuộc bộ nhạc cụ gõ trong dàn nhạc.",
         ["play percussion instruments", "traditional percussion instruments"],
         "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80"),
        ("string quartet", "n.phr", "tứ tấu đàn dây thính phòng", "/strɪŋ kwɔːˈtet/",
         "The string quartet delivered an intimate rendition of Beethoven's compositions.",
         "Tứ tấu đàn dây mang lại màn biểu diễn ấm cúng các tác phẩm của Beethoven.",
         ["award-winning string quartet", "classical string quartet"],
         "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80"),
        ("vocal timbre", "n.phr", "âm sắc và màu giọng đặc trưng của ca sĩ", "/ˈvəʊkl ˈtæmbə(r)/",
         "Her warm vocal timbre makes emotional ballads unforgettable.",
         "Âm sắc giọng hát ấm áp của cô khiến những bản ballad trữ tình trở nên khó quên.",
         ["unique vocal timbre", "rich vocal timbre"],
         "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=800&q=80"),
        ("folk ballad", "n.phr", "bài dân ca trữ tình quê hương", "/fəʊk ˈbæləd/",
         "The folk ballad recounts ancient legends of mountain villages.",
         "Bản dân ca trữ tình kể lại những truyền thuyết cổ xưa của các bản làng vùng cao.",
         ["sing folk ballads", "haunting folk ballad"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("acoustic guitar", "n.phr", "đàn ghi-ta mộc", "/əˈkuːstɪk ɡɪˈtɑː(r)/",
         "He unplugged the electric gear and strummed a wooden acoustic guitar.",
         "Anh rút phích cắm dàn điện và gảy những nốt êm đềm trên cây ghi-ta mộc.",
         ["play acoustic guitar", "strum acoustic guitar"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("music conservatory", "n.phr", "nhạc viện đào tạo âm nhạc chuyên nghiệp", "/ˈmjuːzɪk kənˈsɜːvətri/",
         "Talented violinists audition rigorously to enter the national music conservatory.",
         "Các nghệ sĩ violin tài năng thi tuyển gắt gao để bước chân vào nhạc viện quốc gia.",
         ["study at a conservatory", "prestigious conservatory"],
         "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=800&q=80"),
        ("chart-topping hit", "n.phr", "bài hát đứng đầu các bảng xếp hạng âm nhạc", "/tʃɑːt ˈtɒpɪŋ hɪt/",
         "Their summer single became a chart-topping hit across digital streaming services.",
         "Đĩa đơn mùa hè của họ trở thành bản hit đứng đầu bảng xếp hạng trên các nền tảng số.",
         ["release a chart-topping hit", "produce hits"],
         "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80"),
        ("live performance", "n.phr", "buổi biểu diễn trực tiếp trên sân khấu", "/laɪv pəˈfɔːməns/",
         "Nothing replicates the electrifying energy of a stadium live performance.",
         "Không điều gì có thể thay thế được nguồn năng lượng bùng nổ của một buổi diễn trực tiếp.",
         ["give a live performance", "thrilling live performance"],
         "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80"),
        ("music genre", "n.phr", "thể loại âm nhạc", "/ˈmjuːzɪk ˈʒɒnrə/",
         "Teenagers frequently explore diverse music genres from hip-hop to indie folk.",
         "Giới trẻ thường khám phá các dòng nhạc đa dạng từ hip-hop tới indie folk.",
         ["explore music genres", "popular music genre"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("stage lighting", "n.phr", "hệ thống ánh sáng sân khấu biểu diễn", "/steɪdʒ ˈlaɪtɪŋ/",
         "Dynamic stage lighting synced perfectly with the drum crescendos.",
         "Ánh sáng sân khấu chuyển động ăn khớp hoàn hảo theo từng nhịp trống dồn dập.",
         ["spectacular stage lighting", "lighting designer"],
         "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80"),
        ("fan community", "n.phr", "cộng đồng người hâm mộ trung thành", "/fæn kəˈmjuːnəti/",
         "A global fan community organized philanthropic drives to celebrate the album launch.",
         "Cộng đồng người hâm mộ toàn cầu đã tổ chức chiến dịch thiện nguyện mừng ra mắt album.",
         ["passionate fan community", "build a fan community"],
         "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=800&q=80"),
        ("record label", "n.phr", "hãng thu âm và phát hành âm nhạc", "/ˈrekɔːd ˈleɪbl/",
         "Independent artists often launch their own record labels to retain creative freedom.",
         "Các nghệ sĩ độc lập thường lập hãng đĩa riêng để giữ trọn quyền tự do sáng tạo.",
         ["sign with a record label", "major record label"],
         "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=800&q=80"),
        ("musical prodigy", "n.phr", "thần đồng âm nhạc xuất chúng", "/ˈmjuːzɪkl ˈprɒdədʒi/",
         "Mozart was a renowned musical prodigy who composed sonatas at age five.",
         "Mozart là thần đồng âm nhạc lừng danh, người đã sáng tác bản sonata khi mới lên năm.",
         ["celebrated musical prodigy", "child prodigy"],
         "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=800&q=80"),
        ("sound engineer", "n.phr", "kỹ sư âm thanh phòng thu và sân khấu", "/saʊnd ˌendʒɪˈnɪə(r)/",
         "The sound engineer balanced the microphone levels to prevent audio feedback.",
         "Kỹ sư âm thanh cân chỉnh micro để tránh hiện tượng dội âm khó chịu.",
         ["skilled sound engineer", "work as a sound engineer"],
         "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=800&q=80"),
        ("debut album", "n.phr", "album đầu tay ra mắt công chúng", "/ˈdeɪbjuː ˈælbəm/",
         "Her debut album garnered widespread acclaim from leading music critics.",
         "Album đầu tay của cô nhận được sự khen ngợi nồng nhiệt từ giới phê bình âm nhạc.",
         ["release a debut album", "critically acclaimed debut album"],
         "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80"),
        ("audition", "n", "buổi thử giọng hoặc diễn thử", "/ɔːˈdɪʃn/",
         "Hundreds of aspiring vocalists lined up early for the talent show audition.",
         "Hàng trăm giọng ca trẻ xếp hàng từ sớm để tham gia buổi thử giọng cuộc thi tài năng.",
         ["pass the audition", "attend an audition"],
         "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=800&q=80"),
        ("musical rhythm", "n.phr", "nhịp điệu và tiết tấu âm nhạc", "/ˈmjuːzɪkl ˈrɪðəm/",
         "Traditional drumming conveys a powerful musical rhythm that gets crowds dancing.",
         "Tiếng trống truyền thống mang lại nhịp điệu rộn rã khiến đám đông muốn nhún nhảy.",
         ["infectious musical rhythm", "syncopated rhythm"],
         "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80"),
        ("lyricist", "n", "người viết lời bài hát", "/ˈlɪrɪsɪst/",
         "A great lyricist captures poetic emotions in simple, memorable verses.",
         "Một người viết lời tài ba cô đọng cảm xúc thi vị trong những câu từ dung dị dễ nhớ.",
         ["talented lyricist", "collaborate with a lyricist"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("soundtrack", "n", "nhạc nền trong phim hoặc kịch", "/ˈsaʊndtræk/",
         "The orchestral soundtrack elevated the emotional climax of the movie.",
         "Bản nhạc phim giao hưởng đã nâng tầm cao trào cảm xúc của bộ phim điện ảnh.",
         ["original soundtrack", "movie soundtrack"],
         "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=800&q=80"),
        ("music streaming service", "n.phr", "dịch vụ phát nhạc trực tuyến", "/ˈmjuːzɪk ˈstriːmɪŋ ˈsɜːvɪs/",
         "Subscribers can access millions of curated playlists on music streaming services.",
         "Người dùng có thể truy cập hàng triệu danh sách phát tuyển chọn trên các ứng dụng nghe nhạc số.",
         ["listen on streaming services", "stream music online"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("musical arrangement", "n.phr", "bản phối âm nhạc mới mẻ", "/ˈmjuːzɪkl əˈreɪndʒmənt/",
         "The jazz adaptation featured a sophisticated musical arrangement of the folk song.",
         "Bản phối mang phong cách jazz đem lại diện mạo mới đầy tinh tế cho làn điệu dân ca.",
         ["innovative musical arrangement", "masterful arrangement"],
         "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80"),
        ("folk ensemble", "n.phr", "đoàn nghệ thuật diễn tấu nhạc cụ dân tộc", "/fəʊk ɒnˈsɒmbl/",
         "The folk ensemble performed bamboo flutes and stone chimes at the festival.",
         "Đoàn diễn tấu nhạc dân tộc biểu diễn sáo trúc và đàn đá tại lễ hội văn hóa.",
         ["traditional folk ensemble", "award-winning ensemble"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("anthem", "n", "bài ca chính thức, bài quốc ca hoặc bài ca hào hùng", "/ˈænθəm/",
         "The national anthem echoes solemnly across the stadium as the flag ascends.",
         "Quốc ca vang lên trang nghiêm khắp sân vận động trong lúc lá cờ tổ quốc từ từ dâng cao.",
         ["sing the national anthem", "inspirational anthem"],
         "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80"),
        ("standing ovation", "n.phr", "sự đứng dậy vỗ tay tán thưởng nồng nhiệt", "/ˌstændɪŋ əʊˈveɪʃn/",
         "The audience erupted into a five-minute standing ovation after the final piano chord.",
         "Khán giả đồng loạt đứng dậy vỗ tay tán thưởng suốt năm phút sau hợp âm dương cầm cuối cùng.",
         ["receive a standing ovation", "give a standing ovation"],
         "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-4-for-a-better-community": [
        ("charitable foundation", "n.phr", "quỹ thiện nguyện phi lợi nhuận", "/ˈtʃærətəbl faʊnˈdeɪʃn/",
         "The charitable foundation provides scholarships to orphans in remote mountainous areas.",
         "Quỹ thiện nguyện trao học bổng cho trẻ em mồ côi tại các vùng núi xa xôi.",
         ["establish a charitable foundation", "donate to a foundation"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("civic engagement", "n.phr", "sự tham gia tích cực vào các hoạt động cộng đồng", "/ˈsɪvɪk ɪnˈɡeɪdʒmənt/",
         "High schools encourage civic engagement through regular neighborhood cleanup drives.",
         "Trường cấp 3 khuyến khích sự tham gia cộng đồng qua các đợt làm sạch khu phố định kỳ.",
         ["foster civic engagement", "active civic engagement"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("soup kitchen", "n.phr", "bếp ăn tình thương phục vụ người nghèo", "/suːp ˈkɪtʃɪn/",
         "Volunteers prepare hundreds of nutritious lunches daily at the charity soup kitchen.",
         "Các tình nguyện viên nấu hàng trăm suất cơm dinh dưỡng mỗi ngày tại bếp ăn từ thiện.",
         ["volunteer at a soup kitchen", "community soup kitchen"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("blood donation drive", "n.phr", "ngày hội hiến máu nhân đạo", "/blʌd dəʊˈneɪʃn draɪv/",
         "Red Cross youth organized a blood donation drive that collected five hundred units.",
         "Thanh niên Chữ thập đỏ tổ chức ngày hội hiến máu thu về 500 đơn vị máu quý giá.",
         ["participate in a blood donation drive", "annual donation drive"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("disadvantaged background", "n.phr", "hoàn cảnh gia đình khó khăn", "/ˌdɪsədˈvɑːntɪdʒd ˈbækɡraʊnd/",
         "Tutors offer free evening mathematics classes for children from disadvantaged backgrounds.",
         "Các gia sư mở lớp dạy toán buổi tối miễn phí cho trẻ em có hoàn cảnh gia đình khó khăn.",
         ["students from disadvantaged backgrounds", "support disadvantaged youths"],
         "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80"),
        ("shelter for the homeless", "n.phr", "mái ấm nhà mở cho người vô gia cư", "/ˈʃeltə fə ðə ˈhəʊmləs/",
         "The local shelter for the homeless provides hot meals and warm blankets in winter.",
         "Mái ấm cho người vô gia cư cung cấp bữa ăn nóng và chăn ấm trong mùa đông giá rét.",
         ["operate a homeless shelter", "seek refuge in a shelter"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("humanitarian aid", "n.phr", "hàng cứu trợ nhân đạo khẩn cấp", "/hjuːˌmænɪˈteəriən eɪd/",
         "Convoys carried essential humanitarian aid to villages isolated by landslides.",
         "Đoàn xe vận chuyển hàng cứu trợ nhân đạo khẩn cấp tới các bản làng bị cô lập do sạt lở.",
         ["deliver humanitarian aid", "provide emergency aid"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("fundraising campaign", "n.phr", "chiến dịch quyên góp quỹ ủng hộ", "/ˈfʌndreɪzɪŋ kæmˈpeɪn/",
         "The student council launched an online fundraising campaign to build a village library.",
         "Ban chấp hành học sinh khởi động chiến dịch gây quỹ trực tuyến để xây dựng thư viện xã.",
         ["launch a fundraising campaign", "exceed fundraising targets"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("social worker", "n.phr", "nhân viên công tác xã hội", "/ˈsəʊʃl ˈwɜːkə(r)/",
         "A compassionate social worker counsels teenagers facing domestic turbulence.",
         "Nhân viên công tác xã hội tận tâm tư vấn hỗ trợ thanh thiếu niên gặp bất trắc gia đình.",
         ["trained social worker", "career as a social worker"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("community center", "n.phr", "trung tâm sinh hoạt cộng đồng", "/kəˈmjuːnəti ˈsentə(r)/",
         "Elderly citizens enjoy chess matches and painting classes at the community center.",
         "Các cụ cao tuổi chơi cờ và học vẽ tranh tại nhà sinh hoạt cộng đồng của phường.",
         ["visit the community center", "programs at community centers"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("youth empowerment", "n.phr", "trao quyền và phát huy năng lực giới trẻ", "/juːθ ɪmˈpaʊəmənt/",
         "Vocational workshops advance youth empowerment in rural provinces.",
         "Các hội thảo hướng nghiệp giúp nâng cao năng lực tự chủ cho thanh niên nông thôn.",
         ["promote youth empowerment", "empowerment initiatives"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("altruistic deed", "n.phr", "hành động nhân ái vị tha", "/ˌæltruˈɪstɪk diːd/",
         "Quietly donating savings to surgery funds was a deeply altruistic deed.",
         "Âm thầm quyên góp tiền tiết kiệm vào quỹ mổ tim là một nghĩa cử nhân ái cao đẹp.",
         ["perform altruistic deeds", "spirit of altruism"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("disaster relief", "n.phr", "công tác cứu trợ thiên tai lũ lụt", "/dɪˈzɑːstə rɪˈliːf/",
         "Rescue teams coordinated disaster relief after the severe tropical storm.",
         "Đội cứu hộ điều phối công tác cứu trợ thiên tai sau cơn bão nhiệt đới dữ dội.",
         ["coordinate disaster relief", "disaster relief supplies"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("community bond", "n.phr", "tình làng nghĩa xóm gắn bó keo sơn", "/kəˈmjuːnəti bɒnd/",
         "Neighborhood festivals strengthen the heartfelt community bond among residents.",
         "Ngày hội khu phố thắt chặt thêm tình làng nghĩa xóm chân tình giữa các hộ dân.",
         ["tighten community bonds", "cherish community bonds"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("mentoring program", "n.phr", "chương trình đồng hành kèm cặp hướng dẫn", "/ˈmentɔːrɪŋ ˈprəʊɡræm/",
         "University students volunteer in a mentoring program for first-generation high schoolers.",
         "Sinh viên đại học tình nguyện tham gia chương trình kèm cặp các em học sinh khóa dưới.",
         ["establish a mentoring program", "mentor-mentee relationship"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("philanthropist", "n", "nhà hảo tâm, người làm từ thiện cống hiến cho xã hội", "/fɪˈlænθrəpɪst/",
         "The generous philanthropist funded the pediatric cardiology wing entirely.",
         "Nhà hảo tâm nhân từ đã tài trợ toàn bộ chi phí xây khoa tim mạch nhi khoa.",
         ["generous philanthropist", "acclaimed philanthropist"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("civic duty", "n.phr", "nghĩa vụ và trách nhiệm công dân", "/ˈsɪvɪk ˈdjuːti/",
         "Voting in elections and keeping public parks clean is every citizen's civic duty.",
         "Bỏ phiếu bầu cử và giữ gìn công viên sạch đẹp là nghĩa vụ công dân của mỗi người.",
         ["fulfill one's civic duty", "sense of civic duty"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("in-kind donation", "n.phr", "hiện vật đóng góp từ thiện (sách vở, áo ấm)", "/ɪn kaɪnd dəʊˈneɪʃn/",
         "The charity accepts both financial grants and in-kind donations of winter coats.",
         "Tổ chức từ thiện tiếp nhận cả tiền mặt lẫn hiện vật đóng góp như áo ấm mùa đông.",
         ["make an in-kind donation", "generous in-kind donations"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("orphanage", "n", "trại trẻ mồ côi, mái ấm tình thương", "/ˈɔːfənɪdʒ/",
         "Volunteers visit the district orphanage every Sunday afternoon to play chess with children.",
         "Tình nguyện viên ghé thăm trại trẻ mồ côi huyện mỗi chiều Chủ nhật để chơi cờ cùng các em.",
         ["visit an orphanage", "support local orphanages"],
         "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80"),
        ("nursing home", "n.phr", "viện dưỡng lão chăm sóc người cao tuổi", "/ˈnɜːsɪŋ həʊm/",
         "High school choirs perform folk melodies for elderly residents at the nursing home.",
         "Dàn đồng ca học sinh biểu diễn các làn điệu dân ca tặng các cụ già tại viện dưỡng lão.",
         ["live in a nursing home", "visit a nursing home"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("solidarity", "n", "tinh thần đoàn kết tương thân tương ái", "/ˌsɒlɪˈdærəti/",
         "Neighbors displayed remarkable solidarity when helping repair storm-damaged roofs.",
         "Bà con chòm xóm thể hiện tinh thần tương thân tương ái khi cùng nhau lợp lại mái nhà sau bão.",
         ["show solidarity with", "stand in solidarity"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("benevolence", "n", "lòng nhân từ hướng thiện", "/bəˈnevələns/",
         "Her lifelong benevolence brought hope to thousands of impoverished patients.",
         "Tấm lòng nhân từ suốt đời của bà đã thắp lên hy vọng cho hàng ngàn bệnh nhân nghèo khó.",
         ["act of benevolence", "spirit of benevolence"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("social inclusion", "n.phr", "sự hòa nhập xã hội bình đẳng", "/ˌsəʊʃl ɪnˈkluːʒn/",
         "Adaptive sports programs foster social inclusion for youth with physical disabilities.",
         "Thể thao thích ứng thúc đẩy sự hòa nhập xã hội cho thanh thiếu niên khuyết tật.",
         ["promote social inclusion", "barriers to social inclusion"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("community outreach", "n.phr", "hoạt động tiếp cận và giúp đỡ cộng đồng", "/kəˈmjuːnəti ˈaʊtriːtʃ/",
         "Doctors participate in weekend community outreach programs providing free checkups.",
         "Các bác sĩ tham gia hoạt động cộng đồng cuối tuần để khám sức khỏe miễn phí cho dân nghèo.",
         ["conduct community outreach", "outreach initiative"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("voluntary contribution", "n.phr", "khoản đóng góp tự nguyện vì cộng đồng", "/ˈvɒləntri ˌkɒntrɪˈbjuːʃn/",
         "The bridge was built entirely through voluntary contributions from villagers.",
         "Cây cầu được xây dựng hoàn toàn từ những đóng góp tự nguyện của bà con dân làng.",
         ["make a voluntary contribution", "rely on voluntary contributions"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("neighborhood cleanup", "n.phr", "buổi tổng vệ sinh ngõ phố xanh sạch đẹp", "/ˈneɪbəhʊd ˈkliːnʌp/",
         "Families gathered on Sunday morning for the monthly neighborhood cleanup.",
         "Các gia đình tập trung vào sáng Chủ nhật để tham gia buổi tổng vệ sinh ngõ phố định kỳ.",
         ["join a neighborhood cleanup", "organize a cleanup"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("free dental clinic", "n.phr", "phòng khám răng miễn phí cho người nghèo", "/friː ˈdentl ˈklɪnɪk/",
         "Dentistry students volunteer at the free dental clinic twice a month.",
         "Sinh viên khoa răng hàm mặt tình nguyện khám tại phòng nha miễn phí hai lần mỗi tháng.",
         ["run a free dental clinic", "attend a free clinic"],
         "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80"),
        ("empathy", "n", "sự thấu cảm và sẻ chia sâu sắc", "/ˈempəθi/",
         "True volunteering begins with heartfelt empathy for those enduring hardships.",
         "Hoạt động tình nguyện đích thực bắt đầu từ sự thấu cảm chân thành với những người hoạn nạn.",
         ["display deep empathy", "cultivate empathy"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("community welfare", "n.phr", "phúc lợi và đời sống an sinh của cộng đồng", "/kəˈmjuːnəti ˈwelfeə(r)/",
         "Public investments in clean water directly improve community welfare.",
         "Đầu tư công vào hệ thống nước sạch nâng cao trực tiếp phúc lợi đời sống của người dân.",
         ["enhance community welfare", "dedication to community welfare"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80")
    ]
}

def inject_to_file(filepath, unit_data_map):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    for unit_slug, items in unit_data_map.items():
        search_key = f'"{unit_slug}": ['
        idx = content.find(search_key)
        if idx != -1:
            close_idx = content.find('  ],', idx)
            if close_idx != -1:
                block_entries = []
                for item in items:
                    word, pos, vi, ipa, en_ex, vi_ex, colocs, img = item
                    cid = f"mega-{unit_slug[:6]}-{word.lower().replace(' ', '-').replace('/', '-')}"
                    audio = f"https://dict.youdao.com/dictvoice?audio={word.replace(' ', '+')}&type=2"
                    block_entries.append('    ,')
                    block_entries.append('    {')
                    block_entries.append(f'      id: {json.dumps(cid)},')
                    block_entries.append(f'      word: {json.dumps(word)},')
                    block_entries.append(f'      partOfSpeech: {json.dumps(pos)},')
                    block_entries.append(f'      meaningVi: {json.dumps(vi)},')
                    block_entries.append(f'      ipa: {json.dumps(ipa)},')
                    block_entries.append(f'      audioUrl: {json.dumps(audio)},')
                    block_entries.append(f'      imageUrl: {json.dumps(img)},')
                    block_entries.append(f'      exampleEn: {json.dumps(en_ex)},')
                    block_entries.append(f'      exampleVi: {json.dumps(vi_ex)},')
                    block_entries.append(f'      collocations: {json.dumps(colocs)}')
                    block_entries.append('    }')
                insert_str = "\n".join(block_entries) + "\n"
                content = content[:close_idx] + insert_str + content[close_idx:]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

g10_path = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "curriculum", "expanded-vocab-g10.ts")
inject_to_file(g10_path, G10_REMAINING)
print("Injected mega words into G10 units 3 and 4!")
