# -*- coding: utf-8 -*-
"""
Boost all units across Grade 10, 11, 12 so that EVERY single unit achieves 50 to 80 words!
Curated from textbook syllabus, VietJack, Loigiaihay, and Cambridge Dictionary.
"""
import json
import os

# Additional items to inject into Grade 10
G10_EXTRA = {
    "unit-1-family-life": [
        ("household finances", "n.phr", "tài chính gia đình", "/ˈhaʊshəʊld ˈfaɪnænsɪz/",
         "Couples should openly discuss household finances each month.",
         "Vợ chồng nên cởi mở thảo luận về tài chính gia đình mỗi tháng.",
         ["manage household finances", "track household finances"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("family tree", "n.phr", "gia phả, cây phả hệ dòng họ", "/ˈfæməli triː/",
         "The grandfather showed the children their ancient family tree.",
         "Ông nội chỉ cho các cháu xem cuốn gia phả cổ của dòng họ.",
         ["trace a family tree", "family tree chart"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("chores rotation", "n.phr", "sự luân phiên làm việc nhà", "/tʃɔːrz rəʊˈteɪʃn/",
         "Having a chores rotation schedule ensures everyone helps out fairly.",
         "Có lịch luân phiên làm việc nhà đảm bảo mọi người đều giúp đỡ công bằng.",
         ["weekly chores rotation", "follow chores rotation"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("parental blessing", "n.phr", "lời chúc phúc của cha mẹ", "/pəˈrentl ˈblesɪŋ/",
         "The bride and groom knelt to ask for parental blessing on their wedding day.",
         "Cô dâu và chú rể quỳ xin lời chúc phúc của cha mẹ trong ngày cưới.",
         ["receive parental blessing", "seek parental blessing"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("nurturing environment", "n.phr", "môi trường nuôi dưỡng yêu thương", "/ˈnɜːtʃərɪŋ ɪnˈvaɪrənmənt/",
         "Growing up in a nurturing environment helps children become confident adults.",
         "Lớn lên trong môi trường yêu thương giúp trẻ trở thành người lớn tự tin.",
         ["provide a nurturing environment", "create a nurturing environment"],
         "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-2-humans-and-the-environment": [
        ("reforestation", "n", "trồng lại rừng phủ xanh", "/ˌriːˌfɒrɪˈsteɪʃn/",
         "Reforestation projects help slow down catastrophic soil erosion.",
         "Các dự án trồng lại rừng giúp làm chậm quá trình xói mòn đất.",
         ["coastal reforestation", "mass reforestation"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("energy conservation", "n.phr", "việc tiết kiệm điện năng", "/ˈenədʒi ˌkɒnsəˈveɪʃn/",
         "Simple habits like turning off fans support national energy conservation.",
         "Thói quen tắt quạt khi ra khỏi phòng hỗ trợ tiết kiệm năng lượng quốc gia.",
         ["practice energy conservation", "energy conservation tips"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80"),
        ("biodiversity loss", "n.phr", "sự suy giảm đa dạng sinh học", "/ˌbaɪəʊdaɪˈvɜːsəti lɒs/",
         "Habitat destruction is the main driver of biodiversity loss globally.",
         "Phá hủy môi trường sống là nguyên nhân chính dẫn đến suy giảm đa dạng sinh học.",
         ["halt biodiversity loss", "threat of biodiversity loss"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("upcycling", "n", "tái chế sáng tạo thành đồ vật có ích", "/ˈʌpsaɪklɪŋ/",
         "Upcycling glass jars into flower pots is a creative weekend DIY project.",
         "Tái chế hũ thủy tinh thành chậu hoa là ý tưởng sáng tạo vào cuối tuần.",
         ["creative upcycling", "benefits of upcycling"],
         "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80"),
        ("green technology", "n.phr", "công nghệ xanh bảo vệ trái đất", "/ɡriːn tekˈnɒlədʒi/",
         "Investing in green technology reduces factory emissions significantly.",
         "Đầu tư vào công nghệ xanh giúp giảm đáng kể khí thải nhà máy.",
         ["develop green technology", "adopt green technology"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80"),
        ("ecocentrism", "n", "thuyết trung tâm sinh thái tôn trọng muôn loài", "/ˌiːkəʊˈsentrɪzəm/",
         "Ecocentrism emphasizes that all living organisms possess inherent value.",
         "Thuyết trung tâm sinh thái nhấn mạnh mọi sinh vật đều có giá trị tự thân.",
         ["embrace ecocentrism", "principles of ecocentrism"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-3-music": [
        ("soundtrack", "n", "nhạc nền phim ảnh", "/ˈsaʊndtræk/",
         "The movie soundtrack topped global streaming charts for three months.",
         "Nhạc phim đã đứng đầu các bảng xếp hạng trực tuyến suốt ba tháng.",
         ["original soundtrack", "listen to the soundtrack"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("acoustic guitar", "n.phr", "đàn ghi-ta mộc truyền thống", "/əˌkuːstɪk ɡɪˈtɑː(r)/",
         "He played a gentle folk song on his vintage acoustic guitar.",
         "Anh ấy đã gảy một bản dân ca êm dịu trên cây đàn ghi-ta mộc cổ điển.",
         ["strum an acoustic guitar", "acoustic guitar cords"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("vocal range", "n.phr", "quãng giọng hát của ca sĩ", "/ˈvəʊkl reɪndʒ/",
         "The soprano amazed the judges with her impressive four-octave vocal range.",
         "Nữ ca sĩ thính phòng làm ban giám khảo kinh ngạc với quãng giọng bốn quãng tám.",
         ["wide vocal range", "extend vocal range"],
         "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80"),
        ("sing-along", "n", "buổi hát hòa giọng cùng nhau", "/ˈsɪŋ əlɒŋ/",
         "The campfire ended with an energetic acoustic sing-along.",
         "Đêm lửa trại khép lại bằng một màn hòa giọng hát cùng nhau đầy hào hứng.",
         ["join a sing-along", "fun sing-along"],
         "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-4-for-a-better-community": [
        ("charity drive", "n.phr", "đợt quyên góp cứu trợ từ thiện", "/ˈtʃærəti draɪv/",
         "The neighborhood organized a warm clothing charity drive for winter.",
         "Khu dân cư đã phát động đợt quyên góp áo ấm từ thiện cho mùa đông.",
         ["launch a charity drive", "participate in a charity drive"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("benevolence", "n", "lòng nhân từ, bác ái", "/bəˈnevələns/",
         "Her heartfelt benevolence brought food and shelter to flood victims.",
         "Tấm lòng nhân từ của cô đã mang lại cơm ăn và chỗ ở cho đồng bào vùng lũ.",
         ["act of benevolence", "pure benevolence"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80"),
        ("soup kitchen", "n.phr", "bếp ăn từ thiện phát cơm miễn phí", "/ˈsuːp ˈkɪtʃɪn/",
         "Volunteers prepare hundreds of hot meals daily at the charity soup kitchen.",
         "Tình nguyện viên nấu hàng trăm suất cơm nóng mỗi ngày tại bếp ăn từ thiện.",
         ["volunteer at a soup kitchen", "community soup kitchen"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("social safety net", "n.phr", "mạng lưới an sinh xã hội", "/ˈsəʊʃl ˈseɪfti net/",
         "Pensions and disability grants form a vital social safety net for citizens.",
         "Lương hưu và trợ cấp khuyết tật tạo nên mạng lưới an sinh xã hội thiết yếu.",
         ["strengthen the social safety net", "broad social safety net"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("disaster relief", "n.phr", "công tác cứu trợ thiên tai bão lũ", "/dɪˈzɑːstə rɪˌliːf/",
         "Trucks loaded with clean drinking water rushed to join disaster relief efforts.",
         "Những xe tải chở nước sạch nhanh chóng lên đường cứu trợ vùng bão lũ.",
         ["coordinate disaster relief", "disaster relief team"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("public-spirited", "adj", "có tinh thần vì cộng đồng", "/ˌpʌblɪk ˈspɪrɪtɪd/",
         "Public-spirited youths repainted the rusty community playground equipment.",
         "Những thanh niên có tinh thần cộng đồng đã sơn sửa lại thiết bị sân chơi cũ.",
         ["public-spirited citizen", "public-spirited action"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("shelter", "n / v", "nơi che chở, mái ấm cho người neo đơn", "/ˈʃeltə(r)/",
         "The community shelter opens its warm doors during freezing winter nights.",
         "Mái ấm cộng đồng mở rộng cửa đón người cơ nhỡ vào những đêm đông buốt giá.",
         ["provide shelter", "seek shelter"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("aid convoy", "n.phr", "đoàn xe viện trợ cứu trợ khẩn cấp", "/eɪd ˈkɒnvɔɪ/",
         "An international aid convoy delivered medical supplies to disaster zones.",
         "Đoàn xe viện trợ quốc tế đã kịp thời chuyển thuốc men tới vùng thảm họa.",
         ["dispatch an aid convoy", "relief aid convoy"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("outreach program", "n.phr", "chương trình tiếp cận giúp đỡ cộng đồng", "/ˈaʊtriːtʃ ˌprəʊɡræm/",
         "The university hospital runs an outreach program checking eyes for rural kids.",
         "Bệnh viện đại học thực hiện chương trình khám mắt miễn phí cho trẻ em vùng sâu.",
         ["community outreach program", "conduct an outreach program"],
         "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80"),
        ("empathetic", "adj", "đồng cảm, giàu tình trắc ẩn", "/ˌempəˈθetɪk/",
         "An empathetic listener can bring great comfort to someone in distress.",
         "Một người biết đồng cảm lắng nghe có thể đem lại sự an ủi to lớn cho người đau khổ.",
         ["empathetic response", "empathetic understanding"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("good deed", "n.phr", "việc làm tốt, nghĩa cử cao đẹp", "/ɡʊd diːd/",
         "She makes a habit of doing one good deed anonymously every day.",
         "Cô ấy tạo thói quen làm một việc tốt thầm lặng mỗi ngày.",
         ["do a good deed", "reward a good deed"],
         "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-5-inventions": [
        ("touchscreen", "n", "màn hình cảm ứng đa điểm", "/ˈtʌtʃskriːn/",
         "Touchscreen interfaces replaced physical phone keypads completely.",
         "Màn hình cảm ứng đã thay thế hoàn toàn bàn phím số vật lý trên điện thoại.",
         ["touchscreen display", "responsive touchscreen"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("microchip", "n", "vi mạch bán dẫn điện tử", "/ˈmaɪkrəʊtʃɪp/",
         "Modern microchips pack billions of transistors onto a fingernail-sized silicon die.",
         "Vi mạch bán dẫn hiện đại chứa hàng tỷ bóng bán dẫn trên một miếng silicon nhỏ bằng móng tay.",
         ["silicon microchip", "microchip manufacturing"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("smartwatch", "n", "đồng hồ thông minh theo dõi sức khỏe", "/ˈsmɑːtwɒtʃ/",
         "Her smartwatch alerts her whenever her resting heart rate spikes unusually.",
         "Đồng hồ thông minh cảnh báo mỗi khi nhịp tim lúc nghỉ của cô tăng cao bất thường.",
         ["wear a smartwatch", "smartwatch features"],
         "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"),
        ("fiber optics", "n.phr", "công nghệ cáp quang tốc độ cao", "/ˌfaɪbər ˈɒptɪks/",
         "High-speed fiber optics allow seamless 4K video streaming without buffering.",
         "Cáp quang tốc độ cao cho phép xem phim 4K mượt mà không bị giật lag.",
         ["fiber optics cable", "fiber optics network"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("drone", "n", "thiết bị bay không người lái điều khiển từ xa", "/drəʊn/",
         "Farmers use agricultural drones to spray organic bio-fertilizer over rice fields.",
         "Nông dân dùng drone nông nghiệp để phun phân bón hữu cơ trên đồng lúa.",
         ["commercial drone", "fly a drone"],
         "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80"),
        ("lithium-ion battery", "n.phr", "pin sạc lithium-ion", "/ˌlɪθiəm ˈaɪən ˈbætəri/",
         "Electric motorcycles rely on rechargeable lithium-ion battery packs.",
         "Xe máy điện chạy bằng các khối pin sạc lithium-ion hiện đại.",
         ["lithium-ion battery pack", "charge a lithium-ion battery"],
         "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80"),
        ("Bluetooth", "n.pr", "công nghệ kết nối không dây tầm gần", "/ˈbluːtuːθ/",
         "Connect your wireless earbuds to your laptop using Bluetooth in one tap.",
         "Kết nối tai nghe không dây với máy tính xách tay qua Bluetooth chỉ bằng một chạm.",
         ["Bluetooth connection", "pair via Bluetooth"],
         "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"),
        ("smart home", "n.phr", "ngôi nhà thông minh điều khiển tự động", "/smɑːt həʊm/",
         "A smart home allows you to adjust air conditioning and lock doors remotely.",
         "Nhà thông minh cho phép bạn chỉnh điều hòa và khóa cửa từ xa qua điện thoại.",
         ["smart home devices", "install smart home systems"],
         "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=80"),
        ("voice recognition", "n.phr", "công nghệ nhận diện khẩu lệnh giọng nói", "/vɔɪs ˌrekəɡˈnɪʃn/",
         "Voice recognition software allows hands-free texting while commuting.",
         "Phần mềm nhận diện giọng nói cho phép nhắn tin rảnh tay khi đang đi lại.",
         ["accurate voice recognition", "voice recognition technology"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("wireless charging", "n.phr", "công nghệ sạc không dây", "/ˈwaɪələs ˈtʃɑːdʒɪŋ/",
         "Simply placing your phone on the pad initiates fast wireless charging.",
         "Chỉ cần đặt điện thoại lên đế là quá trình sạc nhanh không dây tự động kích hoạt.",
         ["wireless charging pad", "support wireless charging"],
         "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"),
        ("interactive display", "n.phr", "màn hình hiển thị tương tác", "/ˌɪntərˈæktɪv dɪˈspleɪ/",
         "Museums install interactive displays to make historical exhibits fascinating.",
         "Các bảo tàng lắp màn hình tương tác để hiện vật lịch sử trở nên lôi cuốn.",
         ["touch interactive display", "interactive display screen"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("high-definition", "adj", "độ nét cao, hình ảnh sắc nét", "/ˌhaɪ defɪˈnɪʃn/",
         "The new television reproduces sports matches in crystal-clear high-definition.",
         "Chiếc tivi mới hiển thị các trận bóng đá với độ nét cao sắc nét như thật.",
         ["high-definition video", "high-definition camera"],
         "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"),
        ("compact design", "n.phr", "thiết kế nhỏ gọn, tinh tế", "/ˈkɒmpækt dɪˈzaɪn/",
         "Travellers love this portable power bank because of its ultra-slim compact design.",
         "Dân du lịch thích cục sạc này vì thiết kế siêu mỏng nhỏ gọn dễ bỏ túi.",
         ["sleek compact design", "benefit of compact design"],
         "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80"),
        ("technological leap", "n.phr", "bước nhảy vọt công nghệ thần kỳ", "/ˌteknəˈlɒdʒɪkl liːp/",
         "The discovery of the transistor was a monumental technological leap forward.",
         "Phát minh ra bóng bán dẫn là bước nhảy vọt công nghệ mang tính thời đại.",
         ["giant technological leap", "witness a technological leap"],
         "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-6-gender-equality": [
        ("equal standing", "n.phr", "vị thế bình đẳng ngang hàng", "/ˈiːkwəl ˈstændɪŋ/",
         "Men and women should stand on equal standing in both family and career.",
         "Nam và nữ cần có vị thế ngang hàng bình đẳng trong cả gia đình lẫn sự nghiệp.",
         ["on equal standing", "achieve equal standing"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("equal status", "n.phr", "địa vị xã hội bình đẳng", "/ˈiːkwəl ˈsteɪtəs/",
         "The law ensures equal status for both spouses in marriage and property rights.",
         "Pháp luật đảm bảo địa vị bình đẳng cho vợ và chồng trong hôn nhân và quyền tài sản.",
         ["grant equal status", "equal legal status"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("shared responsibility", "n.phr", "trách nhiệm cùng gánh vác", "/ʃeəd rɪˌspɒnsəˈbɪləti/",
         "Child upbringing is a shared responsibility between both father and mother.",
         "Nuôi dạy con cái là trách nhiệm chung cần gánh vác của cả bố và mẹ.",
         ["shared responsibility for", "spirit of shared responsibility"],
         "https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?auto=format&fit=crop&w=800&q=80"),
        ("fair treatment", "n.phr", "sự đối xử công bằng, vô tư", "/feə ˈtriːtmənt/",
         "Every employee deserves fair treatment regardless of their gender or background.",
         "Mọi người lao động đều xứng đáng được đối xử công bằng không phân biệt giới tính.",
         ["ensure fair treatment", "demand fair treatment"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("equal rights", "n.phr", "quyền bình đẳng của công dân", "/ˈiːkwəl raɪts/",
         "Generations of suffragettes fought courageously for women's equal rights.",
         "Nhiều thế hệ phụ nữ đã đấu tranh quả cảm để giành quyền bình đẳng cho phái nữ.",
         ["fight for equal rights", "guarantee equal rights"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("empowered", "adj", "được trao quyền tự chủ mạnh mẽ", "/ɪmˈpaʊəd/",
         "Educated women feel empowered to make independent career choices.",
         "Phụ nữ có học thức cảm thấy được trao quyền để tự quyết định sự nghiệp của mình.",
         ["feel empowered", "empowered women"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("mutual support", "n.phr", "sự hỗ trợ nâng đỡ lẫn nhau", "/ˈmjuːtʃuəl səˈpɔːt/",
         "Mutual support between spouses is the key to thriving in modern society.",
         "Sự nâng đỡ lẫn nhau giữa vợ chồng là chìa khóa để phát triển trong xã hội hiện đại.",
         ["provide mutual support", "spirit of mutual support"],
         "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=800&q=80"),
        ("fair play", "n.phr", "tinh thần công bằng chính trực", "/ˌfeə ˈpleɪ/",
         "Promoting fair play in hiring practices eliminates unconscious biases.",
         "Thúc đẩy sự công bằng trong tuyển dụng giúp loại bỏ các thiên kiến ngầm.",
         ["sense of fair play", "principle of fair play"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("equality of opportunity", "n.phr", "sự bình đẳng về cơ hội phát triển", "/iˈkwɒləti əv ˌɒpəˈtjuːnəti/",
         "True social justice begins with guaranteeing equality of opportunity in schools.",
         "Công bằng xã hội thực chất bắt đầu từ việc đảm bảo cơ hội bình đẳng trong trường học.",
         ["guarantee equality of opportunity", "strive for equality of opportunity"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("nondiscrimination", "n", "nguyên tắc không phân biệt đối xử", "/ˌnɒndɪˌskrɪmɪˈneɪʃn/",
         "The labor code enforces strict nondiscrimination against female workers.",
         "Bộ luật lao động thực thi nguyên tắc không phân biệt đối xử với lao động nữ.",
         ["policy of nondiscrimination", "ensure nondiscrimination"],
         "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80"),
        ("co-breadwinner", "n", "người cùng làm trụ cột kinh tế gia đình", "/ˌkəʊ ˈbredwɪnə(r)/",
         "Both husband and wife act as co-breadwinners in many modern households.",
         "Cả vợ và chồng cùng làm trụ cột kinh tế trong nhiều gia đình thời nay.",
         ["serve as co-breadwinners", "role of co-breadwinner"],
         "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80"),
        ("egalitarian", "adj", "bình đẳng, hướng tới bình quyền", "/ɪˌɡælɪˈteəriən/",
         "An egalitarian marriage shares both earning and household responsibilities evenly.",
         "Một cuộc hôn nhân bình đẳng chia đều cả việc kiếm tiền lẫn việc gia đình.",
         ["egalitarian society", "egalitarian family"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-7-viet-nam-and-international-organisations": [
        ("peacekeeping mission", "n.phr", "sứ mệnh gìn giữ hòa bình Liên Hợp Quốc", "/ˈpiːskiːpɪŋ ˈmɪʃn/",
         "Vietnam deploys level-two field hospitals to UN peacekeeping missions in South Sudan.",
         "Việt Nam cử bệnh viện dã chiến cấp hai tới các phái bộ gìn giữ hòa bình LHQ tại Nam Sudan.",
         ["join a peacekeeping mission", "peacekeeping mission personnel"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("bilateral cooperation", "n.phr", "sự hợp tác song phương giữa hai nước", "/ˌbaɪˈlætərəl kəʊˌɒpəˈreɪʃn/",
         "Bilateral cooperation in agricultural exports has grown substantially.",
         "Hợp tác song phương trong xuất khẩu nông sản đã tăng trưởng vượt bậc.",
         ["deepen bilateral cooperation", "framework for bilateral cooperation"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("member nation", "n.phr", "quốc gia thành viên trong tổ chức", "/ˈmembə ˈneɪʃn/",
         "Each member nation has an equal vote at the United Nations General Assembly.",
         "Mỗi quốc gia thành viên đều có một lá phiếu bình đẳng tại Đại hội đồng Liên Hợp Quốc.",
         ["active member nation", "contributions of member nations"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("multilateral forum", "n.phr", "diễn đàn hợp tác đa phương", "/ˌmʌltiˈlætərəl ˈfɔːrəm/",
         "Vietnam actively raises its voice at prominent multilateral forums like APEC and ASEAN.",
         "Việt Nam tích cực cất cao tiếng nói tại các diễn đàn đa phương lớn như APEC và ASEAN.",
         ["participate in multilateral forums", "host a multilateral forum"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("strategic partner", "n.phr", "đối tác chiến lược tin cậy", "/strəˈtiːdʒɪk ˈpɑːtnə(r)/",
         "Vietnam has established strategic partner relations with leading economic powers.",
         "Việt Nam đã thiết lập quan hệ đối tác chiến lược với các cường quốc kinh tế hàng đầu.",
         ["reliable strategic partner", "become a strategic partner"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("free trade", "n.phr", "thương mại tự do không rào cản", "/ˌfriː ˈtreɪd/",
         "Free trade agreements allow Vietnamese textiles to enter European markets with zero tariffs.",
         "Các hiệp định thương mại tự do giúp dệt may Việt Nam vào thị trường châu Âu với thuế suất 0%.",
         ["advocate free trade", "benefits of free trade"],
         "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&q=80"),
        ("diplomat", "n", "nhà ngoại giao đại diện cho đất nước", "/ˈdɪpləmæt/",
         "Vietnamese diplomats work untiringly to protect citizens residing overseas.",
         "Các nhà ngoại giao Việt Nam làm việc không mệt mỏi để bảo hộ công dân ở nước ngoài.",
         ["career diplomat", "skilled diplomat"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("humanitarian assistance", "n.phr", "hỗ trợ cứu trợ nhân đạo", "/hjuːˌmænɪˈteəriən əˈsɪstəns/",
         "Vietnam provided emergency humanitarian assistance to countries hit by earthquakes.",
         "Việt Nam đã gửi hàng cứu trợ nhân đạo khẩn cấp tới các quốc gia bị động đất.",
         ["provide humanitarian assistance", "emergency humanitarian assistance"],
         "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80"),
        ("economic integration", "n.phr", "hội nhập kinh tế khu vực và thế giới", "/ˌiːkəˈnɒmɪk ˌɪntɪˈɡreɪʃn/",
         "Economic integration opened access to international supply chains for local firms.",
         "Hội nhập kinh tế mở ra cơ hội tham gia chuỗi cung ứng quốc tế cho doanh nghiệp trong nước.",
         ["accelerate economic integration", "deep economic integration"],
         "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&q=80"),
        ("sovereign state", "n.phr", "quốc gia có chủ quyền độc lập", "/ˈsɒvrɪn steɪt/",
         "Vietnam interacts with all sovereign states on the basis of mutual respect.",
         "Việt Nam giao lưu với mọi quốc gia có chủ quyền trên cơ sở tôn trọng lẫn nhau.",
         ["independent sovereign state", "rights of a sovereign state"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("peaceful settlement", "n.phr", "giải quyết hòa bình các tranh chấp", "/ˈpiːsfl ˈsetlmənt/",
         "Vietnam advocates the peaceful settlement of all international disputes via dialogue.",
         "Việt Nam ủng hộ việc giải quyết hòa bình mọi tranh chấp quốc tế thông qua đối thoại.",
         ["peaceful settlement of disputes", "seek a peaceful settlement"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("solidarity", "n", "tinh thần tương thân đoàn kết", "/ˌsɒlɪˈdærəti/",
         "ASEAN solidarity ensures a coordinated approach towards common regional goals.",
         "Tình đoàn kết ASEAN đảm bảo sự phối hợp nhịp nhàng hướng tới các mục tiêu chung.",
         ["express solidarity", "strengthen regional solidarity"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80"),
        ("foreign relations", "n.phr", "quan hệ đối ngoại của nhà nước", "/ˈfɒrən rɪˈleɪʃnz/",
         "Expanding friendly foreign relations has significantly boosted foreign direct investment.",
         "Mở rộng quan hệ đối ngoại hữu nghị đã thúc đẩy mạnh mẽ nguồn vốn đầu tư trực tiếp nước ngoài.",
         ["conduct foreign relations", "friendly foreign relations"],
         "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-8-new-ways-to-learn": [
        ("online tutorial", "n.phr", "video hướng dẫn học trực tuyến", "/ˈɒnlaɪn tjuːˈtɔːriəl/",
         "Students watch online tutorials to master tricky geometry theorems at home.",
         "Học sinh xem các video hướng dẫn trực tuyến để ôn lại các định lý hình học khó ở nhà.",
         ["watch an online tutorial", "helpful online tutorial"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("screen recorder", "n.phr", "phần mềm quay màn hình bài giảng", "/skriːn rɪˈkɔːdə(r)/",
         "The teacher uses a screen recorder to save computer science code demonstrations.",
         "Thầy giáo dùng phần mềm quay màn hình để lưu lại các đoạn mẫu viết mã tin học.",
         ["use a screen recorder", "screen recorder app"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("digital quiz", "n.phr", "bài trắc nghiệm kiểm tra số", "/ˈdɪdʒɪtl kwɪz/",
         "Playing a digital quiz at the end of class reinforces key grammar lessons funly.",
         "Chơi trò đố vui trắc nghiệm trực tuyến cuối giờ giúp củng cố ngữ pháp rất vui vẻ.",
         ["take a digital quiz", "create a digital quiz"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("microlearning", "n", "học theo từng mẩu kiến thức ngắn (5 phút)", "/ˈmaɪkrəʊˌlɜːnɪŋ/",
         "Microlearning modules allow busy pupils to study English in short five-minute breaks.",
         "Học vi mô cho phép học sinh tranh thủ học tiếng Anh trong những giờ giải lao 5 phút.",
         ["benefits of microlearning", "microlearning technique"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("flashcard", "n", "thẻ học từ vựng hai mặt thông minh", "/ˈflæʃkɑːd/",
         "Digital flashcards prompt your memory with images, pronunciation, and examples.",
         "Thẻ từ vựng số gợi nhớ cho bạn với hình ảnh, phát âm và câu ví dụ.",
         ["study with flashcards", "vocabulary flashcard"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("remote study", "n.phr", "học tập từ xa qua máy tính", "/rɪˈməʊt ˈstʌdi/",
         "Remote study demands high self-motivation and quiet study corners at home.",
         "Học từ xa đòi hỏi tinh thần tự giác cao và một góc học tập yên tĩnh ở nhà.",
         ["manage remote study", "effective remote study"],
         "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80"),
        ("digital note-taking", "n.phr", "ghi chép bài giảng trên thiết bị số", "/ˈdɪdʒɪtl ˈnəʊt teɪkɪŋ/",
         "Stylus pens on tablets make digital note-taking neat, colorful, and searchable.",
         "Bút cảm ứng trên máy tính bảng giúp việc ghi chép số gọn gàng, đẹp mắt và dễ tìm kiếm.",
         ["practice digital note-taking", "apps for digital note-taking"],
         "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80"),
        ("peer review", "n.phr", "chấm chéo và góp ý bài làm cho bạn", "/ˈpɪə rɪˌvjuː/",
         "Peer review helps classmates learn from each other's writing techniques.",
         "Chấm chéo giúp các bạn cùng lớp học hỏi lẫn nhau về kỹ năng hành văn.",
         ["conduct peer review", "valuable peer review"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("audiobook", "n", "sách nói nghe trên điện thoại", "/ˈɔːdiəʊbʊk/",
         "Listening to literature audiobooks while walking improves literary comprehension.",
         "Nghe sách nói tác phẩm văn học trong lúc đi dạo giúp thẩm thấu bài văn hay hơn.",
         ["listen to an audiobook", "narrate an audiobook"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("virtual whiteboarding", "n.phr", "vẽ bảng trắng tương tác nhóm trên mạng", "/ˈvɜːtʃuəl ˈwaɪtbɔːdɪŋ/",
         "Team members brainstorm physics project diagrams using virtual whiteboarding.",
         "Cả nhóm cùng lên ý tưởng sơ đồ dự án Vật lý bằng bảng trắng ảo trên mạng.",
         ["use virtual whiteboarding", "collaborative whiteboarding"],
         "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80"),
        ("study group", "n.phr", "nhóm học tập cùng tiến", "/ˈstʌdi ɡruːp/",
         "Joining an online study group keeps classmates accountable for math problem sets.",
         "Tham gia nhóm học tập trực tuyến giúp các bạn nhắc nhở nhau làm bài tập toán đầy đủ.",
         ["form a study group", "weekly study group"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("interactive simulation", "n.phr", "mô phỏng tương tác thí nghiệm", "/ˌɪntərˈæktɪv ˌsɪmjuˈleɪʃn/",
         "Chemistry interactive simulations allow safe visualization of molecular bonding.",
         "Mô phỏng tương tác môn Hóa giúp quan sát trực quan liên kết phân tử một cách an toàn.",
         ["run an interactive simulation", "science interactive simulations"],
         "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-9-protecting-the-environment": [
        ("nature conservation", "n.phr", "công tác bảo tồn thiên nhiên", "/ˈneɪtʃə ˌkɒnsəˈveɪʃn/",
         "Nature conservation preserves pristine mountain forests for future generations.",
         "Bảo tồn thiên nhiên giữ gìn những cánh rừng nguyên sinh cho các thế hệ tương lai.",
         ["support nature conservation", "field of nature conservation"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("ecological reserve", "n.phr", "khu bảo tồn sinh thái", "/ˌiːkəˈlɒdʒɪkl rɪˈzɜːv/",
         "Strict regulations in the ecological reserve prohibit campfires and littering.",
         "Quy định nghiêm ngặt tại khu bảo tồn sinh thái cấm đốt lửa trại và xả rác.",
         ["protect the ecological reserve", "wild ecological reserve"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("tree-planting", "n", "hoạt động trồng cây xanh gây rừng", "/ˈtriː ˌplɑːntɪŋ/",
         "Our school organized a tree-planting festival to celebrate the new spring.",
         "Trường tôi đã tổ chức tết trồng cây để chào đón mùa xuân mới.",
         ["tree-planting campaign", "join tree-planting"],
         "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=800&q=80"),
        ("wildlife protection", "n.phr", "bảo vệ động vật hoang dã", "/ˈwaɪldlaɪf prəˈtekʃn/",
         "Stricter penal codes were introduced for wildlife protection in national parks.",
         "Các điều luật hình sự nghiêm khắc hơn đã được áp dụng để bảo vệ động vật hoang dã.",
         ["advocate wildlife protection", "law on wildlife protection"],
         "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80"),
        ("clean environment", "n.phr", "môi trường sống xanh sạch", "/kliːn ɪnˈvaɪrənmənt/",
         "Every citizen has the basic right to live in a clean and healthy environment.",
         "Mọi công dân đều có quyền cơ bản được sống trong một môi trường trong lành sạch đẹp.",
         ["maintain a clean environment", "strive for a clean environment"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("green planet", "n.phr", "hành tinh xanh của chúng ta", "/ɡriːn ˈplænɪt/",
         "Planting more trees is our shared responsibility to preserve a green planet.",
         "Trồng thêm cây xanh là trách nhiệm chung của chúng ta để gìn giữ hành tinh xanh.",
         ["cherish our green planet", "protect our green planet"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80"),
        ("marine ecosystem", "n.phr", "hệ sinh thái biển và hải đảo", "/məˈriːn ˈiːkəʊsɪstəm/",
         "Coral reefs and seagrass beds are vital components of the marine ecosystem.",
         "Rạn san hô và thảm cỏ biển là những thành tố sống còn của hệ sinh thái đại dương.",
         ["conserve the marine ecosystem", "fragile marine ecosystem"],
         "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80"),
        ("environmental education", "n.phr", "giáo dục bảo vệ môi trường học đường", "/ɪnˌvaɪrənˈmentl ˌedʒuˈkeɪʃn/",
         "Early environmental education instills green habits in kindergarten students.",
         "Giáo dục môi trường từ nhỏ hình thành thói quen xanh cho các em học sinh mẫu giáo.",
         ["promote environmental education", "role of environmental education"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80"),
        ("green campaign", "n.phr", "chiến dịch xanh vì môi trường", "/ɡriːn kæmˈpeɪn/",
         "Youth unions launched a green campaign to collect used plastic bottles for recycling.",
         "Đoàn thanh niên phát động chiến dịch xanh thu gom chai nhựa cũ để tái chế.",
         ["join a green campaign", "school green campaign"],
         "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80"),
        ("sustainable future", "n.phr", "tương lai phát triển bền vững", "/səˈsteɪnəbl ˈfjuːtʃə(r)/",
         "Saving power and planting trees ensures a sustainable future for our children.",
         "Tiết kiệm điện và trồng cây xanh đảm bảo một tương lai bền vững cho con em chúng ta.",
         ["build a sustainable future", "work towards a sustainable future"],
         "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80"),
        ("anti-littering", "adj", "chống xả rác bừa bãi", "/ˌænti ˈlɪtərɪŋ/",
         "Clear anti-littering signs along the hiking trail remind visitors to pack out their trash.",
         "Biển báo chống xả rác dọc đường mòn nhắc nhở du khách tự thu dọn rác mang về.",
         ["anti-littering law", "anti-littering signage"],
         "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80"),
        ("eco-friendly habit", "n.phr", "thói quen thân thiện với môi trường", "/ˌiːkəʊ ˈfrendli ˈhæbɪt/",
         "Using a reusable fabric bag when shopping is an easy eco-friendly habit.",
         "Mang theo túi vải khi đi chợ là một thói quen thân thiện môi trường rất dễ thực hiện.",
         ["develop eco-friendly habits", "daily eco-friendly habit"],
         "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80")
    ],
    "unit-10-ecotourism": [
        ("guided tour", "n.phr", "chuyến tham quan có hướng dẫn viên", "/ˌɡaɪdɪd ˈtʊə(r)/",
         "A knowledgeable ranger led our guided tour through the bat cave safely.",
         "Người kiểm lâm am hiểu đã dẫn dắt chuyến tham quan qua hang dơi một cách an toàn.",
         ["book a guided tour", "informative guided tour"],
         "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"),
        ("nature trail", "n.phr", "đường mòn khám phá thiên nhiên", "/ˈneɪtʃə treɪl/",
         "We followed a marked nature trail through ancient limestone karst valleys.",
         "Chúng tôi men theo đường mòn thiên nhiên qua các thung lũng đá vôi cổ kính.",
         ["hike a nature trail", "scenic nature trail"],
         "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"),
        ("responsible tourism", "n.phr", "du lịch có trách nhiệm với điểm đến", "/rɪˈspɒnsəbl ˈtʊərɪzəm/",
         "Responsible tourism respects local ethnic customs and supports homegrown craft markets.",
         "Du lịch có trách nhiệm tôn trọng phong tục địa phương và mua sắm tại chợ thủ công bản địa.",
         ["principles of responsible tourism", "promote responsible tourism"],
         "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"),
        ("eco-lodge", "n.phr", "nhà nghỉ sinh thái bằng tre nứa tự nhiên", "/ˈiːkəʊ lɒdʒ/",
         "We stayed at a riverside eco-lodge built entirely of bamboo and thatch.",
         "Chúng tôi nghỉ tại khu nhà nghỉ sinh thái ven sông làm hoàn toàn bằng tre và mái lá.",
         ["stay at an eco-lodge", "rustic eco-lodge"],
         "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80"),
        ("cultural sensitivity", "n.phr", "sự nhạy bén và tôn trọng văn hóa bản địa", "/ˈkʌltʃərəl ˌsensəˈtɪvəti/",
         "Tourists should dress modestly in sacred pagodas to demonstrate cultural sensitivity.",
         "Du khách nên ăn mặc lịch sự khi vào chùa chiền để thể hiện sự tôn trọng văn hóa.",
         ["show cultural sensitivity", "exercise cultural sensitivity"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("sustainable travel", "n.phr", "du lịch bền vững bảo vệ tương lai", "/səˈsteɪnəbl ˈtrævl/",
         "Sustainable travel minimizes carbon emissions by prioritizing train transit over flights.",
         "Du lịch bền vững giảm thiểu khí thải bằng cách ưu tiên đi tàu hỏa thay cho máy bay.",
         ["advocate sustainable travel", "sustainable travel guide"],
         "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"),
        ("green traveler", "n.phr", "du khách xanh có ý thức bảo vệ môi trường", "/ɡriːn ˈtrævələ(r)/",
         "A green traveler carries a refillable steel flask and avoids single-use plastic.",
         "Một du khách xanh luôn mang bình nước inox tái sử dụng và tránh dùng đồ nhựa một lần.",
         ["habits of a green traveler", "become a green traveler"],
         "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"),
        ("nature exploration", "n.phr", "thám hiểm và khám phá vẻ đẹp tự nhiên", "/ˈneɪtʃə ˌekspləˈreɪʃn/",
         "Caving expeditions in Phong Nha offer unmatched thrills of nature exploration.",
         "Thám hiểm hang động ở Phong Nha đem lại cảm giác khám phá tự nhiên kỳ thú có một không hai.",
         ["thrill of nature exploration", "join nature exploration"],
         "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"),
        ("wilderness", "n", "vùng hoang dã thiên nhiên nguyên sơ", "/ˈwɪldənəs/",
         "Hikers must carry compasses and emergency radios when venturing into the deep wilderness.",
         "Người leo núi phải mang theo la bàn và bộ đàm khẩn cấp khi bước vào vùng rừng hoang dã.",
         ["untouched wilderness", "survive in the wilderness"],
         "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"),
        ("eco-adventure", "n.phr", "chuyến phiêu lưu dã ngoại sinh thái", "/ˈiːkəʊ ədˈventʃə(r)/",
         "Whitewater rafting on jungle rivers is an exhilarating eco-adventure for youths.",
         "Chèo xuồng vượt thác trên sông giữa rừng là chuyến phiêu lưu sinh thái đầy kích thích cho giới trẻ.",
         ["embark on an eco-adventure", "memorable eco-adventure"],
         "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"),
        ("conservation travel", "n.phr", "du lịch kết hợp tham gia bảo tồn thiên nhiên", "/ˌkɒnsəˈveɪʃn ˈtrævl/",
         "Volunteering to protect turtle nests on Con Dao island is meaningful conservation travel.",
         "Tình nguyện bảo vệ bãi rùa đẻ trứng tại Côn Đảo là chuyến đi bảo tồn đầy ý nghĩa.",
         ["participate in conservation travel", "conservation travel programs"],
         "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80")
    ]
}

# Update expanded-vocab-g10.ts with G10_EXTRA
g10_file = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "curriculum", "expanded-vocab-g10.ts")
with open(g10_file, "r", encoding="utf-8") as f:
    g10_text = f.read()

for unit_slug, extra_items in G10_EXTRA.items():
    search_str = f'"{unit_slug}": ['
    idx = g10_text.find(search_str)
    if idx != -1:
        # Find closing bracket of this unit
        close_idx = g10_text.find('  ],', idx)
        if close_idx != -1:
            # Build extra lines
            new_lines = []
            for item in extra_items:
                word, pos, vi, ipa, en_ex, vi_ex, colocs, img = item
                clean_id = f"v10-extra-{word.lower().replace(' ', '-').replace('/', '-')}"
                audio = f"https://dict.youdao.com/dictvoice?audio={word.replace(' ', '+')}&type=2"
                new_lines.append('    ,')
                new_lines.append('    {')
                new_lines.append(f'      id: {json.dumps(clean_id)},')
                new_lines.append(f'      word: {json.dumps(word)},')
                new_lines.append(f'      partOfSpeech: {json.dumps(pos)},')
                new_lines.append(f'      meaningVi: {json.dumps(vi)},')
                new_lines.append(f'      ipa: {json.dumps(ipa)},')
                new_lines.append(f'      audioUrl: {json.dumps(audio)},')
                new_lines.append(f'      imageUrl: {json.dumps(img)},')
                new_lines.append(f'      exampleEn: {json.dumps(en_ex)},')
                new_lines.append(f'      exampleVi: {json.dumps(vi_ex)},')
                new_lines.append(f'      collocations: {json.dumps(colocs)}')
                new_lines.append('    }')
            insert_content = "\n".join(new_lines)
            g10_text = g10_text[:close_idx] + insert_content + "\n" + g10_text[close_idx:]

with open(g10_file, "w", encoding="utf-8") as f:
    f.write(g10_text)

print("Successfully injected booster words into Grade 10!")
