# -*- coding: utf-8 -*-
"""
Mega booster for Grade 10: Boosts all 10 units from ~50 words to 75-80 words each!
Curated from Cambridge Dictionary, Oxford Learner's Dictionaries, Global Success, VietJack, Loigiaihay.
"""
import json
import os

G10_MEGA = {
    "unit-1-family-life": [
        ("household finances", "n.phr", "tài chính và chi tiêu trong gia đình", "/ˈhaʊshəʊld ˈfaɪnænsɪz/",
         "Couples should openly discuss household finances to avoid misunderstandings.",
         "Các cặp vợ chồng nên thảo luận cởi mở về tài chính gia đình để tránh hiểu lầm.",
         ["manage household finances", "budget for household finances"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("family reunion", "n.phr", "buổi sum họp gia đình ấm cúng", "/ˈfæməli ˌriːˈjuːniən/",
         "Tet holiday is the most cherished occasion for family reunions across Vietnam.",
         "Dịp Tết là cơ hội quý giá nhất cho những buổi đoàn viên gia đình trên khắp Việt Nam.",
         ["annual family reunion", "host a family reunion"],
         "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80"),
        ("mutual respect", "n.phr", "sự tôn trọng lẫn nhau giữa các thành viên", "/ˈmjuːtʃuəl rɪˈspekt/",
         "A peaceful household relies on mutual respect between parents and teenagers.",
         "Một mái ấm hòa thuận dựa trên sự tôn trọng lẫn nhau giữa cha mẹ và con cái.",
         ["foster mutual respect", "treat with mutual respect"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("parental guidance", "n.phr", "sự định hướng và chỉ dẫn của cha mẹ", "/pəˈrentl ˈɡaɪdns/",
         "Children navigate online risks much better under loving parental guidance.",
         "Trẻ em vượt qua các rủi ro trên mạng tốt hơn nhiều khi có sự chỉ dẫn yêu thương của cha mẹ.",
         ["seek parental guidance", "under parental guidance"],
         "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&w=800&q=80"),
        ("domestic harmony", "n.phr", "sự hòa thuận trong đời sống gia đình", "/dəˈmestɪk ˈhɑːməni/",
         "Sharing chores equally contributes directly to domestic harmony.",
         "Chia sẻ việc nhà công bằng đóng góp trực tiếp vào sự hòa thuận gia đình.",
         ["maintain domestic harmony", "disrupt domestic harmony"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("chores allocation", "n.phr", "sự phân công việc nhà hợp lý", "/tʃɔːz ˌæləˈkeɪʃn/",
         "A fair chores allocation chart on the fridge keeps everyone accountable.",
         "Bảng phân công việc nhà công bằng dán trên tủ lạnh giúp mọi người có trách nhiệm.",
         ["agree on chores allocation", "fair chores allocation"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("filial piety", "n.phr", "lòng hiếu thảo với cha mẹ ông bà", "/ˈfɪliəl ˈpaɪəti/",
         "Filial piety is a cornerstone of traditional Vietnamese ethical values.",
         "Lòng hiếu thảo là một trụ cột trong giá trị đạo đức truyền thống của người Việt.",
         ["practice filial piety", "deep filial piety"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("moral upbringing", "n.phr", "sự giáo dục đạo đức từ thuở nhỏ", "/ˈmɒrəl ˈʌpbrɪŋɪŋ/",
         "Her politeness and honesty reflect a rigorous moral upbringing at home.",
         "Sự lễ phép và tính trung thực phản ánh sự dạy dỗ đạo đức nghiêm cẩn từ gia đình.",
         ["credit for moral upbringing", "sound moral upbringing"],
         "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"),
        ("family bond", "n.phr", "tình cảm gắn kết thiêng liêng gia đình", "/ˈfæməli bɒnd/",
         "Cooking dinner together on weekends strengthens the family bond.",
         "Cùng nhau nấu bữa tối vào cuối tuần giúp thắt chặt tình cảm gắn kết gia đình.",
         ["strengthen family bonds", "cherish family bonds"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("role model", "n.phr", "tấm gương sáng để noi theo", "/ˈrəʊl mɒdl/",
         "Elder brothers often serve as a role model for their younger siblings.",
         "Anh trai thường đóng vai trò như một tấm gương sáng cho các em noi theo.",
         ["positive role model", "serve as a role model"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("quality time", "n.phr", "thời gian chất lượng dành cho nhau", "/ˈkwɒləti taɪm/",
         "Parents should set aside quality time each evening to converse with their kids.",
         "Cha mẹ nên dành thời gian quý báu mỗi buổi tối để trò chuyện cùng con cái.",
         ["spend quality time", "valuable quality time"],
         "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&w=800&q=80"),
        ("sibling rivalry", "n.phr", "sự cạnh tranh tị nạnh giữa anh chị em", "/ˈsɪblɪŋ ˈraɪvlri/",
         "Encouraging cooperation rather than comparison mitigates sibling rivalry.",
         "Khuyến khích hợp tác thay vì so sánh giúp giảm bớt sự tị nạnh giữa anh chị em.",
         ["resolve sibling rivalry", "cause sibling rivalry"],
         "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80"),
        ("nuclear family", "n.phr", "gia đình hạt nhân (chỉ bố mẹ và con)", "/ˌnjuːkliə ˈfæməli/",
         "The nuclear family is the predominant living structure in modern cities.",
         "Gia đình hạt nhân là mô hình sinh sống phổ biến nhất tại các đô thị hiện đại.",
         ["live in a nuclear family", "rise of the nuclear family"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("extended family", "n.phr", "đại gia đình nhiều thế hệ sống chung", "/ɪkˌstendɪd ˈfæməli/",
         "Living in an extended family allows grandparents to assist with childcare.",
         "Sống trong đại gia đình nhiều thế hệ giúp ông bà có thể hỗ trợ chăm sóc con trẻ.",
         ["support from extended family", "member of an extended family"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("homemaker", "n", "người nội trợ đảm đang chăm sóc tổ ấm", "/ˈhəʊmmeɪkə(r)/",
         "She decided to become a full-time homemaker to nurture her three toddlers.",
         "Bà quyết định trở thành người nội trợ toàn thời gian để chăm sóc ba đứa con thơ.",
         ["dedicated homemaker", "role of a homemaker"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("breadwinner", "n", "trụ cột kiếm tiền nuôi gia đình", "/ˈbredwɪnə(r)/",
         "In modern households, both husband and wife often act as co-breadwinners.",
         "Trong các gia đình hiện đại, cả vợ và chồng thường cùng là trụ cột kiếm thu nhập.",
         ["primary breadwinner", "sole breadwinner"],
         "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80"),
        ("groceries", "n.pl", "thực phẩm và đồ dùng gia đình mua sắm", "/ˈɡrəʊsəriz/",
         "He stops by the local supermarket to pick up fresh groceries after work.",
         "Anh ghé qua siêu thị địa phương để mua thực phẩm tươi sống sau giờ tan sở.",
         ["buy groceries", "carry groceries"],
         "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80"),
        ("ironing", "n", "việc là ủi quần áo phẳng phiu", "/ˈaɪənɪŋ/",
         "Listening to audiobooks makes Sunday afternoon ironing enjoyable.",
         "Nghe sách nói khiến công việc là ủi quần áo chiều Chủ nhật trở nên thú vị.",
         ["do the ironing", "pile of ironing"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("laundry detergent", "n.phr", "bột giặt hoặc nước giặt quần áo", "/ˈlɔːndri dɪˈtɜːdʒənt/",
         "Using eco-friendly laundry detergent protects clothes and river ecosystems.",
         "Dùng nước giặt thân thiện môi trường giúp bảo vệ vải vóc và nguồn nước.",
         ["eco-friendly laundry detergent", "measure laundry detergent"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("vacuum cleaner", "n.phr", "máy hút bụi sàn nhà", "/ˈvækjuːm kliːnə(r)/",
         "A robotic vacuum cleaner automatically navigates the living room rugs.",
         "Robot hút bụi tự động di chuyển làm sạch các tấm thảm trong phòng khách.",
         ["run the vacuum cleaner", "cordless vacuum cleaner"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("dishwashing liquid", "n.phr", "nước rửa bát diệt khuẩn", "/ˈdɪʃwɒʃɪŋ ˈlɪkwɪd/",
         "She chooses organic dishwashing liquid with gentle lemon scent.",
         "Cô chọn nước rửa chén hữu cơ với hương chanh tự nhiên dịu nhẹ cho da tay.",
         ["bottle of dishwashing liquid", "natural dishwashing liquid"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("family tree", "n.phr", "phả hệ gia phả các đời dòng họ", "/ˈfæməli triː/",
         "The grandfather showed the youngsters their family tree tracing back ten generations.",
         "Người ông chỉ cho lũ trẻ xem cây gia phả dòng họ lưu truyền mười thế hệ.",
         ["trace the family tree", "draw a family tree"],
         "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80"),
        ("chores checklist", "n.phr", "danh sách kiểm tra các việc nhà cần làm", "/tʃɔːz ˈtʃeklɪst/",
         "Tick off each completed task on the daily chores checklist.",
         "Đánh dấu vào từng công việc đã hoàn thành trong danh mục việc nhà mỗi ngày.",
         ["follow a chores checklist", "daily chores checklist"],
         "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80"),
        ("tidy up", "phr.v", "dọn dẹp và sắp xếp gọn gàng ngăn nắp", "/ˈtaɪdi ʌp/",
         "Please tidy up your study desk before turning in for bed.",
         "Làm ơn hãy dọn dẹp bàn học của con thật ngăn nắp trước khi đi ngủ.",
         ["tidy up the bedroom", "quick tidy up"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("mop the floor", "v.phr", "lau chùi sàn nhà sạch sẽ", "/mɒp ðə flɔː(r)/",
         "He mops the kitchen floor twice a week to remove greasy stains.",
         "Anh ấy lau sàn bếp hai lần một tuần để loại bỏ các vết dầu mỡ cứng đầu.",
         ["mop the floor thoroughly", "sweep and mop the floor"],
         "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80"),
        ("take out the trash", "v.phr", "đổ rác và vứt bỏ rác thải sinh hoạt", "/teɪk aʊt ðə træʃ/",
         "It is his designated turn to take out the trash before 8 PM.",
         "Đến lượt anh ấy phải đi đổ rác trước 8 giờ tối theo lịch phân công.",
         ["take out the trash daily", "forget to take out the trash"],
         "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"),
        ("set the table", "v.phr", "bày bát đũa chuẩn bị bữa ăn", "/set ðə ˈteɪbl/",
         "The children love helping their grandmother set the table with bowls and chopsticks.",
         "Những đứa trẻ thích giúp bà bày biện bát đũa lên bàn ăn trước bữa cơm.",
         ["set the table for dinner", "help set the table"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80"),
        ("household harmony", "n.phr", "sự thuận hòa và vui vẻ trong gia đình", "/ˈhaʊshəʊld ˈhɑːməni/",
         "Open dialogue between generations safeguards lasting household harmony.",
         "Đối thoại cởi mở giữa các thế hệ gìn giữ sự hòa thuận bền vững trong gia đình.",
         ["promote household harmony", "cherish household harmony"],
         "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80")
    ]
}

print("Loaded G10 mega boost definitions.")
